Comparison with baseline decision stump $We\_Re < 147$

# Libraries

In [1]:
import os
from pathlib import Path

import joblib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
RANDOM_STATE = 42

In [3]:
# train/test split
import sys
sys.path.insert(1, '../utils_functionality/split_utils/')
from split_tools import get_train_test

In [4]:
# dict with num features
sys.path.insert(1, '../utils_functionality/models/')
from modelling2_hyperparams import dict_num_features

# Selected models metrics

In [5]:
df_metrics = pd.DataFrame()
path_models = Path('../results/models_modelling_2/')

In [6]:
def calc_current_metrics(target, model, fnames=False):
    path_pipeline = path_models / model
    pipeline = joblib.load(path_pipeline)
    _, test = get_train_test(
        dataset_filename='df_modelling_dimensionless',
        target=target)
    if fnames: test = test[pipeline.steps[0][1].feature_names_+[target]]
    else: test = test[dict_num_features['df_modelling_dimensionless']\
                    +['wettability']+[target]]
    preds = pipeline.predict(test.drop(columns=[target]))
    df_current_metrics = pd.DataFrame({
            'model': [model],
            'target': [target],
            'accuracy': [accuracy_score(test[target], preds)],
            'f1': [f1_score(test[target], preds)],
            'precision': [precision_score(test[target], preds)],
            'recall': [recall_score(test[target], preds)],
            'roc_auc': [roc_auc_score(test[target], preds)]})
    return df_current_metrics

../results/models_modelling_2/logisticregression_splashing_df_modelling_dimensionless_onehot

In [7]:
df_current_metrics = calc_current_metrics(target='splashing', 
                                        model='logisticregression_splashing_df_modelling_dimensionless_onehot')
df_metrics = pd.concat((df_current_metrics, df_metrics))

../results/models_modelling_2/logisticregression_net_impact_df_modelling_dimensionless_ordenc

In [8]:
df_current_metrics = calc_current_metrics(target='net_impact', 
                                        model='logisticregression_net_impact_df_modelling_dimensionless_ordenc')
df_metrics = pd.concat((df_current_metrics, df_metrics))

../results/models_modelling_2/catboostclassifier_splashing_df_modelling_dimensionless

In [9]:
df_current_metrics = calc_current_metrics(target='splashing', 
                                        model='catboostclassifier_splashing_df_modelling_dimensionless',
                                        fnames=True)
df_metrics = pd.concat((df_current_metrics, df_metrics))

../results/models_modelling_2/catboostclassifier_net_impact_df_modelling_dimensionless

In [10]:
df_current_metrics = calc_current_metrics(target='net_impact', 
                                        model='catboostclassifier_net_impact_df_modelling_dimensionless',
                                        fnames=True)
df_metrics = pd.concat((df_current_metrics, df_metrics))

# Decision stump $We\_Re < 147$

splashing

In [11]:
target = 'splashing'
_, test = get_train_test(
    dataset_filename='df_modelling_dimensionless',
    target=target)
preds = (test['We_Re']>=147).astype(int)
df_current_metrics = pd.DataFrame({
        'model': ['decision_stump'],
        'target': [target],
        'accuracy': [accuracy_score(test[target], preds)],
        'f1': [f1_score(test[target], preds)],
        'precision': [precision_score(test[target], preds)],
        'recall': [recall_score(test[target], preds)],
        'roc_auc': [roc_auc_score(test[target], preds)]})
df_metrics = pd.concat((df_current_metrics, df_metrics))

net_impact

In [12]:
target = 'net_impact'
_, test = get_train_test(
    dataset_filename='df_modelling_dimensionless',
    target=target)
preds = (test['We_Re']<147).astype(int)
df_current_metrics = pd.DataFrame({
        'model': ['decision_stump'],
        'target': [target],
        'accuracy': [accuracy_score(test[target], preds)],
        'f1': [f1_score(test[target], preds)],
        'precision': [precision_score(test[target], preds)],
        'recall': [recall_score(test[target], preds)],
        'roc_auc': [roc_auc_score(test[target], preds)]})
df_metrics = pd.concat((df_current_metrics, df_metrics))

# Metrics comparison

In [13]:
df_metrics[df_metrics['target']=='splashing'].sort_values(by=['f1', 'roc_auc'], ascending=False)

,model,target,accuracy,f1,precision,recall,roc_auc
0,catboostclassifier_splashing_df_modelling_dime...,splashing,0.866667,0.900000,0.865385,0.937500,0.839120
0,logisticregression_splashing_df_modelling_dime...,splashing,0.840000,0.880000,0.846154,0.916667,0.810185
0,decision_stump,splashing,0.800000,0.845361,0.836735,0.854167,0.778935

In [14]:
df_metrics[df_metrics['target']=='net_impact'].sort_values(by=['f1', 'roc_auc'], ascending=False)

,model,target,accuracy,f1,precision,recall,roc_auc
0,catboostclassifier_net_impact_df_modelling_dim...,net_impact,0.946667,0.90,0.900000,0.9,0.931818
0,logisticregression_net_impact_df_modelling_dim...,net_impact,0.893333,0.80,0.800000,0.8,0.863636
0,decision_stump,net_impact,0.706667,0.56,0.466667,0.7,0.704545