Baseline comparison with model $K_l^{8/5}=649+3.76/R_{nd}^{0.63}$

# Libraries

In [1]:
import os
from pathlib import Path
import numpy as np

import joblib
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, roc_auc_score

In [2]:
RANDOM_STATE = 42

In [3]:
# train/test split
import sys
sys.path.insert(1, '../utils_functionality/split_utils/')
from split_tools import get_train_test

In [4]:
# dict with num features
sys.path.insert(1, '../utils_functionality/models/')
from modelling2_hyperparams import dict_num_features

# Selected models metrics

In [5]:
df_metrics = pd.DataFrame()
path_models = Path('../results/models_modelling_2/')

In [6]:
def calc_current_metrics(target, model, fnames=False):
    path_pipeline = path_models / model
    pipeline = joblib.load(path_pipeline)
    _, test = get_train_test(
        dataset_filename='df_modelling_dimensionless',
        target=target)
    if fnames: test = test[pipeline.steps[0][1].feature_names_+[target]]
    else: test = test[dict_num_features['df_modelling_dimensionless']\
                    +['wettability']+[target]]
    preds = pipeline.predict(test.drop(columns=[target]))
    df_current_metrics = pd.DataFrame({
            'model': [model],
            'target': [target],
            'accuracy': [accuracy_score(test[target], preds)],
            'f1': [f1_score(test[target], preds)],
            'precision': [precision_score(test[target], preds)],
            'recall': [recall_score(test[target], preds)],
            'roc_auc': [roc_auc_score(test[target], preds)]})
    return df_current_metrics

../results/models_modelling_2/logisticregression_splashing_df_modelling_dimensionless_ordenc

In [7]:
df_current_metrics = calc_current_metrics(target='splashing', 
                                        model='logisticregression_splashing_df_modelling_dimensionless_ordenc')
df_metrics = pd.concat((df_current_metrics, df_metrics))

No df was gotten.
Load dataset from: ..\data\before_drag_force_update\df_modelling_dimensionless.xlsx
Keep "splashing" from {'net_impact', 'splashing'}
Load split indexes from: ..\data\before_drag_force_update\df_ml_split_splashing.xlsx

../results/models_modelling_2/logisticregression_net_impact_df_modelling_dimensionless_ordenc

In [8]:
df_current_metrics = calc_current_metrics(target='net_impact', 
                                        model='logisticregression_net_impact_df_modelling_dimensionless_ordenc')
df_metrics = pd.concat((df_current_metrics, df_metrics))

No df was gotten.
Load dataset from: ..\data\before_drag_force_update\df_modelling_dimensionless.xlsx
Keep "net_impact" from {'net_impact', 'splashing'}
Load split indexes from: ..\data\before_drag_force_update\df_ml_split_net_impact.xlsx

../results/models_modelling_2/catboostclassifier_splashing_df_modelling_dimensionless

In [9]:
df_current_metrics = calc_current_metrics(target='splashing', 
                                        model='catboostclassifier_splashing_df_modelling_dimensionless',
                                        fnames=True)
df_metrics = pd.concat((df_current_metrics, df_metrics))

No df was gotten.
Load dataset from: ..\data\before_drag_force_update\df_modelling_dimensionless.xlsx
Keep "splashing" from {'net_impact', 'splashing'}
Load split indexes from: ..\data\before_drag_force_update\df_ml_split_splashing.xlsx

../results/models_modelling_2/catboostclassifier_net_impact_df_modelling_dimensionless

In [10]:
df_current_metrics = calc_current_metrics(target='net_impact', 
                                        model='catboostclassifier_net_impact_df_modelling_dimensionless',
                                        fnames=True)
df_metrics = pd.concat((df_current_metrics, df_metrics))

No df was gotten.
Load dataset from: ..\data\before_drag_force_update\df_modelling_dimensionless.xlsx
Keep "net_impact" from {'net_impact', 'splashing'}
Load split indexes from: ..\data\before_drag_force_update\df_ml_split_net_impact.xlsx

In [11]:
df_metrics

,model,target,accuracy,f1,precision,recall,roc_auc
0,catboostclassifier_net_impact_df_modelling_dim...,net_impact,0.946667,0.900000,0.900000,0.9000,0.931818
0,catboostclassifier_splashing_df_modelling_dime...,splashing,0.866667,0.900000,0.865385,0.9375,0.839120
0,logisticregression_net_impact_df_modelling_dim...,net_impact,0.893333,0.800000,0.800000,0.8000,0.863636
0,logisticregression_splashing_df_modelling_dime...,splashing,0.813333,0.865385,0.803571,0.9375,0.765046

# Comparsion with decision stump, splashing

In [12]:
path_data = Path('../data')
df_main = pd.read_excel(path_data / 'df_main.xlsx')

In [40]:
target = 'splashing'
train, test = get_train_test(
    dataset_filename='df_modelling_dimensionless',
    target=target)

No df was gotten.
Load dataset from: ..\data\before_drag_force_update\df_modelling_dimensionless.xlsx
Keep "splashing" from {'net_impact', 'splashing'}
Load split indexes from: ..\data\before_drag_force_update\df_ml_split_splashing.xlsx

In [30]:
test_full = test.merge(df_main, left_index=True, right_index=True,
                 how='left', suffixes=('', '_y'))
test_full.drop(test_full.filter(regex='_y$').columns, axis=1, inplace=True)
test_full.head()

,splashing,wettability,inclination,roughness_binary,particle_liquid_density_ratio,volume_fraction_binary,particle_droplet_diameter_ratio,Re,We,We_Re,...,sedimentation_velocity,sedimentation_Re,sedimentation_Stk,sign_sedimentation_Re,sign_sedimentation_Stk,sign_particle_droplet_diameter_ratio,droplet_density,free_fall_velocity,drag_velocity,relative_roughness
291,1,2,45,0,1.016949,1,0.078797,706.180601,951.652336,159.025989,...,2.619450e-05,0.000368,1.638124e-06,0.000368,1.638124e-06,0.078797,1181.774158,3.961141,3.787726,0.000713
328,0,0,0,0,1.016949,1,0.013259,950.005136,1920.347158,243.288377,...,5.969252e-07,0.000001,9.479131e-10,0.000001,9.479131e-10,0.013259,1181.618179,5.941712,5.365357,0.000032
4,1,1,0,0,1.219512,1,0.013833,1435.111557,1434.906112,233.148786,...,1.827262e-05,0.000092,8.582889e-08,0.000092,8.582889e-08,0.013833,836.795029,3.961141,3.668410,0.000013
313,0,1,45,0,0.847458,1,0.016339,256.976895,173.151643,52.684981,...,-4.952515e-06,0.000010,8.076139e-09,-0.000010,-8.076139e-09,-0.016339,1164.548521,1.980571,1.936740,0.000016
175,1,1,0,0,1.000000,1,0.011891,13292.675924,748.091989,293.684216,...,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.011891,1000.000000,3.961141,3.757249,0.000011

In [15]:
test_full['kl'] = (649 + 3.76 / (
    (test_full['roughness'] / (test_full['droplet_diameter']*(10**6))) ** 0.63)) ** (5/8)
preds = test_full['We_Re'] > test_full['kl']
df_current_metrics = pd.DataFrame({
        'model': ['decision_stump_baseline'],
        'target': [target],
        'accuracy': [accuracy_score(test[target], preds)],
        'f1': [f1_score(test[target], preds)],
        'precision': [precision_score(test[target], preds)],
        'recall': [recall_score(test[target], preds)],
        'roc_auc': [roc_auc_score(test[target], preds)]})
df_metrics = pd.concat((df_current_metrics, df_metrics))
df_metrics

,model,target,accuracy,f1,precision,recall,roc_auc
0,decision_stump_baseline,splashing,0.760000,0.800000,0.857143,0.7500,0.763889
0,catboostclassifier_net_impact_df_modelling_dim...,net_impact,0.946667,0.900000,0.900000,0.9000,0.931818
0,catboostclassifier_splashing_df_modelling_dime...,splashing,0.866667,0.900000,0.865385,0.9375,0.839120
0,logisticregression_net_impact_df_modelling_dim...,net_impact,0.893333,0.800000,0.800000,0.8000,0.863636
0,logisticregression_splashing_df_modelling_dime...,splashing,0.813333,0.865385,0.803571,0.9375,0.765046

In [38]:
# test for pure modelling
test_full[preds & test_full['splashing']==1].sort_index().tail(10)['test']

244    267
247    270
257    281
265    289
271    295
291    315
320    344
322    346
323    347
336    360
Name: test, dtype: int64

In [42]:
train_full = train.merge(df_main, left_index=True, right_index=True,
                 how='left', suffixes=('', '_y'))
train_full.drop(train_full.filter(regex='_y$').columns, axis=1, inplace=True)
train_full.head()

,splashing,wettability,inclination,roughness_binary,particle_liquid_density_ratio,volume_fraction_binary,particle_droplet_diameter_ratio,Re,We,We_Re,...,sedimentation_velocity,sedimentation_Re,sedimentation_Stk,sign_sedimentation_Re,sign_sedimentation_Stk,sign_particle_droplet_diameter_ratio,droplet_density,free_fall_velocity,drag_velocity,relative_roughness
311,0,1,45,0,0.847458,1,0.013973,300.480858,202.464716,59.241886,...,-0.000005,0.000010,6.906866e-09,-0.000010,-6.906866e-09,-0.013973,1164.312775,1.980571,1.945223,0.000013
12,1,2,0,0,1.000000,1,0.044141,11864.379801,667.709612,269.683934,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.044141,1000.000000,3.961141,3.725683,0.000799
339,1,2,0,0,1.000000,1,0.014310,16568.235035,1398.653361,424.301052,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.014310,1000.000000,5.941712,5.206027,0.000859
204,1,2,0,0,1.000000,1,0.012652,6246.415048,175.769464,117.863525,...,0.000000,0.000000,0.000000e+00,0.000000,0.000000e+00,0.012652,1000.000000,1.980571,1.944673,0.000759
54,0,2,0,0,1.864407,1,0.012307,682.304008,919.476126,154.976093,...,0.000030,0.000065,8.225391e-08,0.000065,8.225391e-08,0.012307,1294.435402,3.961141,3.795320,0.000738

In [45]:
train_full['kl'] = (649 + 3.76 / (
    (train_full['roughness'] / (train_full['droplet_diameter']*(10**6))) ** 0.63)) ** (5/8)
preds = train_full['We_Re'] > train_full['kl']
df_current_metrics = pd.DataFrame({
        'model': ['decision_stump_baseline'],
        'target': [target],
        'accuracy': [accuracy_score(train[target], preds)],
        'f1': [f1_score(train[target], preds)],
        'precision': [precision_score(train[target], preds)],
        'recall': [recall_score(train[target], preds)],
        'roc_auc': [roc_auc_score(train[target], preds)]})
df_current_metrics

,model,target,accuracy,f1,precision,recall,roc_auc
0,decision_stump_baseline,splashing,0.777778,0.814607,0.884146,0.755208,0.787128

In [47]:
# train for pure modelling
train_full[preds & train_full['splashing']==1].sort_index().tail(10)['test']

338    362
339    363
340    364
341    365
342    366
343    367
344    368
345    369
346    370
347    371
Name: test, dtype: int64

In [28]:
df_spl_metrics = df_metrics[df_metrics['target']=='splashing']
df_spl_metrics.round(3)

,model,target,accuracy,f1,precision,recall,roc_auc
0,decision_stump_baseline,splashing,0.760,0.800,0.857,0.750,0.764
0,catboostclassifier_splashing_df_modelling_dime...,splashing,0.867,0.900,0.865,0.938,0.839
0,logisticregression_splashing_df_modelling_dime...,splashing,0.813,0.865,0.804,0.938,0.765

In [30]:
print(pd.DataFrame.to_latex(df_spl_metrics.round(3)))

\begin{tabular}{lllrrrrr}
\toprule
 & model & target & accuracy & f1 & precision & recall & roc_auc \\
\midrule
0 & decision_stump_baseline & splashing & 0.760000 & 0.800000 & 0.857000 & 0.750000 & 0.764000 \\
0 & catboostclassifier_splashing_df_modelling_dimensionless & splashing & 0.867000 & 0.900000 & 0.865000 & 0.938000 & 0.839000 \\
0 & logisticregression_splashing_df_modelling_dimensionless_ordenc & splashing & 0.813000 & 0.865000 & 0.804000 & 0.938000 & 0.765000 \\
\bottomrule
\end{tabular}

In [46]:
first_row = df_spl_metrics.iloc[0, 2:]
df_percent_change = (df_spl_metrics.iloc[:, 2:] - first_row) / first_row * 100
df_percent_change.astype(float).round(1)

   accuracy    f1  precision  recall  roc_auc
0       0.0   0.0        0.0     0.0      0.0
0      14.0  12.5        1.0    25.0      9.8
0       7.0   8.2       -6.2    25.0      0.2