In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

## Main df

In [2]:
# Import data
df_main = pd.read_excel('../data/df_main.xlsx', index_col=0).reset_index(drop=True)
## Drop unused columns
# drop_columns = ['voltage', 'long_impulse_duration', 'long_impulse_dur_binary']
# df_main = df_main.drop(drop_columns, axis=1)
display(df_main.head())
df_main.info()

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,roughness,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
0,3,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
1,4,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
2,5,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
3,7,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small
4,8,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 28 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   test                             372 non-null    int64
 1   one_drop                         372 non-null    int64
 2   splashing                        372 non-null    int64
 3   breaking_up                      372 non-null    int64
 4   net_impact                       372 non-null    int64
 5   rebound                          372 non-null    int64
 6   voltage                          372 non-null    float64
 7   long_impulse_duration            372 non-null    int64
 8   height                           372 non-null    float64
 9   inclination                      372 non-null    int64
 10  droplet_diameter                 372 non-null    float64
 11  liquid_density                   372 non-null    int64
 12  surface_tension                  372 non-null    float64
 13  viscosity                        372 non-null    float64
 14  particle_mean_diameter           372 non-null    float64
 15  particle_liquid_density_ratio    372 non-null    float64
 16  volume_fraction                  372 non-null    float64
 17  wettability                      372 non-null    object
 18  roughness                        372 non-null    float64
 19  long_impulse_dur_binary          372 non-null    object
 20  roughness_binary                 372 non-null    int64
 21  volume_fraction_binary           372 non-null    int64
 22  velocity                         372 non-null    float64
 23  Re                               372 non-null    float64
 24  We                               372 non-null    float64
 25  We_Re                            372 non-null    float64
 26  particle_droplet_diameter_ratio  372 non-null    float64
 27  particle_diameter_cat            372 non-null    object
dtypes: float64(14), int64(11), object(3)
memory usage: 81.5+ KB

In [3]:
label_name = ['net_impact', 'splashing', 'breaking_up', 'rebound']

class_count_dict = {}

for label in label_name:
    class_count_dict[label] = df_main[df_main[label]==1].shape[0]

class_count_s = pd.Series(class_count_dict)
class_count_s

net_impact     121
splashing      174
breaking_up    101
rebound         99
dtype: int64

**Labels description:**
- **splashing**: when *'Number of detached small droplets during Spreading'=='many' (more than 5)*;
- **breaking_up**: combines clear "breaking_up" during receding *'Droplet Receding'==2*, as well as the Spreading detaching *0<'Number of detached small droplets during Spreading'<=5*;
- **rebound**: combines all rebound types (partial and total, *'Rebound'>0*), as well as the central jet ejection *'Rim merging or Central jet ejecting'==2*
- **net_impact**: when there is 
    - **no Splashing** (no small droplets detached during spreading, *'Number of detached small droplets during Spreading'==0*), 
    - **no Breaking up** (*'Droplet Receding'<2* [equivalent is *'Number of detached small droplets during Receding or Rim merging' == 0*])
    - **no Rebound** (*'Rebound' == 0*)

**Total count of clear experiments is *372***

## Suspension Data Labeling Edited. For the classes reconfiguration

In [4]:
df_labels = pd.read_excel('../data/Suspension Data Labeling Edited.xlsx', index_col=0)
df_labels = df_labels.drop(index=0)
# Keep only used 372 tests (without draft substrated and liquids)
df_labels = df_labels[df_labels['Test #'].isin(df_main.test.values)]
df_labels = df_labels.drop('Comments', axis=1)
df_labels = df_labels.rename({'Test #': 'test'}, axis=1)
df_labels['test'] = df_labels['test'].astype(int)
df_labels = df_labels.reset_index(drop=True)
display(df_labels)
display(df_labels.info())
df_labels.columns

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
0,3,1,many,0,0,0,0,0,1
1,4,1,many,0,0,0,0,0,1
2,5,1,many,0,0,0,0,0,1
3,7,0,many,1,0,0,0,0,2
4,8,0,many,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...
367,391,0,0,1,2,0,2,0,0
368,392,1,3,1,1,0,0,0,1
369,393,1,2,1,1,0,0,0,3
370,394,1,0,1,1,1,0,0,2
371,395,1,0,1,2,0,2,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 9 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   test                                                              372 non-null    int32
 1   Total number of dropped drops                                     372 non-null    object
 2   Number of detached small droplets during Spreading                372 non-null    object
 3   Droplet Receding                                                  372 non-null    object
 4   Rim merging or Central jet ejecting                               372 non-null    object
 5   Number of detached small droplets during Receding or Rim merging  372 non-null    object
 6   Rebound                                                           372 non-null    object
 7   Number of detached droplets during Rebound                        372 non-null    object
 8   Final droplets count                                              372 non-null    object
dtypes: int32(1), object(8)
memory usage: 24.8+ KB

None

Index(['test', 'Total number of dropped drops',
       'Number of detached small droplets during Spreading',
       'Droplet Receding', 'Rim merging or Central jet ejecting',
       'Number of detached small droplets during Receding or Rim merging',
       'Rebound', 'Number of detached droplets during Rebound',
       'Final droplets count'],
      dtype='object')


| Parameter name | Description | Possible values |
| --- | --- | --- |
| Total number of dropped drops | The total number of drops that fell from above | 1, 2 |
| Number of detached small droplets during *spreading* | The number of small droplets that flew out of the lamella drops in the process of spreading | 0, 1, .., 5, many |
| Droplet Receding | Presence (1,2), absence — 0 of a visible drop shrinkage, and an increase in the drop height after reaching the maximum spot diameter. 1 — the usual reduction of the main drop, 2 — the destruction of the main drop in the process of reduction | 0, 1, 2 |
| Rim merging or Central jet ejecting | The presence (1,2), absence — 0 of an explicit rim merging at the end of the shrinkage of the drop (1) and/or the reverse vertical jet (2) (against gravity) | 0, 1, 2 |
| Number of detached small droplets during *Receding or Rim merging* | The number of small droplets separating from the rim of the main drop (rim) and remaining on the substrate during the shrinkage of the drop (receding). Drops do not separate — 0, several drops, many drops — many | 0, 1, .., 5, many |
| Rebound | Presence (1,2), absence — 0 of a drop rebound after the formation of a reverse vertical jet (central jet ejecting). Partial rebound — 1, total rebound - 2 | 0, 1, 2 |
| Number of detached droplets during *Rebound* | The number of droplets separating from the reverse vertical jet (central jet) | 0, 1, .., 5, many |
| Final droplets count | The total number of droplets on the substrate, clearly separated from each other | 1, .., 5, many |

# Show strange tests

Let us consider non-splashing tests when We_Re larger than 150 and splashing before 150.
Do they have correct labels?

On the boundary

In [17]:
df_main[(df_main['splashing'] == 0) & (df_main['We_Re']>150) & (df_main['We_Re']<160)]

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,roughness,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
38,51,0,0,1,0,0,106.5,12,0.8,0,...,0.10,low,0,1,3.961141,677.852440,913.477171,154.217138,0.012388,small
40,53,0,0,0,1,0,105.0,12,0.8,0,...,0.04,low,0,1,3.961141,677.852440,913.477171,154.217138,0.012388,small
41,54,0,0,0,1,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,677.852440,913.477171,154.217138,0.012388,small
43,56,0,0,1,0,1,106.0,12,0.8,0,...,2.49,low,0,1,3.961141,677.852440,913.477171,154.217138,0.012388,small
46,59,1,0,1,0,0,107.0,12,0.8,0,...,2.49,low,0,1,3.961141,693.028241,933.928153,156.799425,0.012117,small
47,60,1,0,1,0,0,107.0,12,0.8,0,...,0.04,low,0,1,3.961141,693.028241,933.928153,156.799425,0.012117,small
49,63,0,0,0,1,0,109.0,12,0.8,0,...,0.10,low,0,1,3.961141,653.571158,880.755601,150.055157,0.012848,small
53,69,1,0,0,0,1,108.0,15,0.8,0,...,2.49,high,0,1,3.961141,682.304008,919.476126,154.976093,0.012307,small
54,70,1,0,1,0,1,103.5,21,0.8,0,...,2.49,high,0,1,3.961141,682.304008,919.476126,154.976093,0.012307,small
60,78,1,0,1,0,0,108.0,15,0.8,0,...,0.10,high,0,1,3.961141,687.969640,927.111159,155.940249,0.040441,medium
61,79,1,0,0,1,0,108.0,15,0.8,0,...,0.04,high,0,1,3.961141,687.969640,927.111159,155.940249,0.040441,medium
63,81,0,0,1,0,0,108.0,15,0.8,0,...,10.89,high,1,1,3.961141,653.571158,880.755601,150.055157,0.042570,medium
86,109,1,0,1,0,0,110.0,15,0.8,0,...,0.04,high,0,0,3.961141,683.922760,921.657564,155.251770,0.012278,small
87,110,1,0,1,0,0,110.0,15,0.8,0,...,2.49,high,0,0,3.961141,671.782119,905.296779,153.180188,0.012500,small
94,117,1,0,0,1,0,110.0,15,0.8,0,...,0.10,high,0,0,3.961141,679.875880,916.203969,154.562272,0.012351,small
123,146,1,0,1,0,0,109.0,15,0.8,0,...,0.10,high,0,0,3.961141,685.946200,924.384361,155.596136,0.081121,large
125,148,1,0,0,1,0,109.0,15,0.8,0,...,0.04,high,0,0,3.961141,692.016521,932.564754,156.627716,0.080409,large
127,150,1,0,1,0,0,109.0,15,0.8,0,...,0.04,high,0,0,3.961141,683.922760,921.657564,155.251770,0.081361,large
142,165,1,0,1,0,0,110.0,15,0.8,0,...,0.10,high,0,0,3.961141,669.758679,902.569981,152.834018,0.041541,medium
144,167,1,0,0,1,0,110.0,15,0.8,0,...,0.04,high,0,0,3.961141,677.852440,913.477171,154.217138,0.041045,medium
146,169,1,0,1,0,1,110.0,15,0.8,0,...,2.49,high,0,0,3.961141,685.946200,924.384361,155.596136,0.040560,medium
149,172,1,0,1,0,0,110.0,15,0.8,0,...,0.10,high,0,0,3.961141,667.735239,899.843184,152.487586,0.041667,medium
150,173,1,0,0,1,0,110.0,15,0.8,0,...,10.89,high,1,0,3.961141,670.770399,903.933380,153.007135,0.041478,medium
151,174,1,0,0,1,0,106.0,15,0.8,0,...,0.10,high,0,0,3.961141,655.594599,883.482398,150.403448,0.012809,small
152,175,1,0,0,1,0,106.0,15,0.8,0,...,0.10,high,0,0,3.961141,673.805560,908.023576,153.526097,0.012462,small
157,180,1,0,0,1,0,104.0,15,0.8,0,...,0.04,high,0,0,3.961141,661.664919,891.662791,151.446712,0.012691,small
184,207,1,0,1,0,0,100.0,15,0.8,0,...,0.10,high,0,1,3.961141,665.711799,897.116386,152.140892,0.012614,small
185,208,0,0,0,1,0,108.0,15,0.8,0,...,0.10,high,0,1,3.961141,663.688359,894.389588,151.793934,0.012652,small
186,209,1,0,0,1,0,106.0,15,0.8,0,...,0.04,high,0,1,3.961141,665.711799,897.116386,152.140892,0.012614,small
193,216,1,0,1,0,0,108.0,15,0.8,0,...,0.04,high,0,1,3.961141,665.711799,897.116386,152.140892,0.083587,large
249,272,1,0,0,1,0,103.0,15,0.8,20,...,0.04,high,0,1,3.961141,655.594599,883.482398,150.403448,0.012809,small
250,273,1,0,0,1,0,103.0,15,0.8,20,...,0.04,high,0,1,3.961141,667.735239,899.843184,152.487586,0.012576,small
251,274,1,0,1,0,1,101.0,15,0.8,20,...,2.49,high,0,1,3.961141,669.758679,902.569981,152.834018,0.012538,small
255,279,1,0,0,1,0,101.0,15,0.8,20,...,0.10,high,0,1,3.961141,677.852440,913.477171,154.217138,0.012388,small
256,280,1,0,0,1,0,101.0,15,0.8,20,...,10.89,high,1,1,3.961141,672.456600,906.205711,153.295520,0.012487,small
257,281,0,0,1,0,1,101.0,15,0.8,20,...,2.49,high,0,1,3.961141,661.440092,891.359813,151.408115,0.012695,small
263,287,0,0,1,0,0,106.0,15,0.8,20,...,0.04,high,0,1,3.961141,694.545821,935.973251,157.056872,0.080117,large
279,303,1,0,0,1,0,101.0,12,0.8,45,...,10.89,low,1,1,3.961141,661.664919,891.662791,151.446712,0.012691,small
281,305,1,0,0,1,0,105.0,12,0.8,45,...,0.04,low,0,1,3.961141,689.993081,929.837956,156.284108,0.012170,small
282,306,1,0,0,0,1,105.0,12,0.8,45,...,2.49,low,0,1,3.961141,663.688359,894.389588,151.793934,0.012652,small
283,307,1,0,1,0,0,105.0,12,0.8,45,...,0.10,low,0,1,3.961141,669.758679,902.569981,152.834018,0.012538,small
288,312,1,0,0,1,0,105.0,12,0.8,45,...,10.89,low,1,1,3.961141,677.852440,913.477171,154.217138,0.012388,small
289,313,1,0,0,1,0,105.0,12,0.8,45,...,10.89,low,1,1,3.961141,669.758679,902.569981,152.834018,0.012538,small

### Outliers

In [18]:
df_main[(df_main['splashing'] == 0) & (df_main['We_Re']>160)]

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,roughness,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
8,16,1,0,1,0,0,103.0,18,0.8,0,...,0.10,high,0,1,3.961141,11274.017403,634.484896,259.555550,0.046453,medium
9,17,0,0,1,0,0,103.0,21,0.8,0,...,0.10,high,0,1,3.961141,11559.676628,650.561372,264.472523,0.045305,medium
10,18,0,0,1,0,0,103.0,18,0.8,0,...,0.04,high,0,1,3.961141,11559.676628,650.561372,264.472523,0.045305,medium
11,19,0,0,0,1,0,103.0,18,0.8,0,...,0.04,high,0,1,3.961141,11559.676628,650.561372,264.472523,0.045305,medium
17,26,1,0,1,0,0,108.0,10,0.8,0,...,0.04,low,0,1,3.961141,11426.368989,643.059016,262.181762,0.045833,medium
18,27,0,0,1,0,0,108.0,10,0.8,0,...,0.10,low,0,1,3.961141,11883.423749,668.781377,270.008528,0.044071,medium
70,91,1,0,0,1,0,112.5,12,0.8,0,...,0.04,low,0,0,3.961141,12662.760711,712.641300,283.183271,0.012483,small
72,93,1,0,0,1,0,114.0,12,0.8,0,...,0.04,low,0,0,3.961141,12645.181682,711.651978,282.888374,0.012500,small
73,94,1,0,0,1,0,114.0,12,0.8,0,...,0.10,low,0,0,3.961141,13445.027511,756.666109,296.205123,0.011756,small
74,95,1,0,0,1,0,114.0,12,0.8,0,...,0.10,low,0,0,3.961141,13787.818581,775.957880,301.851240,0.011464,small
95,118,1,0,1,0,0,114.0,10,0.8,0,...,0.10,low,0,0,3.961141,12949.884855,728.800219,287.985568,0.040441,medium
96,119,0,0,1,0,0,114.0,10,0.8,0,...,0.10,low,0,0,3.961141,12607.093785,709.508448,282.249078,0.041541,medium
97,120,0,0,0,1,0,112.0,10,0.8,0,...,0.04,low,0,0,3.961141,13026.060648,733.087279,289.255160,0.040205,medium
98,121,1,0,0,1,0,112.0,10,0.8,0,...,0.04,low,0,0,3.961141,13064.148545,735.230809,289.889260,0.040087,medium
102,125,1,0,1,0,0,112.0,10,0.8,0,...,0.04,low,0,0,3.961141,13064.148545,735.230809,289.889260,0.040087,medium
103,126,1,0,0,1,0,112.0,10,0.8,0,...,0.10,low,0,0,3.961141,10982.010195,618.051166,254.497005,0.047688,medium
109,132,1,0,0,1,0,106.0,12,0.8,0,...,0.10,low,0,0,3.961141,6287.973588,716.135774,238.300724,0.013518,small
170,193,1,0,0,1,0,110.0,12,0.8,0,...,0.10,low,0,1,3.961141,12835.621165,722.369628,286.077671,0.012315,small
171,194,1,0,0,1,0,110.0,12,0.8,0,...,0.04,low,0,1,3.961141,12873.709061,724.513158,286.714107,0.012278,small
175,198,1,0,0,1,0,110.0,12,0.8,0,...,0.04,low,0,1,3.961141,13292.675924,748.091989,293.684216,0.011891,small
244,267,1,0,0,1,0,111.0,12,0.8,20,...,0.04,low,0,1,3.961141,13216.500131,743.804929,292.421057,0.011960,small
246,269,1,0,0,1,0,110.0,12,0.8,20,...,0.10,low,0,1,3.961141,13026.060648,733.087279,289.255160,0.012135,small
264,288,1,0,0,1,0,108.0,15,0.8,45,...,0.04,high,0,1,3.961141,13559.291201,763.096699,298.091117,0.011657,small
266,290,1,0,0,1,0,106.0,15,0.8,45,...,0.10,high,0,1,3.961141,12873.709061,724.513158,286.714107,0.012278,small
267,291,1,0,0,1,0,106.0,15,0.8,45,...,0.04,high,0,1,3.961141,13254.588028,745.948459,293.052863,0.011925,small
269,293,1,0,0,1,0,106.0,15,0.8,45,...,0.10,high,0,1,3.961141,13073.670519,735.766691,290.047713,0.012090,small
319,343,1,0,1,0,0,108.0,12,1.8,0,...,0.04,low,0,1,5.941712,937.864495,1895.805980,240.952795,0.088997,large
323,347,1,0,1,0,0,109.0,12,1.8,0,...,0.04,low,0,1,5.941712,959.110616,1938.753041,245.035168,0.087025,large
325,349,1,0,0,1,0,107.0,12,1.8,0,...,0.04,low,0,1,5.941712,953.040296,1926.482452,243.871104,0.013217,small
327,351,1,0,0,1,0,107.0,12,1.8,0,...,0.10,low,0,1,5.941712,989.462218,2000.105985,250.828169,0.012730,small
328,352,1,0,0,1,0,107.0,12,1.8,0,...,0.10,low,0,1,5.941712,950.005136,1920.347158,243.288377,0.013259,small
329,353,1,0,0,1,0,107.0,12,1.8,0,...,0.04,low,0,1,5.941712,974.286417,1969.429513,247.937309,0.012928,small
331,355,1,0,1,0,0,102.0,12,1.8,0,...,0.04,low,0,1,5.941712,837.704209,1693.341264,221.383332,0.015036,small
334,358,1,0,0,1,0,102.0,12,1.8,0,...,0.04,low,0,1,5.941712,673.805560,1362.035364,188.030300,0.018694,small
337,361,1,0,0,1,0,102.0,12,1.8,0,...,0.04,low,0,1,5.941712,736.532203,1488.831449,201.011406,0.017102,small
341,365,1,0,0,1,0,112.0,12,1.8,0,...,0.10,low,0,1,5.941712,16911.026104,1427.591016,430.868151,0.014020,small

New types in "Number of detached small droplets during Spreading":

- **many small** - when tiny droplets or even particles are detached from the droplet
- **gear** - when branches appear, without explicit detaching.

If "many small" case, gear is not written

TODO: Continue from **351**