# Import Libraries

Enable automatic reloading of modules during interactive development:

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit # type: ignore

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [2]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.404380
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.376612
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.397960
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.389046
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.401565
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.371844
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.387222
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.384420
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Fri, 11 Oct 2024   Pseudo R-squ.:                  0.4082
Time:                        14:46:47   Log-Likelihood:                -114.17
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 1.983e-31
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
inclination                       2.9317      0.637      4.602      0.000       1.683       4.180
volume_fraction                   3.2403      0.861      3.764      0.000       1.553       4.928
sign_sedimentation_Re             0.6854      0.204      3.364      0.001       0.286       1.085
particle_liquid_density_ratio    -0.3194      0.139     -2.300      0.021      -0.591      -0.047
relative_roughness                0.3266      0.167      1.954      0.051      -0.001       0.654
K                                 3.7320      0.503      7.422      0.000       2.747       4.717
wettability                      -0.5327      0.211     -2.527      0.011      -0.946      -0.120
=================================================================================================

                                            0
target                              splashing
model                    Logit_splashing_base
holdout_test_accuracy                0.826667
holdout_test_f1                      0.871287
holdout_test_roc_auc                  0.87963
cv_test_accuracy_median              0.754717
cv_test_f1_median                    0.816901
cv_test_roc_auc_median               0.904025

Model saved in ../results/models_modelling3/Logit_splashing_base

In [3]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sign_particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'sedimentation_Stk',
        'sign_sedimentation_Stk',
        # 'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    model_postfix='base',
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.331186
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.313922
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.330520
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.313094
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.330763
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.317059
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.336114
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.331494
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Fri, 11 Oct 2024   Pseudo R-squ.:                  0.4277
Time:                        14:46:47   Log-Likelihood:                -98.454
converged:                       True   LL-Null:                       -172.03
Covariance Type:            nonrobust   LLR p-value:                 3.087e-29
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
inclination                      -4.4363      0.765     -5.796      0.000      -5.936      -2.936
volume_fraction                  -6.0775      1.120     -5.428      0.000      -8.272      -3.883
sign_sedimentation_Re            -0.6237      0.207     -3.009      0.003      -1.030      -0.218
particle_liquid_density_ratio     0.3685      0.154      2.399      0.016       0.067       0.670
relative_roughness               -0.4835      0.184     -2.624      0.009      -0.845      -0.122
K                                -3.9397      0.540     -7.296      0.000      -4.998      -2.881
wettability                       1.2644      0.256      4.944      0.000       0.763       1.766
=================================================================================================

                                                   0
target                              no_fragmentation
model                    Logit_no_fragmentation_base
holdout_test_accuracy                           0.84
holdout_test_f1                             0.727273
holdout_test_roc_auc                        0.908182
cv_test_accuracy_median                     0.849057
cv_test_f1_median                           0.692308
cv_test_roc_auc_median                      0.910256

Model saved in ../results/models_modelling3/Logit_no_fragmentation_base