Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!
No optimization was used.

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
features_to_drop = (
    'Re', 
    'We', 
    'init_volume_fraction',
    'particle_droplet_diameter_ratio',
    'sedimentation_Re',
    'particle_liquid_density_ratio',
    # 'sedimentation_Stk',
    # 'sign_sedimentation_Re',
    # 'volume_fraction', 
    # 'relative_roughness', 
    # 'inclination',
    # 'wettability',
    # 'K',
)
log_features=(
    'relative_roughness',
    'sedimentation_Stk',
)
minmax_features_splash=(
    # 'relative_roughness',
    'inclination',
    'volume_fraction',
)
passthrough_features_splash=(
    'wettability',
)
minmax_features_no_fragm=(
    # 'relative_roughness',
)
passthrough_features_no_fragm=(
    'wettability',
    'inclination',
    'volume_fraction',
)
add_const=False
model_postfix='Stk'

# Logit

In [5]:
estimator = StatsModelsEstimator(Logit)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.396331
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.365700
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.384199
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.366459
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.390900
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.367264
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.371445
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.372357
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4268
Time:                        13:06:30   Log-Likelihood:                -110.59
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 6.018e-33
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
inclination               3.2523      0.632      5.145      0.000       2.013       4.491
volume_fraction           1.9645      0.910      2.158      0.031       0.181       3.748
sign_sedimentation_Re     0.4562      0.213      2.141      0.032       0.039       0.874
sedimentation_Stk         0.9033      0.276      3.272      0.001       0.362       1.444
relative_roughness        0.2893      0.171      1.691      0.091      -0.046       0.625
K                         3.6330      0.447      8.123      0.000       2.756       4.510
wettability              -0.6507      0.218     -2.983      0.003      -1.078      -0.223
=========================================================================================

                                           0
target                             splashing
model                    Logit_splashing_Stk
holdout_test_accuracy               0.813333
holdout_test_f1                         0.86
holdout_test_roc_auc                0.884259
cv_test_accuracy_median             0.792453
cv_test_f1_median                    0.84058
cv_test_roc_auc_median              0.859133

Model saved in ../results/models_modelling3/Logit_splashing_Stk

In [6]:
estimator = StatsModelsEstimator(Logit)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimization terminated successfully.
         Current function value: 0.283411
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.267936
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.295330
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.273705
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.279036
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.277998
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.304520
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.288682
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.5016
Time:                        13:06:31   Log-Likelihood:                -85.739
converged:                       True   LL-Null:                       -172.03
Covariance Type:            nonrobust   LLR p-value:                 1.271e-34
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
sign_sedimentation_Re    -0.4217      0.243     -1.734      0.083      -0.898       0.055
sedimentation_Stk        -1.0316      0.303     -3.410      0.001      -1.625      -0.439
relative_roughness       -0.4388      0.197     -2.224      0.026      -0.825      -0.052
K                        -4.1980      0.575     -7.306      0.000      -5.324      -3.072
wettability               1.6952      0.310      5.462      0.000       1.087       2.304
inclination              -6.2928      1.060     -5.935      0.000      -8.371      -4.215
volume_fraction         -19.0501      3.763     -5.063      0.000     -26.425     -11.675
=========================================================================================

                                                  0
target                             no_fragmentation
model                    Logit_no_fragmentation_Stk
holdout_test_accuracy                          0.88
holdout_test_f1                            0.790698
holdout_test_roc_auc                       0.945455
cv_test_accuracy_median                    0.851852
cv_test_f1_median                          0.689655
cv_test_roc_auc_median                     0.917582

Model saved in ../results/models_modelling3/Logit_no_fragmentation_Stk

# Logistic Regression

In [7]:
estimator = LogisticRegression(
    fit_intercept=False,
)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                        0
target                                          splashing
model                    LogisticRegression_splashing_Stk
holdout_test_accuracy                            0.813333
holdout_test_f1                                      0.86
holdout_test_roc_auc                              0.88966
cv_test_accuracy_median                          0.792453
cv_test_f1_median                                0.835821
cv_test_roc_auc_median                           0.854489

Model saved in ../results/models_modelling3/LogisticRegression_splashing_Stk

In [8]:
estimator = LogisticRegression(
    fit_intercept=False,
)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                               0
target                                          no_fragmentation
model                    LogisticRegression_no_fragmentation_Stk
holdout_test_accuracy                                   0.853333
holdout_test_f1                                         0.755556
holdout_test_roc_auc                                    0.925455
cv_test_accuracy_median                                  0.87037
cv_test_f1_median                                           0.75
cv_test_roc_auc_median                                  0.941392

Model saved in ../results/models_modelling3/LogisticRegression_no_fragmentation_Stk

# KNClassifier

In [9]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                          0
target                                            splashing
model                    KNeighborsClassifier_splashing_Stk
holdout_test_accuracy                              0.786667
holdout_test_f1                                    0.829787
holdout_test_roc_auc                               0.859568
cv_test_accuracy_median                            0.792453
cv_test_f1_median                                   0.84507
cv_test_roc_auc_median                             0.896285

Model saved in ../results/models_modelling3/KNeighborsClassifier_splashing_Stk

In [10]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                 0
target                                            no_fragmentation
model                    KNeighborsClassifier_no_fragmentation_Stk
holdout_test_accuracy                                     0.866667
holdout_test_f1                                           0.736842
holdout_test_roc_auc                                      0.942273
cv_test_accuracy_median                                   0.833333
cv_test_f1_median                                         0.666667
cv_test_roc_auc_median                                    0.907509

Model saved in ../results/models_modelling3/KNeighborsClassifier_no_fragmentation_Stk

# SVC

In [11]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                         0
target                           splashing
model                    SVC_splashing_Stk
holdout_test_accuracy             0.826667
holdout_test_f1                   0.868687
holdout_test_roc_auc              0.935185
cv_test_accuracy_median           0.830189
cv_test_f1_median                 0.865672
cv_test_roc_auc_median            0.917957

Model saved in ../results/models_modelling3/SVC_splashing_Stk

In [12]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                0
target                           no_fragmentation
model                    SVC_no_fragmentation_Stk
holdout_test_accuracy                    0.866667
holdout_test_f1                          0.736842
holdout_test_roc_auc                     0.949091
cv_test_accuracy_median                  0.849057
cv_test_f1_median                        0.666667
cv_test_roc_auc_median                   0.941392

Model saved in ../results/models_modelling3/SVC_no_fragmentation_Stk

# CatBoost

In [13]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                        0
target                                          splashing
model                    CatBoostClassifier_splashing_Stk
holdout_test_accuracy                            0.866667
holdout_test_f1                                  0.901961
holdout_test_roc_auc                             0.949846
cv_test_accuracy_median                           0.90566
cv_test_f1_median                                0.927536
cv_test_roc_auc_median                           0.958204

Model saved in ../results/models_modelling3/CatBoostClassifier_splashing_Stk

In [14]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                               0
target                                          no_fragmentation
model                    CatBoostClassifier_no_fragmentation_Stk
holdout_test_accuracy                                       0.92
holdout_test_f1                                             0.85
holdout_test_roc_auc                                    0.984545
cv_test_accuracy_median                                 0.924528
cv_test_f1_median                                       0.846154
cv_test_roc_auc_median                                  0.976068

Model saved in ../results/models_modelling3/CatBoostClassifier_no_fragmentation_Stk

# XGBoost

In [15]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                   0
target                                     splashing
model                    XGBClassifier_splashing_Stk
holdout_test_accuracy                       0.893333
holdout_test_f1                                 0.92
holdout_test_roc_auc                        0.933256
cv_test_accuracy_median                     0.849057
cv_test_f1_median                           0.885714
cv_test_roc_auc_median                      0.938854

Model saved in ../results/models_modelling3/XGBClassifier_splashing_Stk

In [16]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                          0
target                                     no_fragmentation
model                    XGBClassifier_no_fragmentation_Stk
holdout_test_accuracy                              0.933333
holdout_test_f1                                    0.871795
holdout_test_roc_auc                                   0.99
cv_test_accuracy_median                            0.924528
cv_test_f1_median                                  0.846154
cv_test_roc_auc_median                             0.964103

Model saved in ../results/models_modelling3/XGBClassifier_no_fragmentation_Stk