Test KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Logistic Regression

In [4]:
estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ),
    model_postfix='base',
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                    LogisticRegression_splashing_base
params                   {'estimator': LogisticRegression(), 'source_fe...
holdout_test_accuracy                                             0.813333
holdout_test_precision                                            0.803571
holdout_test_recall                                                 0.9375
holdout_test_f1                                                   0.865385
holdout_test_roc_auc                                              0.891204
holdout_train_accuracy                                            0.814815
holdout_train_precision                                           0.840796
holdout_train_recall                                              0.880208
holdout_train_f1                                                  0.860051
holdout_train_roc_auc                                             0.913269
cv_fit_time              [0.006107807159423828, 0.0034821033477783203, ...
cv_score_time            [0.00541996955871582, 0.004540920257568359, 0....
cv_test_accuracy         [0.8703703703703703, 0.7924528301886793, 0.849...
cv_train_accuracy        [0.8113207547169812, 0.8119122257053292, 0.811...
cv_test_precision        [0.8333333333333334, 0.8529411764705882, 0.861...
cv_train_precision       [0.8341013824884793, 0.8310502283105022, 0.834...
cv_test_recall           [1.0, 0.8285714285714286, 0.9117647058823529, ...
cv_train_recall          [0.8829268292682927, 0.8878048780487805, 0.883...
cv_test_f1               [0.9090909090909091, 0.8405797101449276, 0.885...
cv_train_f1              [0.8578199052132701, 0.8584905660377359, 0.858...
cv_test_roc_auc          [0.9578947368421054, 0.8571428571428572, 0.950...
cv_train_roc_auc         [0.8975825598963955, 0.9145485665382971, 0.901...

Model saved in ../results/models_modelling3/LogisticRegression_splashing_base

In [5]:
model = joblib.load(
    '../results/models_modelling3/LogisticRegression_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

# KNClassifier

In [6]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                  KNeighborsClassifier_splashing_base
params                   {'estimator': KNeighborsClassifier(), 'source_...
holdout_test_accuracy                                             0.813333
holdout_test_precision                                            0.826923
holdout_test_recall                                               0.895833
holdout_test_f1                                                       0.86
holdout_test_roc_auc                                              0.880787
holdout_train_accuracy                                            0.915825
holdout_train_precision                                           0.928205
holdout_train_recall                                              0.942708
holdout_train_f1                                                  0.935401
holdout_train_roc_auc                                             0.966195
cv_fit_time              [0.003818988800048828, 0.003165006637573242, 0...
cv_score_time            [0.008829116821289062, 0.005921125411987305, 0...
cv_test_accuracy         [0.8888888888888888, 0.8301886792452831, 0.867...
cv_train_accuracy        [0.8962264150943396, 0.896551724137931, 0.8808...
cv_test_precision        [0.8918918918918919, 0.8823529411764706, 0.909...
cv_train_precision       [0.9174757281553398, 0.9215686274509803, 0.915...
cv_test_recall           [0.9428571428571428, 0.8571428571428571, 0.882...
cv_train_recall          [0.9219512195121952, 0.9170731707317074, 0.898...
cv_test_f1               [0.9166666666666667, 0.8695652173913043, 0.895...
cv_train_f1              [0.9197080291970803, 0.9193154034229828, 0.906...
cv_test_roc_auc          [0.9624060150375939, 0.8849206349206349, 0.927...
cv_train_roc_auc         [0.9620332398014245, 0.9660034231921266, 0.962...

Model saved in ../results/models_modelling3/KNeighborsClassifier_splashing_base

In [7]:
model = joblib.load(
    '../results/models_modelling3/KNeighborsClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.4, 0.6],
       [0. , 1. ],
       [0. , 1. ],
       [1. , 0. ],
       [0. , 1. ]])

# SVC

In [8]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                                   SVC_splashing_base
params                   {'estimator': SVC(probability=True), 'source_f...
holdout_test_accuracy                                                 0.84
holdout_test_precision                                            0.821429
holdout_test_recall                                               0.958333
holdout_test_f1                                                   0.884615
holdout_test_roc_auc                                              0.895833
holdout_train_accuracy                                            0.885522
holdout_train_precision                                           0.903061
holdout_train_recall                                              0.921875
holdout_train_f1                                                  0.912371
holdout_train_roc_auc                                             0.949727
cv_fit_time              [0.009522199630737305, 0.007333993911743164, 0...
cv_score_time            [0.005955934524536133, 0.00539708137512207, 0....
cv_test_accuracy         [0.9074074074074074, 0.7547169811320755, 0.867...
cv_train_accuracy        [0.8710691823899371, 0.8746081504702194, 0.868...
cv_test_precision        [0.875, 0.84375, 0.9354838709677419, 0.9354838...
cv_train_precision       [0.8660714285714286, 0.9365079365079365, 0.936...
cv_test_recall           [1.0, 0.7714285714285715, 0.8529411764705882, ...
cv_train_recall          [0.9463414634146341, 0.8634146341463415, 0.854...
cv_test_f1               [0.9333333333333333, 0.8059701492537314, 0.892...
cv_train_f1              [0.9044289044289044, 0.898477157360406, 0.8934...
cv_test_roc_auc          [0.9699248120300752, 0.8333333333333334, 0.970...
cv_train_roc_auc         [0.9373839844593136, 0.9515618314077879, 0.939...

Model saved in ../results/models_modelling3/SVC_splashing_base

In [9]:
model = joblib.load(
    '../results/models_modelling3/SVC_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.22335218, 0.77664782],
       [0.03001266, 0.96998734],
       [0.10504737, 0.89495263],
       [0.91303777, 0.08696223],
       [0.03203911, 0.96796089]])

# CatBoost

In [10]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                    CatBoostClassifier_splashing_base
params                   {'estimator': <catboost.core.CatBoostClassifie...
holdout_test_accuracy                                                 0.88
holdout_test_precision                                            0.867925
holdout_test_recall                                               0.958333
holdout_test_f1                                                   0.910891
holdout_test_roc_auc                                              0.946759
holdout_train_accuracy                                            0.996633
holdout_train_precision                                           0.994819
holdout_train_recall                                                   1.0
holdout_train_f1                                                  0.997403
holdout_train_roc_auc                                             0.998884
cv_fit_time              [0.65146803855896, 0.5669980049133301, 0.56462...
cv_score_time            [0.006080150604248047, 0.005192756652832031, 0...
cv_test_accuracy         [0.9629629629629629, 0.8679245283018868, 0.905...
cv_train_accuracy        [0.9874213836477987, 0.9937304075235109, 0.990...
cv_test_precision        [0.9459459459459459, 0.9117647058823529, 0.914...
cv_train_precision       [0.9855072463768116, 0.9903381642512077, 0.990...
cv_test_recall           [1.0, 0.8857142857142857, 0.9411764705882353, ...
cv_train_recall          [0.9951219512195122, 1.0, 0.9951456310679612, ...
cv_test_f1               [0.9722222222222222, 0.8985507246376812, 0.927...
cv_train_f1              [0.9902912621359223, 0.9951456310679612, 0.992...
cv_test_roc_auc          [1.0, 0.9396825396825397, 0.9736842105263158, ...
cv_train_roc_auc         [0.9979063241959854, 0.9986307231493367, 0.998...

Model saved in ../results/models_modelling3/CatBoostClassifier_splashing_base

In [11]:
model = joblib.load(
    '../results/models_modelling3/CatBoostClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.04080068, 0.95919932],
       [0.11544159, 0.88455841],
       [0.03240344, 0.96759656],
       [0.96022457, 0.03977543],
       [0.09204319, 0.90795681]])

# XGBoost

In [12]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='base',)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

None

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                         XGBClassifier_splashing_base
params                   {'estimator': XGBClassifier(base_score=None, b...
holdout_test_accuracy                                             0.866667
holdout_test_precision                                            0.851852
holdout_test_recall                                               0.958333
holdout_test_f1                                                   0.901961
holdout_test_roc_auc                                              0.944059
holdout_train_accuracy                                            0.996633
holdout_train_precision                                           0.994819
holdout_train_recall                                                   1.0
holdout_train_f1                                                  0.997403
holdout_train_roc_auc                                             0.999975
cv_fit_time              [0.08306121826171875, 0.08234429359436035, 0.0...
cv_score_time            [0.0071909427642822266, 0.007078886032104492, ...
cv_test_accuracy         [0.9629629629629629, 0.8490566037735849, 0.905...
cv_train_accuracy        [0.9968553459119497, 1.0, 0.9968652037617555, ...
cv_test_precision        [0.9459459459459459, 0.8857142857142857, 0.939...
cv_train_precision       [0.9951456310679612, 1.0, 0.9951690821256038, ...
cv_test_recall           [1.0, 0.8857142857142857, 0.9117647058823529, ...
cv_train_recall                        [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
cv_test_f1               [0.9722222222222222, 0.8857142857142857, 0.925...
cv_train_f1              [0.9975669099756691, 1.0, 0.9975786924939467, ...
cv_test_roc_auc          [0.9984962406015038, 0.9333333333333333, 0.952...
cv_train_roc_auc         [0.9999784157133608, 1.0, 0.9999355614743535, ...

Model saved in ../results/models_modelling3/XGBClassifier_splashing_base

In [13]:
model = joblib.load(
    '../results/models_modelling3/XGBClassifier_splashing_base')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.00789207, 0.9921079 ],
       [0.03681272, 0.9631873 ],
       [0.00534171, 0.9946583 ],
       [0.9872422 , 0.01275775],
       [0.0543167 , 0.9456833 ]], dtype=float32)