Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!
No optimization was used.

# Import libraries

In [45]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [46]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [47]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [48]:
model_postfix='default'
add_smote=False

# Logit

Splashing. Without SMOTE

In [49]:
estimator = StatsModelsEstimator
target = 'splashing'
estimator_params = {
    'model_class': Logit,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.383331
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357214
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.376182
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357074
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.378432
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.353686
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.363656
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357568
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Apr 2025   Pseudo R-squ.:                  0.4496
Time:                        13:14:44   Log-Likelihood:                -106.20
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 8.251e-35
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
inclination                         3.4616      0.643      5.383      0.000       2.201       4.722
volume_fraction                     2.0703      0.950      2.179      0.029       0.208       3.933
sedimentation_Stk                   0.7069      0.303      2.334      0.020       0.113       1.301
particle_droplet_diameter_ratio     0.6921      0.201      3.446      0.001       0.298       1.086
relative_roughness                  0.3300      0.175      1.891      0.059      -0.012       0.672
K                                   3.6507      0.460      7.935      0.000       2.749       4.552
wettability                        -0.7044      0.223     -3.155      0.002      -1.142      -0.267
===================================================================================================

                                                        0
target                                          splashing
model                             Logit_splashing_default
holdout_test_f1_macro                            0.777184
holdout_test_accuracy_balanced                   0.770833
holdout_test_roc_auc                             0.874228
holdout_test_f1                                  0.848485
holdout_test_accuracy                                 0.8
cv_test_f1_macro_median                          0.817451
cv_test_accuracy_balanced_median                 0.821207
cv_test_roc_auc_median                           0.869969
cv_test_f1_median                                0.865672
cv_test_accuracy_median                          0.830189
cv_test_precision_class_0_median                     0.75
cv_test_recall_class_0_median                    0.789474
cv_test_f1_class_0_median                        0.769231

Model saved in ../results/models_modelling4/Logit_splashing_default

No fragmentation. without SMOTE

In [50]:
estimator = StatsModelsEstimator
target = 'no_fragmentation'
estimator_params = {
    'model_class': Logit,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimization terminated successfully.
         Current function value: 0.269884
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.250426
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.277629
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.260251
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.264926
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.254987
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.287571
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.272580
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Apr 2025   Pseudo R-squ.:                  0.5294
Time:                        13:14:44   Log-Likelihood:                -80.956
converged:                       True   LL-Null:                       -172.03
Covariance Type:            nonrobust   LLR p-value:                 1.185e-36
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
sedimentation_Stk                  -0.7220      0.330     -2.191      0.028      -1.368      -0.076
particle_droplet_diameter_ratio    -0.8317      0.258     -3.225      0.001      -1.337      -0.326
relative_roughness                 -0.4844      0.201     -2.408      0.016      -0.879      -0.090
K                                  -4.4566      0.634     -7.031      0.000      -5.699      -3.214
wettability                         1.8122      0.322      5.625      0.000       1.181       2.444
inclination                        -6.7218      1.123     -5.987      0.000      -8.922      -4.521
volume_fraction                   -21.4024      4.250     -5.036      0.000     -29.732     -13.073
===================================================================================================

                                                               0
target                                          no_fragmentation
model                             Logit_no_fragmentation_default
holdout_test_f1_macro                                   0.882524
holdout_test_accuracy_balanced                          0.888636
holdout_test_roc_auc                                    0.951818
holdout_test_f1                                         0.829268
holdout_test_accuracy                                   0.906667
cv_test_f1_macro_median                                 0.814035
cv_test_accuracy_balanced_median                        0.828755
cv_test_roc_auc_median                                  0.932234
cv_test_f1_median                                       0.733333
cv_test_accuracy_median                                 0.851852
cv_test_precision_class_0_median                        0.918919
cv_test_recall_class_0_median                           0.923077
cv_test_f1_class_0_median                               0.902439

Model saved in ../results/models_modelling4/Logit_no_fragmentation_default

FINDING: The metrics on the holdout sample worsened with the addition of SMOTE, both for splashing and for no_fragmentation. The CV metrics improved only for no_fragmentation, see `modelling_df4_dimless_smote_2_pure_smote.ipynb`.

# Logistic Regression

In [51]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    'fit_intercept': False,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                     0
target                                                       splashing
model                             LogisticRegression_splashing_default
holdout_test_f1_macro                                         0.777184
holdout_test_accuracy_balanced                                0.770833
holdout_test_roc_auc                                           0.87963
holdout_test_f1                                               0.848485
holdout_test_accuracy                                              0.8
cv_test_f1_macro_median                                       0.799242
cv_test_accuracy_balanced_median                              0.806502
cv_test_roc_auc_median                                        0.871517
cv_test_f1_median                                             0.848485
cv_test_accuracy_median                                       0.811321
cv_test_precision_class_0_median                              0.714286
cv_test_recall_class_0_median                                 0.789474
cv_test_f1_class_0_median                                         0.75

Model saved in ../results/models_modelling4/LogisticRegression_splashing_default

In [52]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    'fit_intercept': False,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                            0
target                                                       no_fragmentation
model                             LogisticRegression_no_fragmentation_default
holdout_test_f1_macro                                                0.798595
holdout_test_accuracy_balanced                                       0.834091
holdout_test_roc_auc                                                 0.946364
holdout_test_f1                                                      0.723404
holdout_test_accuracy                                                0.826667
cv_test_f1_macro_median                                              0.854396
cv_test_accuracy_balanced_median                                     0.882051
cv_test_roc_auc_median                                               0.945055
cv_test_f1_median                                                    0.787879
cv_test_accuracy_median                                              0.886792
cv_test_precision_class_0_median                                      0.96875
cv_test_recall_class_0_median                                        0.846154
cv_test_f1_class_0_median                                            0.916667

Model saved in ../results/models_modelling4/LogisticRegression_no_fragmentation_default

# KNClassifier

In [53]:
estimator = KNeighborsClassifier
target = 'splashing'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                       0
target                                                         splashing
model                             KNeighborsClassifier_splashing_default
holdout_test_f1_macro                                           0.836601
holdout_test_accuracy_balanced                                  0.828704
holdout_test_roc_auc                                            0.880787
holdout_test_f1                                                 0.888889
holdout_test_accuracy                                           0.853333
cv_test_f1_macro_median                                         0.821013
cv_test_accuracy_balanced_median                                0.832817
cv_test_roc_auc_median                                          0.923308
cv_test_f1_median                                               0.869565
cv_test_accuracy_median                                         0.830189
cv_test_precision_class_0_median                                0.764706
cv_test_recall_class_0_median                                   0.777778
cv_test_f1_class_0_median                                       0.780488

Model saved in ../results/models_modelling4/KNeighborsClassifier_splashing_default

In [54]:
estimator = KNeighborsClassifier
target = 'no_fragmentation'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                              0
target                                                         no_fragmentation
model                             KNeighborsClassifier_no_fragmentation_default
holdout_test_f1_macro                                                  0.844075
holdout_test_accuracy_balanced                                         0.838636
holdout_test_roc_auc                                                   0.947727
holdout_test_f1                                                        0.769231
holdout_test_accuracy                                                      0.88
cv_test_f1_macro_median                                                0.835007
cv_test_accuracy_balanced_median                                       0.828205
cv_test_roc_auc_median                                                 0.932234
cv_test_f1_median                                                      0.758621
cv_test_accuracy_median                                                 0.87037
cv_test_precision_class_0_median                                            0.9
cv_test_recall_class_0_median                                          0.923077
cv_test_f1_class_0_median                                              0.911392

Model saved in ../results/models_modelling4/KNeighborsClassifier_no_fragmentation_default

# SVC

In [55]:
estimator = SVC
target = 'splashing'
estimator_params = {
    'probability': True,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                      0
target                                        splashing
model                             SVC_splashing_default
holdout_test_f1_macro                          0.793956
holdout_test_accuracy_balanced                 0.789352
holdout_test_roc_auc                           0.911265
holdout_test_f1                                0.857143
holdout_test_accuracy                          0.813333
cv_test_f1_macro_median                        0.821013
cv_test_accuracy_balanced_median               0.832817
cv_test_roc_auc_median                         0.928793
cv_test_f1_median                              0.861538
cv_test_accuracy_median                        0.830189
cv_test_precision_class_0_median               0.727273
cv_test_recall_class_0_median                  0.789474
cv_test_f1_class_0_median                      0.780488

Model saved in ../results/models_modelling4/SVC_splashing_default

In [56]:
estimator = SVC
target = 'no_fragmentation'
estimator_params = {
    'probability': True,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                             0
target                                        no_fragmentation
model                             SVC_no_fragmentation_default
holdout_test_f1_macro                                 0.829545
holdout_test_accuracy_balanced                        0.829545
holdout_test_roc_auc                                  0.954545
holdout_test_f1                                           0.75
holdout_test_accuracy                                 0.866667
cv_test_f1_macro_median                               0.796154
cv_test_accuracy_balanced_median                      0.782967
cv_test_roc_auc_median                                0.943223
cv_test_f1_median                                     0.692308
cv_test_accuracy_median                               0.849057
cv_test_precision_class_0_median                      0.878049
cv_test_recall_class_0_median                         0.923077
cv_test_f1_class_0_median                                  0.9

Model saved in ../results/models_modelling4/SVC_no_fragmentation_default

# CatBoost

In [57]:
estimator = CatBoostClassifier
target = 'splashing'
estimator_params = {
    'verbose': False,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                     0
target                                                       splashing
model                             CatBoostClassifier_splashing_default
holdout_test_f1_macro                                         0.863609
holdout_test_accuracy_balanced                                0.849537
holdout_test_roc_auc                                           0.95679
holdout_test_f1                                               0.910891
holdout_test_accuracy                                             0.88
cv_test_f1_macro_median                                       0.876935
cv_test_accuracy_balanced_median                              0.876935
cv_test_roc_auc_median                                        0.955108
cv_test_f1_median                                             0.914286
cv_test_accuracy_median                                       0.886792
cv_test_precision_class_0_median                                 0.875
cv_test_recall_class_0_median                                 0.842105
cv_test_f1_class_0_median                                     0.842105

Model saved in ../results/models_modelling4/CatBoostClassifier_splashing_default

In [58]:
estimator = CatBoostClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': False,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                            0
target                                                       no_fragmentation
model                             CatBoostClassifier_no_fragmentation_default
holdout_test_f1_macro                                                0.897727
holdout_test_accuracy_balanced                                       0.897727
holdout_test_roc_auc                                                 0.987273
holdout_test_f1                                                          0.85
holdout_test_accuracy                                                    0.92
cv_test_f1_macro_median                                              0.898077
cv_test_accuracy_balanced_median                                     0.880037
cv_test_roc_auc_median                                                0.97265
cv_test_f1_median                                                    0.846154
cv_test_accuracy_median                                              0.924528
cv_test_precision_class_0_median                                     0.928571
cv_test_recall_class_0_median                                        0.974359
cv_test_f1_class_0_median                                                0.95

Model saved in ../results/models_modelling4/CatBoostClassifier_no_fragmentation_default

# XGBoost

In [59]:
estimator = XGBClassifier
target = 'splashing'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                0
target                                                  splashing
model                             XGBClassifier_splashing_default
holdout_test_f1_macro                                    0.863609
holdout_test_accuracy_balanced                           0.849537
holdout_test_roc_auc                                     0.940972
holdout_test_f1                                          0.910891
holdout_test_accuracy                                        0.88
cv_test_f1_macro_median                                   0.87381
cv_test_accuracy_balanced_median                         0.865325
cv_test_roc_auc_median                                   0.942724
cv_test_f1_median                                        0.911765
cv_test_accuracy_median                                  0.886792
cv_test_precision_class_0_median                         0.842105
cv_test_recall_class_0_median                            0.842105
cv_test_f1_class_0_median                                0.833333

Model saved in ../results/models_modelling4/XGBClassifier_splashing_default

In [60]:
estimator = XGBClassifier
target = 'no_fragmentation'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                                       0
target                                                  no_fragmentation
model                             XGBClassifier_no_fragmentation_default
holdout_test_f1_macro                                           0.946185
holdout_test_accuracy_balanced                                     0.925
holdout_test_roc_auc                                            0.991818
holdout_test_f1                                                 0.918919
holdout_test_accuracy                                               0.96
cv_test_f1_macro_median                                         0.875762
cv_test_accuracy_balanced_median                                0.867216
cv_test_roc_auc_median                                          0.979487
cv_test_f1_median                                               0.814815
cv_test_accuracy_median                                          0.90566
cv_test_precision_class_0_median                                   0.925
cv_test_recall_class_0_median                                   0.948718
cv_test_f1_class_0_median                                       0.936709

Model saved in ../results/models_modelling4/XGBClassifier_no_fragmentation_default

# AdaBoost

In [61]:
estimator = AdaBoostClassifier
target = 'splashing'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "AdaBoostClassifier"

                                                                     0
target                                                       splashing
model                             AdaBoostClassifier_splashing_default
holdout_test_f1_macro                                         0.793956
holdout_test_accuracy_balanced                                0.789352
holdout_test_roc_auc                                          0.881559
holdout_test_f1                                               0.857143
holdout_test_accuracy                                         0.813333
cv_test_f1_macro_median                                       0.817451
cv_test_accuracy_balanced_median                              0.821207
cv_test_roc_auc_median                                        0.900929
cv_test_f1_median                                             0.865672
cv_test_accuracy_median                                       0.830189
cv_test_precision_class_0_median                                  0.75
cv_test_recall_class_0_median                                 0.736842
cv_test_f1_class_0_median                                     0.769231

Model saved in ../results/models_modelling4/AdaBoostClassifier_splashing_default

In [62]:
estimator = AdaBoostClassifier
target = 'no_fragmentation'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "AdaBoostClassifier"

                                                                            0
target                                                       no_fragmentation
model                             AdaBoostClassifier_no_fragmentation_default
holdout_test_f1_macro                                                0.834656
holdout_test_accuracy_balanced                                       0.845455
holdout_test_roc_auc                                                 0.897273
holdout_test_f1                                                      0.761905
holdout_test_accuracy                                                0.866667
cv_test_f1_macro_median                                              0.826067
cv_test_accuracy_balanced_median                                     0.818681
cv_test_roc_auc_median                                               0.912088
cv_test_f1_median                                                    0.740741
cv_test_accuracy_median                                              0.867925
cv_test_precision_class_0_median                                     0.914286
cv_test_recall_class_0_median                                        0.923077
cv_test_f1_class_0_median                                            0.911392

Model saved in ../results/models_modelling4/AdaBoostClassifier_no_fragmentation_default

# Random Forest

In [63]:
estimator = RandomForestClassifier
target = 'splashing'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "RandomForestClassifier"

                                                                         0
target                                                           splashing
model                             RandomForestClassifier_splashing_default
holdout_test_f1_macro                                                 0.85
holdout_test_accuracy_balanced                                     0.83912
holdout_test_roc_auc                                              0.943673
holdout_test_f1                                                        0.9
holdout_test_accuracy                                             0.866667
cv_test_f1_macro_median                                           0.876935
cv_test_accuracy_balanced_median                                  0.887302
cv_test_roc_auc_median                                            0.945046
cv_test_f1_median                                                 0.911765
cv_test_accuracy_median                                           0.886792
cv_test_precision_class_0_median                                  0.866667
cv_test_recall_class_0_median                                     0.842105
cv_test_f1_class_0_median                                         0.842105

Model saved in ../results/models_modelling4/RandomForestClassifier_splashing_default

In [64]:
estimator = RandomForestClassifier
target = 'no_fragmentation'
estimator_params = {}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "RandomForestClassifier"

                                                                                0
target                                                           no_fragmentation
model                             RandomForestClassifier_no_fragmentation_default
holdout_test_f1_macro                                                    0.863636
holdout_test_accuracy_balanced                                           0.863636
holdout_test_roc_auc                                                         0.98
holdout_test_f1                                                               0.8
holdout_test_accuracy                                                    0.893333
cv_test_f1_macro_median                                                  0.869136
cv_test_accuracy_balanced_median                                         0.844322
cv_test_roc_auc_median                                                   0.952991
cv_test_f1_median                                                             0.8
cv_test_accuracy_median                                                   0.90566
cv_test_precision_class_0_median                                         0.904762
cv_test_recall_class_0_median                                            0.948718
cv_test_f1_class_0_median                                                0.936709

Model saved in ../results/models_modelling4/RandomForestClassifier_no_fragmentation_default

# LightGBM

In [65]:
estimator = LGBMClassifier
target = 'splashing'
estimator_params = {
    'verbose': -1,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LGBMClassifier"

                                                                 0
target                                                   splashing
model                             LGBMClassifier_splashing_default
holdout_test_f1_macro                                      0.86631
holdout_test_accuracy_balanced                            0.857639
holdout_test_roc_auc                                      0.951775
holdout_test_f1                                           0.909091
holdout_test_accuracy                                         0.88
cv_test_f1_macro_median                                    0.87381
cv_test_accuracy_balanced_median                          0.873839
cv_test_roc_auc_median                                     0.94582
cv_test_f1_median                                         0.914286
cv_test_accuracy_median                                   0.886792
cv_test_precision_class_0_median                              0.85
cv_test_recall_class_0_median                             0.894737
cv_test_f1_class_0_median                                 0.833333

Model saved in ../results/models_modelling4/LGBMClassifier_splashing_default

In [66]:
estimator = LGBMClassifier
target = 'no_fragmentation'
estimator_params = {
    'verbose': -1,
}

ml_pipe = MLPipeline(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    model_postfix=model_postfix,
    add_smote=add_smote,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LGBMClassifier"

                                                                        0
target                                                   no_fragmentation
model                             LGBMClassifier_no_fragmentation_default
holdout_test_f1_macro                                            0.916089
holdout_test_accuracy_balanced                                   0.922727
holdout_test_roc_auc                                             0.985455
holdout_test_f1                                                  0.878049
holdout_test_accuracy                                            0.933333
cv_test_f1_macro_median                                          0.898077
cv_test_accuracy_balanced_median                                  0.89011
cv_test_roc_auc_median                                           0.958974
cv_test_f1_median                                                0.846154
cv_test_accuracy_median                                          0.924528
cv_test_precision_class_0_median                                 0.945946
cv_test_recall_class_0_median                                    0.948718
cv_test_f1_class_0_median                                        0.948718

Model saved in ../results/models_modelling4/LGBMClassifier_no_fragmentation_default