Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!

Based on `research_14_SMOTE_influence_on_metrics.ipynb` it was decided to use SMOTE for all models, except Logit!

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier, RandomForestClassifier

from sklearn.metrics import (
    make_scorer,
    f1_score,
)

import optuna
from functools import partial

from pathlib import Path
import sys

from typing import Type
from sklearn.base import BaseEstimator

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling4_utils import (
    # _prepare_df,
    MLPipeline,
    StatsModelsEstimator,
    update_estimator_params,
    OptunaOptimizer,
    GridSearchOptimizer,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
model_postfix = 'opt-model'
add_smote = False
is_smotenc = False
smote_params = {
    # 'categorical_features': (
    #     'wettability',
    #     'inclination',
    # ),
}
scoring_metrics = {"f1_macro": make_scorer(f1_score, average="macro"),}
step_scoring_average = "mean"
n_trials = 5000 # 1000

save_model_and_metrics = False

## Optimization functions

In [5]:
def optimize_estimator_optuna(
    target:str,
    estimator:Type[BaseEstimator],
    estimator_params:dict,
    objective:callable,
    n_trials:int,
    step_scoring_average:str=step_scoring_average,
    params_to_process:list=None,
    model_postfix:str=model_postfix,
    add_smote:bool=add_smote,
    is_smotenc:bool=is_smotenc,
    smote_params:dict=smote_params,
    scoring_metrics:dict=scoring_metrics,
    save_model_and_metrics:bool=save_model_and_metrics,
):
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params=estimator_params,
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        scoring_metrics=scoring_metrics,
        step_scoring_average=step_scoring_average,
    )
    
    opt = OptunaOptimizer(
        objective=partial(objective, ml_pipe=ml_pipe),
        study_name="model_study",
        direction="maximize",
    )
    
    opt.optimize(n_trials=n_trials)
    
    best_params = opt.study.best_params
    
    if params_to_process:
        for param in params_to_process:
            # Find one key in best_params which contains param
            key = next((k for k in best_params.keys() if param in k), None)
            if key:
                best_params[param] = best_params.pop(key)

    print('best_params')
    display(best_params)
    
    ml_pipe = MLPipeline(
        target=target,
        estimator=estimator,
        estimator_params={**estimator_params, **best_params},
        model_postfix=model_postfix,
        add_smote=add_smote,
        is_smotenc=is_smotenc,
        smote_params=smote_params,
        step_scoring_average=step_scoring_average, # No need to pass, it would not be used
    )
    
    ml_pipe.run(
        save_model_and_metrics=save_model_and_metrics,
    )

# Logistic Regression

In [6]:
estimator = LogisticRegression
target = 'splashing'
estimator_params = {
    "fit_intercept": False,
}
params_to_process = ['penalty']

def logreg_objective(trial:optuna.trial.Trial, ml_pipe:MLPipeline):
    
    # # NOTE: Does not work, since optuna requires static parameters ranges
    # solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # penalty_options = {
    #     'lbfgs': ['l2'],
    #     'liblinear': ['l1', 'l2'],
    #     'newton-cg': ['l2'],
    #     'newton-cholesky': ['l2'],
    #     'sag': ['l2'],
    #     'saga': ['l1', 'l2', 'elasticnet'],
    # }
    # penalty = trial.suggest_categorical('penalty', penalty_options[solver])
    # NOTE: warnings + inconvenient to create best model
    # solver_penalty_combinations = [
    #     ("liblinear", "l1"),
    #     ("liblinear", "l2"),
    #     ("saga", "l1"),
    #     ("saga", "l2"),
    #     ("saga", "elasticnet"),
    #     ("lbfgs", "l2"),
    #     ("newton-cg", "l2"),
    #     ("newton-cholesky", "l2"),
    #     ("sag", "l2"),
    # ]
    # solver, penalty = trial.suggest_categorical(
    #     'solver_penalty', solver_penalty_combinations
    # )
    
    solver = trial.suggest_categorical('solver', ['lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'])
    # solver = trial.suggest_categorical('solver', ['lbfgs',])
    
    if solver == 'liblinear':
        penalty = trial.suggest_categorical('penalty_liblinear', ['l1', 'l2'])
    elif solver == 'saga':
        penalty = trial.suggest_categorical('penalty_saga', ['l1', 'l2', 'elasticnet'])
    else:
        penalty = trial.suggest_categorical('penalty_other', ['l2'])
    
    # If C is large, the penalty should be small
    C = trial.suggest_loguniform('C', 1e-4, 1e3) 
    
    l1_ratio = None
    if penalty == 'elasticnet':
        l1_ratio = trial.suggest_uniform('l1_ratio', 0., 1.)
    
    class_weight = trial.suggest_categorical(
        'class_weight', [None, 'balanced']
    )
    
    suggested_estimator_params = {
        "solver": solver,
        "penalty": penalty,
        "C": C,
        "l1_ratio": l1_ratio,
        "class_weight": class_weight,
    }
    
    
    estimator_params = update_estimator_params(
        ml_pipe,
        suggested_estimator_params
    )
    
    score = ml_pipe.step(
        estimator=ml_pipe._pipeline_params['estimator'],
        estimator_params=estimator_params,
    )
    
    return score

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

[I 2025-04-14 18:56:58,502] A new study created in memory with name: model_study
[I 2025-04-14 18:56:58,583] Trial 0 finished with value: 0.7985639090256361 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 18:56:58,644] Trial 1 finished with value: 0.7941608217143109 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 18:56:58,701] Trial 2 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 18:56:58,755] Trial 3 finished with value: 0.797286337918985 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.7985639090256361.
[I 2025-04-14 18:56:58,875] Trial 4 finished with value: 0.8051764214045931 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 4 with value: 0.8051764214045931.
[I 2025-04-14 18:56:58,933] Trial 5 finished with value: 0.7472954252138893 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 4 with value: 0.8051764214045931.
[I 2025-04-14 18:56:58,995] Trial 6 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,050] Trial 7 finished with value: 0.7611608284370048 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,107] Trial 8 finished with value: 0.8092959761471556 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,163] Trial 9 finished with value: 0.7440757557883121 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,229] Trial 10 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 612.0117715317909, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,294] Trial 11 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 812.2968586165572, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,357] Trial 12 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 44.18006281079643, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,422] Trial 13 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 53.997004500496224, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,486] Trial 14 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 82.8316016194943, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,551] Trial 15 finished with value: 0.8043578522466602 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 6.710520506428847, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,616] Trial 16 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 862.7281076174387, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,675] Trial 17 finished with value: 0.8011388801027161 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 9.634842407301047, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,735] Trial 18 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 154.28126375129878, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,798] Trial 19 finished with value: 0.7147720923839032 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.05277899450558773, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,858] Trial 20 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.0019806976015503477, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,926] Trial 21 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 793.8857365594376, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:56:59,995] Trial 22 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 219.31135888519634, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,063] Trial 23 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 25.510987556759318, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,129] Trial 24 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 258.3620661216836, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,197] Trial 25 finished with value: 0.8011388801027161 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 2.5427324308248602, 'l1_ratio': 0.03880691701978933, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,257] Trial 26 finished with value: 0.8108339592997184 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 670.8607617954096, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,323] Trial 27 finished with value: 0.8076324033935517 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 21.875400062405905, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,383] Trial 28 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 127.61786566762798, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,442] Trial 29 finished with value: 0.8054944185887905 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.657889434458531, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,502] Trial 30 finished with value: 0.8070196325242648 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.3693501869209362, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,566] Trial 31 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 24.60210090566989, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,630] Trial 32 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 55.444174075582346, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,694] Trial 33 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 991.2188844464986, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,757] Trial 34 finished with value: 0.8051764214045931 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 326.9005065843657, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,820] Trial 35 finished with value: 0.8011388801027161 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 3.356386770573319, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,877] Trial 36 finished with value: 0.8069855520521557 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.7671853381937119, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,936] Trial 37 finished with value: 0.7523053213470348 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.11784084260431638, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:00,998] Trial 38 finished with value: 0.8083849775543257 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 104.47008439705394, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,060] Trial 39 finished with value: 0.8108339592997184 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 332.20768073311547, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,118] Trial 40 finished with value: 0.8076324033935517 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 45.48108914098549, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,186] Trial 41 finished with value: 0.8076324033935517 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 46.29829692045701, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,250] Trial 42 finished with value: 0.8043578522466602 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 14.644895489802087, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,313] Trial 43 finished with value: 0.8011388801027161 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 6.437774317247896, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,378] Trial 44 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 80.80022488898723, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,455] Trial 45 finished with value: 0.8083849775543257 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 471.34177634275824, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,513] Trial 46 finished with value: 0.8108339592997184 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 175.51679075546247, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,578] Trial 47 finished with value: 0.8011388801027161 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 4.92508850455539, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,644] Trial 48 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 404.87118172795107, 'l1_ratio': 0.9991380019669489, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,699] Trial 49 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.0004062648427292201, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,760] Trial 50 finished with value: 0.8091931765214193 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.8916958583368253, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,826] Trial 51 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 59.64793340371888, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,894] Trial 52 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 112.68149098711169, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:01,959] Trial 53 finished with value: 0.8011388801027161 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 13.370634009504629, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,025] Trial 54 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 32.12497696807618, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,092] Trial 55 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 162.5069104968723, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,153] Trial 56 finished with value: 0.8108339592997184 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 507.3510292017766, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,214] Trial 57 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 229.33152375581943, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,278] Trial 58 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 689.5049782951927, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,343] Trial 59 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 80.4518637607886, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,404] Trial 60 finished with value: 0.5223274005133915 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.014011367612997363, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,471] Trial 61 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 808.6644643517914, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,537] Trial 62 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 370.23492839693796, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,604] Trial 63 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 210.34931360410306, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,669] Trial 64 finished with value: 0.8076324033935517 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 33.57513844628709, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,729] Trial 65 finished with value: 0.8108339592997184 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 18.334109719260034, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,798] Trial 66 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 137.34620752865303, 'l1_ratio': 0.0033924013751416293, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,861] Trial 67 finished with value: 0.8051764214045931 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 959.9246415033698, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,921] Trial 68 finished with value: 0.8011388801027161 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 9.774233773200372, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:02,986] Trial 69 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 73.59175291299202, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,048] Trial 70 finished with value: 0.8108339592997184 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 257.4373987817939, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,108] Trial 71 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 524.8433849668473, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,166] Trial 72 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 122.9028923390491, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,227] Trial 73 finished with value: 0.8076324033935517 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 36.90517950958393, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,286] Trial 74 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 276.8091278896913, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,353] Trial 75 finished with value: 0.8108339592997184 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 583.4733743054669, 'l1_ratio': 0.452108460208148, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,417] Trial 76 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 998.2581510490639, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,480] Trial 77 finished with value: 0.8051764214045931 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 77.75148205251834, 'class_weight': None}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,540] Trial 78 finished with value: 0.8108339592997184 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 151.27275233930945, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,598] Trial 79 finished with value: 0.8108339592997184 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 348.301406576052, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,657] Trial 80 finished with value: 0.7114314704208322 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.051457823934386984, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.
[I 2025-04-14 18:57:03,717] Trial 81 finished with value: 0.26121337827326935 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 0.003575350343980175, 'class_weight': 'balanced'}. Best is trial 6 with value: 0.8108339592997184.

best_params

{'solver': 'sag',
 'C': 0.5528280003981445,
 'class_weight': 'balanced',
 'penalty': 'l2'}

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                       0
target                                                         splashing
model                             LogisticRegression_splashing_opt-model
holdout_test_f1_macro                                           0.772036
holdout_test_accuracy_balanced                                   0.77662
holdout_test_roc_auc                                            0.886574
holdout_test_f1                                                 0.829787
holdout_test_accuracy                                           0.786667
cv_test_f1_macro_median                                         0.802827
cv_test_accuracy_balanced_median                                0.818111
cv_test_roc_auc_median                                          0.871517
cv_test_f1_median                                                0.84375
cv_test_accuracy_median                                         0.811321
cv_test_precision_class_0_median                                0.681818
cv_test_recall_class_0_median                                   0.894737
cv_test_f1_class_0_median                                       0.761905

In [7]:
estimator = LogisticRegression
target = 'no_fragmentation'
estimator_params = {
    "fit_intercept": False,
}
params_to_process = ['penalty']

optimize_estimator_optuna(
    target=target,
    estimator=estimator,
    estimator_params=estimator_params,
    params_to_process=params_to_process,
    objective=logreg_objective,
    n_trials=n_trials,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

[I 2025-04-14 19:36:35,323] A new study created in memory with name: model_study
[I 2025-04-14 19:36:35,369] Trial 0 finished with value: 0.8397856760138982 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.6136341713591311, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,415] Trial 1 finished with value: 0.8027588628638668 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.47129737561107793, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,456] Trial 2 finished with value: 0.4233049487844008 and parameters: {'solver': 'saga', 'penalty_saga': 'elasticnet', 'C': 0.00021142332035497166, 'l1_ratio': 0.6075448519014384, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,498] Trial 3 finished with value: 0.7911634439518859 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 0.292575779498244, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,539] Trial 4 finished with value: 0.8041450241851706 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l1', 'C': 377.1313111077982, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,583] Trial 5 finished with value: 0.7101944867137514 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00793310536373302, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2025-04-14 19:36:35,638] Trial 6 finished with value: 0.7975711524350583 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 51.07754312955822, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,680] Trial 7 finished with value: 0.7162615239628565 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.020715058970816186, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,723] Trial 8 finished with value: 0.8389828678891506 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 9.833622008382896, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,765] Trial 9 finished with value: 0.7027598982205824 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.00016596033385442345, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,815] Trial 10 finished with value: 0.7927422008145589 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.8666692466256958, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,860] Trial 11 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 10.143487196996828, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,905] Trial 12 finished with value: 0.812515742911062 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.6327525396615056, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,950] Trial 13 finished with value: 0.8041450241851706 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 810.5159286019858, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:35,993] Trial 14 finished with value: 0.8217069937807342 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 41.088344411941925, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:36,039] Trial 15 finished with value: 0.7553687870563394 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 0.0372597498604139, 'class_weight': None}. Best is trial 0 with value: 0.8397856760138982.
[I 2025-04-14 19:36:36,091] Trial 16 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.724106746978989, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 19:36:36,144] Trial 17 finished with value: 0.8397856760138982 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.095084119182575, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 19:36:36,196] Trial 18 finished with value: 0.751333847002101 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.08756325508970042, 'class_weight': 'balanced'}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 19:36:36,253] Trial 19 finished with value: 0.7058880066067941 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 0.0024162747940151587, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 19:36:36,306] Trial 20 finished with value: 0.8053486507069412 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 129.7722129415162, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 19:36:36,357] Trial 21 finished with value: 0.8397856760138982 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.2132003115413115, 'class_weight': None}. Best is trial 16 with value: 0.8419263095815431.
[I 2025-04-14 19:36:36,406] Trial 22 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.8783531560274382, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,455] Trial 23 finished with value: 0.8373759056160653 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 15.303575401434081, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,503] Trial 24 finished with value: 0.7861038159067716 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.23387991022843746, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,545] Trial 25 finished with value: 0.823203012055543 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.1344494087951653, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,595] Trial 26 finished with value: 0.7957150504518486 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 5.295881990201866, 'class_weight': 'balanced'}. Best is trial 22 with value: 0.8434131344007432.
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2025-04-14 19:36:36,647] Trial 27 finished with value: 0.8217069937807342 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 60.76935561647131, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,691] Trial 28 finished with value: 0.764321884872908 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.12927445165859106, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,737] Trial 29 finished with value: 0.8060768869882171 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 0.5144042098751197, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,780] Trial 30 finished with value: 0.8397856760138982 and parameters: {'solver': 'liblinear', 'penalty_liblinear': 'l2', 'C': 1.5561018720408164, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,829] Trial 31 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.8712800590967085, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,879] Trial 32 finished with value: 0.8264230783613948 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 25.316725538800213, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,929] Trial 33 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.7221260582895894, 'class_weight': None}. Best is trial 22 with value: 0.8434131344007432.
[I 2025-04-14 19:36:36,979] Trial 34 finished with value: 0.8450545594789775 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 5.435591249239913, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,030] Trial 35 finished with value: 0.8053486507069412 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 136.63824111037857, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,078] Trial 36 finished with value: 0.823203012055543 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.816964373947913, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,130] Trial 37 finished with value: 0.7957150504518486 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 6.659970275930177, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,176] Trial 38 finished with value: 0.7794397535150646 and parameters: {'solver': 'saga', 'penalty_saga': 'l2', 'C': 0.2153110037721488, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,225] Trial 39 finished with value: 0.8264230783613948 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 24.35599927753569, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,278] Trial 40 finished with value: 0.8009378735983896 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 129.41869004589753, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,327] Trial 41 finished with value: 0.8419263095815431 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.7122157144133734, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,376] Trial 42 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.157250346127057, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,425] Trial 43 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 12.097509864736578, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,473] Trial 44 finished with value: 0.832833811324452 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 1.3542365384722908, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,521] Trial 45 finished with value: 0.8027588628638668 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.4966907276767269, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2025-04-14 19:36:37,573] Trial 46 finished with value: 0.8360731605957052 and parameters: {'solver': 'sag', 'penalty_other': 'l2', 'C': 6.752958044247071, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/Users/vulf/.pyenv/versions/3.11.8/envs/drop-impact-env/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
[I 2025-04-14 19:36:37,627] Trial 47 finished with value: 0.8341241108270036 and parameters: {'solver': 'saga', 'penalty_saga': 'l1', 'C': 2.193740731166382, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,677] Trial 48 finished with value: 0.7975711524350583 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 21.194244633210136, 'class_weight': 'balanced'}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,722] Trial 49 finished with value: 0.7027598982205824 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.0005639111644513537, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,766] Trial 50 finished with value: 0.7567771390686735 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 0.08059991173771112, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,815] Trial 51 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.2811507683257304, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,863] Trial 52 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 3.327120493705326, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,913] Trial 53 finished with value: 0.8341241108270036 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 10.564040915095697, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:37,962] Trial 54 finished with value: 0.823203012055543 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 1.0126144081915616, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:38,009] Trial 55 finished with value: 0.8129853203141331 and parameters: {'solver': 'lbfgs', 'penalty_other': 'l2', 'C': 46.83818698981929, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:38,059] Trial 56 finished with value: 0.8434131344007432 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 2.597273588251652, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:38,107] Trial 57 finished with value: 0.7993857581360823 and parameters: {'solver': 'newton-cg', 'penalty_other': 'l2', 'C': 0.36753899263985235, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.
[I 2025-04-14 19:36:38,151] Trial 58 finished with value: 0.8406750578217989 and parameters: {'solver': 'newton-cholesky', 'penalty_other': 'l2', 'C': 6.360169940577772, 'class_weight': None}. Best is trial 34 with value: 0.8450545594789775.

best_params

{'solver': 'lbfgs',
 'C': 3.62369856229918,
 'class_weight': None,
 'penalty': 'l2'}

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                              0
target                                                         no_fragmentation
model                             LogisticRegression_no_fragmentation_opt-model
holdout_test_f1_macro                                                  0.798595
holdout_test_accuracy_balanced                                         0.834091
holdout_test_roc_auc                                                   0.943636
holdout_test_f1                                                        0.723404
holdout_test_accuracy                                                  0.826667
cv_test_f1_macro_median                                                0.865709
cv_test_accuracy_balanced_median                                       0.882051
cv_test_roc_auc_median                                                 0.938462
cv_test_f1_median                                                        0.8125
cv_test_accuracy_median                                                0.886792
cv_test_precision_class_0_median                                       0.969697
cv_test_recall_class_0_median                                          0.871795
cv_test_f1_class_0_median                                              0.918919