Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!
No optimization was used.

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
features_to_drop = (
    'sign_particle_droplet_diameter_ratio',
    'sign_sedimentation_Stk',
    'Re', 
    'We', 
    'init_volume_fraction',
    # 'particle_droplet_diameter_ratio',
    'sedimentation_Re',
    'particle_liquid_density_ratio',
    # 'sedimentation_Stk',
    'sign_sedimentation_Re',
    # 'volume_fraction', 
    # 'relative_roughness', 
    # 'inclination',
    # 'wettability',
    # 'K',
)
log_features=(
    'relative_roughness',
    'sedimentation_Stk',
    'particle_droplet_diameter_ratio',
)
minmax_features_splash=(
    # 'relative_roughness',
    'inclination',
    'volume_fraction',
)
passthrough_features_splash=(
    'wettability',
)
minmax_features_no_fragm=(
    # 'relative_roughness',
)
passthrough_features_no_fragm=(
    'wettability',
    'inclination',
    'volume_fraction',
)
add_const=False
model_postfix='Stk_diam'

# Logit

In [5]:
estimator = StatsModelsEstimator(Logit)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.383331
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357214
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.376182
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357074
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.378432
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.353686
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.363656
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357568
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Mon, 14 Oct 2024   Pseudo R-squ.:                  0.4496
Time:                        14:39:14   Log-Likelihood:                -106.20
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 8.251e-35
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
inclination                         3.4616      0.643      5.383      0.000       2.201       4.722
volume_fraction                     2.0703      0.950      2.179      0.029       0.208       3.933
sedimentation_Stk                   0.7069      0.303      2.334      0.020       0.113       1.301
particle_droplet_diameter_ratio     0.6921      0.201      3.446      0.001       0.298       1.086
relative_roughness                  0.3300      0.175      1.891      0.059      -0.012       0.672
K                                   3.6507      0.460      7.935      0.000       2.749       4.552
wettability                        -0.7044      0.223     -3.155      0.002      -1.142      -0.267
===================================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_Stk_diam
holdout_test_accuracy                         0.8
holdout_test_f1                          0.848485
holdout_test_roc_auc                     0.874228
cv_test_accuracy_median                  0.830189
cv_test_f1_median                        0.865672
cv_test_roc_auc_median                   0.869969

Model saved in ../results/models_modelling3/Logit_splashing_Stk_diam

In [6]:
estimator = StatsModelsEstimator(Logit)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimization terminated successfully.
         Current function value: 0.269884
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.250426
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.277629
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.260251
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.264926
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.254987
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.287571
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.272580
         Iterations 9
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Mon, 14 Oct 2024   Pseudo R-squ.:                  0.5294
Time:                        14:39:14   Log-Likelihood:                -80.956
converged:                       True   LL-Null:                       -172.03
Covariance Type:            nonrobust   LLR p-value:                 1.185e-36
===================================================================================================
                                      coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------------------
sedimentation_Stk                  -0.7220      0.330     -2.191      0.028      -1.368      -0.076
particle_droplet_diameter_ratio    -0.8317      0.258     -3.225      0.001      -1.337      -0.326
relative_roughness                 -0.4844      0.201     -2.408      0.016      -0.879      -0.090
K                                  -4.4566      0.634     -7.031      0.000      -5.699      -3.214
wettability                         1.8122      0.322      5.625      0.000       1.181       2.444
inclination                        -6.7218      1.123     -5.987      0.000      -8.922      -4.521
volume_fraction                   -21.4024      4.250     -5.036      0.000     -29.732     -13.073
===================================================================================================

                                                       0
target                                  no_fragmentation
model                    Logit_no_fragmentation_Stk_diam
holdout_test_accuracy                           0.906667
holdout_test_f1                                 0.829268
holdout_test_roc_auc                            0.951818
cv_test_accuracy_median                         0.851852
cv_test_f1_median                               0.733333
cv_test_roc_auc_median                          0.932234

Model saved in ../results/models_modelling3/Logit_no_fragmentation_Stk_diam

# Logistic Regression

In [7]:
estimator = LogisticRegression(
    fit_intercept=False,
)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                             0
target                                               splashing
model                    LogisticRegression_splashing_Stk_diam
holdout_test_accuracy                                      0.8
holdout_test_f1                                       0.848485
holdout_test_roc_auc                                   0.87963
cv_test_accuracy_median                               0.811321
cv_test_f1_median                                     0.848485
cv_test_roc_auc_median                                0.871517

Model saved in ../results/models_modelling3/LogisticRegression_splashing_Stk_diam

In [8]:
estimator = LogisticRegression(
    fit_intercept=False,
)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                    0
target                                               no_fragmentation
model                    LogisticRegression_no_fragmentation_Stk_diam
holdout_test_accuracy                                        0.826667
holdout_test_f1                                              0.723404
holdout_test_roc_auc                                         0.946364
cv_test_accuracy_median                                      0.886792
cv_test_f1_median                                            0.787879
cv_test_roc_auc_median                                       0.945055

Model saved in ../results/models_modelling3/LogisticRegression_no_fragmentation_Stk_diam

# KNClassifier

In [9]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                               0
target                                                 splashing
model                    KNeighborsClassifier_splashing_Stk_diam
holdout_test_accuracy                                   0.853333
holdout_test_f1                                         0.888889
holdout_test_roc_auc                                    0.880787
cv_test_accuracy_median                                 0.830189
cv_test_f1_median                                       0.869565
cv_test_roc_auc_median                                  0.923308

Model saved in ../results/models_modelling3/KNeighborsClassifier_splashing_Stk_diam

In [10]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                      0
target                                                 no_fragmentation
model                    KNeighborsClassifier_no_fragmentation_Stk_diam
holdout_test_accuracy                                              0.88
holdout_test_f1                                                0.769231
holdout_test_roc_auc                                           0.947727
cv_test_accuracy_median                                         0.87037
cv_test_f1_median                                              0.758621
cv_test_roc_auc_median                                         0.932234

Model saved in ../results/models_modelling3/KNeighborsClassifier_no_fragmentation_Stk_diam

# SVC

In [11]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                              0
target                                splashing
model                    SVC_splashing_Stk_diam
holdout_test_accuracy                  0.813333
holdout_test_f1                        0.857143
holdout_test_roc_auc                   0.911265
cv_test_accuracy_median                0.830189
cv_test_f1_median                      0.861538
cv_test_roc_auc_median                 0.928793

Model saved in ../results/models_modelling3/SVC_splashing_Stk_diam

In [12]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                     0
target                                no_fragmentation
model                    SVC_no_fragmentation_Stk_diam
holdout_test_accuracy                         0.866667
holdout_test_f1                                   0.75
holdout_test_roc_auc                          0.954545
cv_test_accuracy_median                       0.849057
cv_test_f1_median                             0.692308
cv_test_roc_auc_median                        0.943223

Model saved in ../results/models_modelling3/SVC_no_fragmentation_Stk_diam

# CatBoost

In [13]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                             0
target                                               splashing
model                    CatBoostClassifier_splashing_Stk_diam
holdout_test_accuracy                                     0.88
holdout_test_f1                                       0.910891
holdout_test_roc_auc                                  0.955247
cv_test_accuracy_median                                0.90566
cv_test_f1_median                                     0.927536
cv_test_roc_auc_median                                 0.95356

Model saved in ../results/models_modelling3/CatBoostClassifier_splashing_Stk_diam

In [14]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                    0
target                                               no_fragmentation
model                    CatBoostClassifier_no_fragmentation_Stk_diam
holdout_test_accuracy                                            0.92
holdout_test_f1                                                  0.85
holdout_test_roc_auc                                         0.986364
cv_test_accuracy_median                                      0.924528
cv_test_f1_median                                            0.846154
cv_test_roc_auc_median                                       0.979487

Model saved in ../results/models_modelling3/CatBoostClassifier_no_fragmentation_Stk_diam

# XGBoost

In [15]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                        0
target                                          splashing
model                    XGBClassifier_splashing_Stk_diam
holdout_test_accuracy                                0.88
holdout_test_f1                                  0.910891
holdout_test_roc_auc                             0.940972
cv_test_accuracy_median                          0.886792
cv_test_f1_median                                0.911765
cv_test_roc_auc_median                           0.942724

Model saved in ../results/models_modelling3/XGBClassifier_splashing_Stk_diam

In [16]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                               0
target                                          no_fragmentation
model                    XGBClassifier_no_fragmentation_Stk_diam
holdout_test_accuracy                                       0.96
holdout_test_f1                                         0.918919
holdout_test_roc_auc                                    0.991818
cv_test_accuracy_median                                  0.90566
cv_test_f1_median                                       0.814815
cv_test_roc_auc_median                                  0.979487

Model saved in ../results/models_modelling3/XGBClassifier_no_fragmentation_Stk_diam