Test KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [3]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [14]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Logistic Regression

In [3]:
estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ),
    model_postfix='test',
)

ml_pipe.run()

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                    LogisticRegression_splashing_test
params                   {'estimator': LogisticRegression(), 'source_fe...
holdout_test_accuracy                                             0.813333
holdout_test_precision                                            0.803571
holdout_test_recall                                                 0.9375
holdout_test_f1                                                   0.865385
holdout_test_roc_auc                                              0.891204
holdout_train_accuracy                                            0.814815
holdout_train_precision                                           0.840796
holdout_train_recall                                              0.880208
holdout_train_f1                                                  0.860051
holdout_train_roc_auc                                             0.913269
cv_fit_time              [0.018549442291259766, 0.0, 0.0102829933166503...
cv_score_time            [0.004538774490356445, 0.013784646987915039, 0...
cv_test_accuracy         [0.84, 0.8133333333333334, 0.7837837837837838,...
cv_train_accuracy        [0.8080808080808081, 0.8181818181818182, 0.815...
cv_test_precision        [0.8461538461538461, 0.8269230769230769, 0.863...
cv_train_precision       [0.8292682926829268, 0.8415841584158416, 0.830...
cv_test_recall           [0.9166666666666666, 0.8958333333333334, 0.791...
cv_train_recall          [0.8854166666666666, 0.8854166666666666, 0.895...
cv_test_f1               [0.8799999999999999, 0.86, 0.8260869565217391,...
cv_train_f1              [0.8564231738035264, 0.8629441624365483, 0.862...
cv_test_roc_auc          [0.9436728395061728, 0.8935185185185186, 0.889...
cv_train_roc_auc         [0.8981150793650794, 0.9085565476190476, 0.909...

Model saved in ..\results\models_modelling3\LogisticRegression_splashing_test

In [6]:
model = joblib.load(
    '../results/models_modelling3/LogisticRegression_splashing_test')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

# KNClassifier

In [7]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='test',)

ml_pipe.run()

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                  KNeighborsClassifier_splashing_test
params                   {'estimator': KNeighborsClassifier(), 'source_...
holdout_test_accuracy                                             0.813333
holdout_test_precision                                            0.826923
holdout_test_recall                                               0.895833
holdout_test_f1                                                       0.86
holdout_test_roc_auc                                              0.880787
holdout_train_accuracy                                            0.915825
holdout_train_precision                                           0.928205
holdout_train_recall                                              0.942708
holdout_train_f1                                                  0.935401
holdout_train_roc_auc                                             0.966195
cv_fit_time              [0.013483047485351562, 0.008872747421264648, 0...
cv_score_time            [0.0032334327697753906, 0.008018970489501953, ...
cv_test_accuracy         [0.9333333333333333, 0.7733333333333333, 0.810...
cv_train_accuracy        [0.898989898989899, 0.8888888888888888, 0.8892...
cv_test_precision        [0.9387755102040817, 0.8444444444444444, 0.854...
cv_train_precision       [0.9263157894736842, 0.9206349206349206, 0.903...
cv_test_recall           [0.9583333333333334, 0.7916666666666666, 0.854...
cv_train_recall          [0.9166666666666666, 0.90625, 0.92708333333333...
cv_test_f1               [0.9484536082474228, 0.8172043010752689, 0.854...
cv_train_f1              [0.9214659685863874, 0.9133858267716536, 0.915...
cv_test_roc_auc          [0.970679012345679, 0.8873456790123456, 0.9234...
cv_train_roc_auc         [0.9578869047619047, 0.9656250000000001, 0.963...

Model saved in ..\results\models_modelling3\KNeighborsClassifier_splashing_test

In [8]:
model = joblib.load(
    '../results/models_modelling3/KNeighborsClassifier_splashing_test')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

# SVC

In [10]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='test',)

ml_pipe.run()

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                                   SVC_splashing_test
params                   {'estimator': SVC(probability=True), 'source_f...
holdout_test_accuracy                                                 0.84
holdout_test_precision                                            0.821429
holdout_test_recall                                               0.958333
holdout_test_f1                                                   0.884615
holdout_test_roc_auc                                              0.895833
holdout_train_accuracy                                            0.885522
holdout_train_precision                                           0.903061
holdout_train_recall                                              0.921875
holdout_train_f1                                                  0.912371
holdout_train_roc_auc                                             0.949727
cv_fit_time              [0.02239513397216797, 0.014011144638061523, 0....
cv_score_time            [0.014072656631469727, 0.008000850677490234, 0...
cv_test_accuracy         [0.88, 0.7733333333333333, 0.8513513513513513,...
cv_train_accuracy        [0.8754208754208754, 0.8821548821548821, 0.879...
cv_test_precision        [0.8545454545454545, 0.8297872340425532, 0.930...
cv_train_precision       [0.8743961352657005, 0.943502824858757, 0.9333...
cv_test_recall           [0.9791666666666666, 0.8125, 0.833333333333333...
cv_train_recall          [0.9427083333333334, 0.8697916666666666, 0.875...
cv_test_f1               [0.912621359223301, 0.8210526315789474, 0.8791...
cv_train_f1              [0.9072681704260651, 0.9051490514905148, 0.903...
cv_test_roc_auc          [0.9606481481481481, 0.8966049382716049, 0.935...
cv_train_roc_auc         [0.9385416666666667, 0.9472966269841271, 0.946...

Model saved in ..\results\models_modelling3\SVC_splashing_test

In [11]:
model = joblib.load(
    '../results/models_modelling3/SVC_splashing_test')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

# CatBoost

In [15]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='test',)

ml_pipe.run()

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                    CatBoostClassifier_splashing_test
params                   {'estimator': <catboost.core.CatBoostClassifie...
holdout_test_accuracy                                                 0.88
holdout_test_precision                                            0.867925
holdout_test_recall                                               0.958333
holdout_test_f1                                                   0.910891
holdout_test_roc_auc                                              0.948302
holdout_train_accuracy                                            0.996633
holdout_train_precision                                           0.994819
holdout_train_recall                                                   1.0
holdout_train_f1                                                  0.997403
holdout_train_roc_auc                                             0.998834
cv_fit_time              [1.5839686393737793, 1.4876301288604736, 1.538...
cv_score_time            [0.01909041404724121, 0.01392221450805664, 0.0...
cv_test_accuracy         [0.9333333333333333, 0.8933333333333333, 0.864...
cv_train_accuracy        [0.98989898989899, 0.98989898989899, 0.9932885...
cv_test_precision        [0.9387755102040817, 0.8846153846153846, 0.931...
cv_train_precision       [0.9896373056994818, 0.9896373056994818, 0.994...
cv_test_recall           [0.9583333333333334, 0.9583333333333334, 0.854...
cv_train_recall          [0.9947916666666666, 0.9947916666666666, 0.994...
cv_test_f1               [0.9484536082474228, 0.9199999999999999, 0.891...
cv_train_f1              [0.9922077922077923, 0.9922077922077923, 0.994...
cv_test_roc_auc          [0.9814814814814814, 0.9722222222222222, 0.945...
cv_train_roc_auc         [0.9982638888888888, 0.9980406746031746, 0.998...

Model saved in ..\results\models_modelling3\CatBoostClassifier_splashing_test

In [16]:
model = joblib.load(
    '../results/models_modelling3/CatBoostClassifier_splashing_test')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.05959526, 0.94040474],
       [0.06389382, 0.93610618],
       [0.04239738, 0.95760262],
       [0.89485934, 0.10514066],
       [0.00426144, 0.99573856]])

# XGBoost

In [4]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio', 
        'sedimentation_Re',
        # 'particle_liquid_density_ratio',
        'sedimentation_Stk'
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
    ), model_postfix='test',)

ml_pipe.run()

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                                         0
dataset                                                         df_dimless
target                                                           splashing
model                                         XGBClassifier_splashing_test
params                   {'estimator': XGBClassifier(base_score=None, b...
holdout_test_accuracy                                                 0.88
holdout_test_precision                                            0.867925
holdout_test_recall                                               0.958333
holdout_test_f1                                                   0.910891
holdout_test_roc_auc                                              0.951389
holdout_train_accuracy                                            0.996633
holdout_train_precision                                           0.994819
holdout_train_recall                                                   1.0
holdout_train_f1                                                  0.997403
holdout_train_roc_auc                                             0.999975
cv_fit_time              [0.09089159965515137, 0.059160709381103516, 0....
cv_score_time            [0.016202449798583984, 0.007999658584594727, 0...
cv_test_accuracy         [0.9466666666666667, 0.8933333333333333, 0.837...
cv_train_accuracy        [1.0, 0.9966329966329966, 0.9966442953020134, ...
cv_test_precision        [0.94, 0.9, 0.9090909090909091, 0.957446808510...
cv_train_precision       [1.0, 0.9948186528497409, 0.9948186528497409, ...
cv_test_recall           [0.9791666666666666, 0.9375, 0.833333333333333...
cv_train_recall                                  [1.0, 1.0, 1.0, 1.0, 1.0]
cv_test_f1               [0.9591836734693877, 0.9183673469387755, 0.869...
cv_train_f1              [1.0, 0.9974025974025974, 0.9974025974025974, ...
cv_test_roc_auc          [0.9822530864197532, 0.9737654320987654, 0.917...
cv_train_roc_auc         [1.0, 0.9999751984126984, 0.9999754323899371, ...

Model saved in ..\results\models_modelling3\XGBClassifier_splashing_test

In [5]:
model = joblib.load(
    '../results/models_modelling3/XGBClassifier_splashing_test')
model.predict_proba(
    ml_pipe.get_X_y(ml_pipe.test)[0])[:5]

array([[0.00264955, 0.99735045],
       [0.05747163, 0.94252837],
       [0.00106913, 0.9989309 ],
       [0.9433746 , 0.05662544],
       [0.06219703, 0.937803  ]], dtype=float32)