Comparison with baseline decision stump $K < K_L$

$K_L = (649 + \frac{3.76}{\text{relative\_roughness}^{0.63}} ^ {5/8})$

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [6]:
import pandas as pd

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from modelling3_utils import (
    MLPipeline,
    DecisionStumpEstimator
)

# Baseline comparison

In [8]:
estimator = DecisionStumpEstimator(less_sign=False)
ml_pipe_ds = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=('init_volume_fraction', 'volume_fraction', 'sedimentation_Re',
       'sign_sedimentation_Re', 'sign_sedimentation_Stk', 'sedimentation_Stk',
       'particle_liquid_density_ratio', 'particle_droplet_diameter_ratio',
       'sign_particle_droplet_diameter_ratio', 'wettability', 'inclination', 'Re', 'We'),
    passthrough_features=('K', 'relative_roughness'),
    log_features=(),
    model_postfix='greater_or_equal_kl')

ml_pipe_ds.run(
    save_model_and_metrics=True)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

()

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(), ()),
                                ('passthrough', 'passthrough',
                                 ('K', 'relative_roughness'))])

no summary in estimator class "DecisionStumpEstimator"

                                                                            0
target                                                              splashing
model                             DecisionStump_splashing_greater_or_equal_kl
holdout_test_accuracy                                                0.773333
holdout_test_f1                                                      0.808989
holdout_test_roc_auc                                                 0.782407
cv_test_accuracy_median                                              0.773585
cv_test_f1_median                                                         0.8
cv_test_roc_auc_median                                               0.797214
cv_test_f1_macro_median                                              0.769565
cv_test_accuracy_balanced_median                                     0.797214
cv_test_precision_class_0_median                                      0.62963
cv_test_recall_class_0_median                                        0.894737
cv_test_f1_class_0_median                                            0.734694

Model saved in ..\results\models_modelling3\DecisionStump_splashing_greater_or_equal_kl

In [9]:
estimator = DecisionStumpEstimator(less_sign=True)
ml_pipe_ds = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=('init_volume_fraction', 'volume_fraction', 'sedimentation_Re',
       'sign_sedimentation_Re', 'sign_sedimentation_Stk', 'sedimentation_Stk',
       'particle_liquid_density_ratio', 'particle_droplet_diameter_ratio',
       'sign_particle_droplet_diameter_ratio', 'wettability', 'inclination', 'Re', 'We',),
    passthrough_features=('K', 'relative_roughness'),
    log_features=(),
    model_postfix='less_kl')

ml_pipe_ds.run(
    save_model_and_metrics=True)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'splashing', 'no_fragmentation'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

()

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(), ()),
                                ('passthrough', 'passthrough',
                                 ('K', 'relative_roughness'))])

no summary in estimator class "DecisionStumpEstimator"

                                                                       0
target                                                  no_fragmentation
model                             DecisionStump_no_fragmentation_less_kl
holdout_test_accuracy                                           0.733333
holdout_test_f1                                                 0.642857
holdout_test_roc_auc                                            0.786364
cv_test_accuracy_median                                         0.759259
cv_test_f1_median                                               0.647059
cv_test_roc_auc_median                                          0.771795
cv_test_f1_macro_median                                         0.732775
cv_test_accuracy_balanced_median                                0.771795
cv_test_precision_class_0_median                                0.939394
cv_test_recall_class_0_median                                   0.717949
cv_test_f1_class_0_median                                       0.816901

Model saved in ..\results\models_modelling3\DecisionStump_no_fragmentation_less_kl