Save base Logit, KNN, SVC, LogisticRegression, CatBoost, XGboost with pipeline. Sedimentation_Stk feature was used!
No optimization was used.

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit
from statsmodels.api import Logit # type: ignore
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from catboost import CatBoostClassifier
from xgboost import XGBClassifier

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [3]:
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

# Settings

In [4]:
features_to_drop = (
    # 'sign_particle_droplet_diameter_ratio',
    'sign_sedimentation_Stk',
    'Re', 
    'We', 
    'init_volume_fraction',
    'particle_droplet_diameter_ratio',
    'sedimentation_Re',
    'particle_liquid_density_ratio',
    # 'sedimentation_Stk',
    'sign_sedimentation_Re',
    # 'volume_fraction', 
    # 'relative_roughness', 
    # 'inclination',
    # 'wettability',
    # 'K',
)
log_features=(
    'relative_roughness',
    'sedimentation_Stk',
)
minmax_features_splash=(
    # 'relative_roughness',
    'inclination',
    'volume_fraction',
)
passthrough_features_splash=(
    'wettability',
)
minmax_features_no_fragm=(
    # 'relative_roughness',
)
passthrough_features_no_fragm=(
    'wettability',
    'inclination',
    'volume_fraction',
)
add_const=False
model_postfix='Stk_diam'

# Logit

In [5]:
estimator = StatsModelsEstimator(Logit)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run(
    save_model_and_metrics=False
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.397271
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.366859
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.385680
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.367731
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.392069
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.367136
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.373705
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.372093
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4272
Time:                        22:05:37   Log-Likelihood:                -110.51
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 5.574e-33
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
inclination                              3.2264      0.622      5.188      0.000       2.008       4.445
volume_fraction                          1.9815      0.906      2.187      0.029       0.205       3.758
sedimentation_Stk                        0.9250      0.278      3.324      0.001       0.380       1.470
sign_particle_droplet_diameter_ratio     0.3666      0.172      2.136      0.033       0.030       0.703
relative_roughness                       0.2987      0.171      1.743      0.081      -0.037       0.635
K                                        3.4893      0.426      8.191      0.000       2.654       4.324
wettability                             -0.6688      0.219     -3.058      0.002      -1.097      -0.240
========================================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_Stk_diam
holdout_test_accuracy                         0.8
holdout_test_f1                          0.851485
holdout_test_roc_auc                     0.878858
cv_test_accuracy_median                  0.811321
cv_test_f1_median                        0.852941
cv_test_roc_auc_median                   0.857585

In [6]:
estimator = StatsModelsEstimator(Logit)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run(
    save_model_and_metrics=False
)

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimization terminated successfully.
         Current function value: 0.282634
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.264131
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.292373
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.274057
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.278770
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.273943
         Iterations 9
Optimization terminated successfully.
         Current function value: 0.303203
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.286629
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.5052
Time:                        22:05:37   Log-Likelihood:                -85.129
converged:                       True   LL-Null:                       -172.03
Covariance Type:            nonrobust   LLR p-value:                 7.005e-35
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
sedimentation_Stk                       -1.0557      0.301     -3.502      0.000      -1.646      -0.465
sign_particle_droplet_diameter_ratio    -0.3979      0.198     -2.005      0.045      -0.787      -0.009
relative_roughness                      -0.4493      0.198     -2.271      0.023      -0.837      -0.062
K                                       -4.1187      0.560     -7.358      0.000      -5.216      -3.022
wettability                              1.7124      0.310      5.518      0.000       1.104       2.321
inclination                             -6.2865      1.060     -5.932      0.000      -8.363      -4.210
volume_fraction                        -19.2408      3.812     -5.048      0.000     -26.711     -11.770
========================================================================================================

                                                       0
target                                  no_fragmentation
model                    Logit_no_fragmentation_Stk_diam
holdout_test_accuracy                               0.88
holdout_test_f1                                 0.790698
holdout_test_roc_auc                                0.95
cv_test_accuracy_median                         0.867925
cv_test_f1_median                                   0.72
cv_test_roc_auc_median                          0.924908

# Logistic Regression

In [7]:
estimator = LogisticRegression(
    fit_intercept=False,
)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "LogisticRegression"

                                                             0
target                                               splashing
model                    LogisticRegression_splashing_Stk_diam
holdout_test_accuracy                                 0.813333
holdout_test_f1                                           0.86
holdout_test_roc_auc                                  0.885802
cv_test_accuracy_median                               0.792453
cv_test_f1_median                                     0.835821
cv_test_roc_auc_median                                0.859133

Model saved in ../results/models_modelling3/LogisticRegression_splashing_Stk_diam

In [8]:
estimator = LogisticRegression(
    fit_intercept=False,
)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "LogisticRegression"

                                                                    0
target                                               no_fragmentation
model                    LogisticRegression_no_fragmentation_Stk_diam
holdout_test_accuracy                                        0.853333
holdout_test_f1                                              0.755556
holdout_test_roc_auc                                         0.929091
cv_test_accuracy_median                                       0.87037
cv_test_f1_median                                            0.774194
cv_test_roc_auc_median                                       0.940171

Model saved in ../results/models_modelling3/LogisticRegression_no_fragmentation_Stk_diam

# KNClassifier

In [9]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "KNeighborsClassifier"

                                                               0
target                                                 splashing
model                    KNeighborsClassifier_splashing_Stk_diam
holdout_test_accuracy                                   0.866667
holdout_test_f1                                         0.897959
holdout_test_roc_auc                                    0.875386
cv_test_accuracy_median                                 0.849057
cv_test_f1_median                                       0.882353
cv_test_roc_auc_median                                  0.910526

Model saved in ../results/models_modelling3/KNeighborsClassifier_splashing_Stk_diam

In [10]:
estimator = KNeighborsClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "KNeighborsClassifier"

                                                                      0
target                                                 no_fragmentation
model                    KNeighborsClassifier_no_fragmentation_Stk_diam
holdout_test_accuracy                                          0.906667
holdout_test_f1                                                0.829268
holdout_test_roc_auc                                               0.97
cv_test_accuracy_median                                        0.849057
cv_test_f1_median                                              0.714286
cv_test_roc_auc_median                                         0.897436

Model saved in ../results/models_modelling3/KNeighborsClassifier_no_fragmentation_Stk_diam

# SVC

In [11]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "SVC"

                                              0
target                                splashing
model                    SVC_splashing_Stk_diam
holdout_test_accuracy                  0.826667
holdout_test_f1                        0.868687
holdout_test_roc_auc                   0.927469
cv_test_accuracy_median                0.849057
cv_test_f1_median                      0.878788
cv_test_roc_auc_median                 0.913313

Model saved in ../results/models_modelling3/SVC_splashing_Stk_diam

In [12]:
estimator = SVC(probability=True)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "SVC"

                                                     0
target                                no_fragmentation
model                    SVC_no_fragmentation_Stk_diam
holdout_test_accuracy                             0.84
holdout_test_f1                               0.684211
holdout_test_roc_auc                              0.96
cv_test_accuracy_median                       0.849057
cv_test_f1_median                             0.692308
cv_test_roc_auc_median                        0.930403

Model saved in ../results/models_modelling3/SVC_no_fragmentation_Stk_diam

# CatBoost

In [13]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "CatBoostClassifier"

                                                             0
target                                               splashing
model                    CatBoostClassifier_splashing_Stk_diam
holdout_test_accuracy                                 0.866667
holdout_test_f1                                       0.901961
holdout_test_roc_auc                                  0.958333
cv_test_accuracy_median                                0.90566
cv_test_f1_median                                     0.925373
cv_test_roc_auc_median                                0.948916

Model saved in ../results/models_modelling3/CatBoostClassifier_splashing_Stk_diam

In [14]:
estimator = CatBoostClassifier(verbose=False)

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "CatBoostClassifier"

                                                                    0
target                                               no_fragmentation
model                    CatBoostClassifier_no_fragmentation_Stk_diam
holdout_test_accuracy                                            0.96
holdout_test_f1                                              0.926829
holdout_test_roc_auc                                         0.988182
cv_test_accuracy_median                                      0.924528
cv_test_f1_median                                            0.857143
cv_test_roc_auc_median                                       0.981685

Model saved in ../results/models_modelling3/CatBoostClassifier_no_fragmentation_Stk_diam

# XGBoost

In [15]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_splash,
    passthrough_features=passthrough_features_splash,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

no summary in estimator class "XGBClassifier"

                                                        0
target                                          splashing
model                    XGBClassifier_splashing_Stk_diam
holdout_test_accuracy                                0.88
holdout_test_f1                                  0.910891
holdout_test_roc_auc                             0.940201
cv_test_accuracy_median                          0.867925
cv_test_f1_median                                0.898551
cv_test_roc_auc_median                           0.938095

Model saved in ../results/models_modelling3/XGBClassifier_splashing_Stk_diam

In [16]:
estimator = XGBClassifier()

ml_pipe = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=features_to_drop,
    minmax_features=minmax_features_no_fragm,
    passthrough_features=passthrough_features_no_fragm,
    log_features=log_features,
    add_const=add_const,
    model_postfix=model_postfix,
)

ml_pipe.run()

Load dataset from: ../data/df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_no_fragmentation.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

no summary in estimator class "XGBClassifier"

                                                               0
target                                          no_fragmentation
model                    XGBClassifier_no_fragmentation_Stk_diam
holdout_test_accuracy                                   0.933333
holdout_test_f1                                         0.871795
holdout_test_roc_auc                                    0.987273
cv_test_accuracy_median                                  0.90566
cv_test_f1_median                                       0.814815
cv_test_roc_auc_median                                  0.976068

Model saved in ../results/models_modelling3/XGBClassifier_no_fragmentation_Stk_diam