# Import Libraries

Enable automatic reloading of modules during interactive development:

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np

import joblib

from statsmodels.api import Logit # type: ignore

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    # _prepare_df,
    MLPipeline,
    _create_pipeline,
    StatsModelsEstimator,
)

In [2]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    model_postfix='research',
)

ml_pipe.run(
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re',
 'particle_liquid_density_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re',
                                  'particle_liquid_density_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.404380
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.376612
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.397960
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.389046
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.401565
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.371844
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.387222
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.384420
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4082
Time:                        22:00:41   Log-Likelihood:                -114.17
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 1.983e-31
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
inclination                       2.9317      0.637      4.602      0.000       1.683       4.180
volume_fraction                   3.2403      0.861      3.764      0.000       1.553       4.928
sign_sedimentation_Re             0.6854      0.204      3.364      0.001       0.286       1.085
particle_liquid_density_ratio    -0.3194      0.139     -2.300      0.021      -0.591      -0.047
relative_roughness                0.3266      0.167      1.954      0.051      -0.001       0.654
K                                 3.7320      0.503      7.422      0.000       2.747       4.717
wettability                      -0.5327      0.211     -2.527      0.011      -0.946      -0.120
=================================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_research
holdout_test_accuracy                    0.826667
holdout_test_f1                          0.871287
holdout_test_roc_auc                      0.87963
cv_test_accuracy_median                  0.754717
cv_test_f1_median                        0.816901
cv_test_roc_auc_median                   0.904025

Without volume fraction (bad!)

In [3]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'sign_particle_droplet_diameter_ratio',
        'sign_sedimentation_Stk',
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sedimentation_Re',
        # 'sedimentation_Stk',
        'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    minmax_features=(
        'relative_roughness',
    ),
    passthrough_features=(
        'wettability',
        'inclination',
        'volume_fraction',
    ),
    log_features=(
        'relative_roughness',
        'sedimentation_Stk',
    ),
    add_const=False,
    model_postfix='research',
)

ml_pipe.run(
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('relative_roughness',)),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination'))])

Optimization terminated successfully.
         Current function value: 0.387517
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.356430
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.376148
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.355164
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.381749
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.356109
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.358707
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.360794
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      291
Method:                           MLE   Df Model:                            5
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4446
Time:                        22:00:41   Log-Likelihood:                -107.16
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 3.398e-35
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
relative_roughness        1.4402      0.393      3.663      0.000       0.670       2.211
sign_sedimentation_Re     0.5854      0.220      2.664      0.008       0.155       1.016
sedimentation_Stk         0.8114      0.266      3.045      0.002       0.289       1.334
K                         3.6087      0.454      7.955      0.000       2.720       4.498
wettability              -0.6031      0.218     -2.764      0.006      -1.031      -0.175
inclination               4.1358      0.783      5.284      0.000       2.602       5.670
=========================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_research
holdout_test_accuracy                         0.8
holdout_test_f1                          0.848485
holdout_test_roc_auc                     0.888117
cv_test_accuracy_median                  0.773585
cv_test_f1_median                        0.818182
cv_test_roc_auc_median                   0.859133

Almost Best alternative:

In [4]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'sign_particle_droplet_diameter_ratio',
        'sign_sedimentation_Stk',
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sedimentation_Re',
        # 'sedimentation_Stk',
        'particle_liquid_density_ratio',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    minmax_features=(
        # 'relative_roughness',
    ),
    passthrough_features=(
        'wettability',
        'inclination',
        'volume_fraction',
    ),
    log_features=(
        'relative_roughness',
        'sedimentation_Stk',
    ),
    add_const=False,
    model_postfix='research',
)

ml_pipe.run(
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability', 'inclination',
                                  'volume_fraction'))])

Optimization terminated successfully.
         Current function value: 0.390982
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.359199
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.378528
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.362077
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.385731
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.357813
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.363761
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.365679
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4371
Time:                        22:00:41   Log-Likelihood:                -108.61
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 8.680e-34
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
sign_sedimentation_Re     0.5035      0.219      2.296      0.022       0.074       0.933
sedimentation_Stk         0.7882      0.277      2.850      0.004       0.246       1.330
relative_roughness        0.2791      0.172      1.619      0.105      -0.059       0.617
K                         3.6747      0.466      7.892      0.000       2.762       4.587
wettability              -0.6763      0.221     -3.057      0.002      -1.110      -0.243
inclination               3.9087      0.810      4.824      0.000       2.321       5.497
volume_fraction           8.7451      3.048      2.869      0.004       2.771      14.720
=========================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_research
holdout_test_accuracy                    0.813333
holdout_test_f1                              0.86
holdout_test_roc_auc                     0.885802
cv_test_accuracy_median                  0.792453
cv_test_f1_median                         0.84058
cv_test_roc_auc_median                   0.862229

## Alternative. Stat. important roughness

In [5]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        'sign_particle_droplet_diameter_ratio',
        'sign_sedimentation_Stk',
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'particle_liquid_density_ratio',
        # 'sedimentation_Stk',
        # 'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    minmax_features=(
        # 'relative_roughness',
        'inclination',
        'volume_fraction',
    ),
    passthrough_features=(
        'wettability',
    ),
    log_features=(
        'relative_roughness',
        'sedimentation_Stk',
    ),
    add_const=False,
    model_postfix='research',
)

ml_pipe.run(
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sign_sedimentation_Re', 'sedimentation_Stk', 'relative_roughness', 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sign_sedimentation_Re', 'sedimentation_Stk',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.396331
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.365700
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.384199
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.366459
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.390900
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.367264
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.371445
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.372357
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4268
Time:                        22:00:42   Log-Likelihood:                -110.59
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 6.018e-33
=========================================================================================
                            coef    std err          z      P>|z|      [0.025      0.975]
-----------------------------------------------------------------------------------------
inclination               3.2523      0.632      5.145      0.000       2.013       4.491
volume_fraction           1.9645      0.910      2.158      0.031       0.181       3.748
sign_sedimentation_Re     0.4562      0.213      2.141      0.032       0.039       0.874
sedimentation_Stk         0.9033      0.276      3.272      0.001       0.362       1.444
relative_roughness        0.2893      0.171      1.691      0.091      -0.046       0.625
K                         3.6330      0.447      8.123      0.000       2.756       4.510
wettability              -0.6507      0.218     -2.983      0.003      -1.078      -0.223
=========================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_research
holdout_test_accuracy                    0.813333
holdout_test_f1                              0.86
holdout_test_roc_auc                     0.884259
cv_test_accuracy_median                  0.792453
cv_test_f1_median                         0.84058
cv_test_roc_auc_median                   0.859133

# Features with signs (Best solution)

In [6]:
# from sklearn.linear_model import LogisticRegression

estimator = StatsModelsEstimator(Logit)
# estimator = LogisticRegression()

ml_pipe = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop = (
        # 'sign_particle_droplet_diameter_ratio',
        'sign_sedimentation_Stk',
        'Re', 
        'We', 
        'init_volume_fraction',
        'particle_droplet_diameter_ratio',
        'sedimentation_Re',
        'particle_liquid_density_ratio',
        # 'sedimentation_Stk',
        'sign_sedimentation_Re',
        # 'volume_fraction', 
        # 'relative_roughness', 
        # 'inclination',
        # 'wettability',
        # 'K',
    ),
    minmax_features=(
        # 'relative_roughness',
        'inclination',
        'volume_fraction',
    ),
    passthrough_features=(
        'wettability',
    ),
    log_features=(
        'relative_roughness',
        'sedimentation_Stk',
    ),
    add_const=False,
    model_postfix='research',
)

ml_pipe.run(
    save_model_and_metrics=False,
)

Load dataset from: ../data/df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ../data/df_ml_split_splashing.xlsx
std_features

('sedimentation_Stk',
 'sign_particle_droplet_diameter_ratio',
 'relative_roughness',
 'K')

ColumnTransformer(transformers=[('minmax', MinMaxScaler(),
                                 ('inclination', 'volume_fraction')),
                                ('std', StandardScaler(),
                                 ('sedimentation_Stk',
                                  'sign_particle_droplet_diameter_ratio',
                                  'relative_roughness', 'K')),
                                ('passthrough', 'passthrough',
                                 ('wettability',))])

Optimization terminated successfully.
         Current function value: 0.397271
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.366859
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.385680
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.367731
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.392069
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.367136
         Iterations 8
Optimization terminated successfully.
         Current function value: 0.373705
         Iterations 7
Optimization terminated successfully.
         Current function value: 0.372093
         Iterations 8
                           Logit Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:                  297
Model:                          Logit   Df Residuals:                      290
Method:                           MLE   Df Model:                            6
Date:                Sun, 13 Oct 2024   Pseudo R-squ.:                  0.4272
Time:                        22:00:42   Log-Likelihood:                -110.51
converged:                       True   LL-Null:                       -192.93
Covariance Type:            nonrobust   LLR p-value:                 5.574e-33
========================================================================================================
                                           coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------
inclination                              3.2264      0.622      5.188      0.000       2.008       4.445
volume_fraction                          1.9815      0.906      2.187      0.029       0.205       3.758
sedimentation_Stk                        0.9250      0.278      3.324      0.001       0.380       1.470
sign_particle_droplet_diameter_ratio     0.3666      0.172      2.136      0.033       0.030       0.703
relative_roughness                       0.2987      0.171      1.743      0.081      -0.037       0.635
K                                        3.4893      0.426      8.191      0.000       2.654       4.324
wettability                             -0.6688      0.219     -3.058      0.002      -1.097      -0.240
========================================================================================================

                                                0
target                                  splashing
model                    Logit_splashing_research
holdout_test_accuracy                         0.8
holdout_test_f1                          0.851485
holdout_test_roc_auc                     0.878858
cv_test_accuracy_median                  0.811321
cv_test_f1_median                        0.852941
cv_test_roc_auc_median                   0.857585

In [7]:
ml_pipe.pipe.steps[1][-1].transformers_[1][1].mean_

array([-9.20070718e+00,  1.75827540e-02, -3.96211099e+00,  1.51512472e+02])

In [8]:
ml_pipe.pipe.steps[1][-1].transformers_[1][1].get_feature_names_out()

array(['sedimentation_Stk', 'sign_particle_droplet_diameter_ratio',
       'relative_roughness', 'K'], dtype=object)