Comparison with baseline decision stump $K < threshold$

# Import libraries

In [1]:
# Changes to all modules will automatically be applied when any cell runs. 
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

import joblib

from pathlib import Path
import sys

sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

from split_tools import get_train_test
from modelling3_utils import (
    MLPipeline,
    DecisionStumpEstimator,
    StatsModelsEstimator
)
from statsmodels.api import Logit

# Pipeline with $K=147$

In [12]:
estimator = DecisionStumpEstimator(threshold=147, less_sign=False)
ml_pipe_ds = MLPipeline(
    target='splashing',
    estimator=estimator,
    features_to_drop=('init_volume_fraction', 'volume_fraction', 'sedimentation_Re',
       'sign_sedimentation_Re', 'sign_sedimentation_Stk', 'sedimentation_Stk',
       'particle_liquid_density_ratio', 'particle_droplet_diameter_ratio',
       'sign_particle_droplet_diameter_ratio', 'wettability',
       'relative_roughness', 'inclination', 'Re', 'We',),
    passthrough_features=('K'),
    model_postfix='greater_or_equal_147')

ml_pipe_ds.run(
    save_model_and_metrics=True)

Load dataset from: ..\data\df_dimless.xlsx
Keep "splashing" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_splashing.xlsx
std_features

()

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(), ()),
                                ('passthrough', 'passthrough', ('K',))])

no summary in estimator class "DecisionStumpEstimator"

                                                                    0
target                                                      splashing
model                    DecisionStump_splashing_greater_or_equal_147
holdout_test_accuracy                                        0.693333
holdout_test_f1                                              0.708861
holdout_test_roc_auc                                         0.736111
cv_test_accuracy_median                                      0.698113
cv_test_f1_median                                            0.703704
cv_test_roc_auc_median                                       0.753096

Model saved in ..\results\models_modelling3\DecisionStump_splashing_greater_or_equal_147

In [15]:
estimator = DecisionStumpEstimator(threshold=147, less_sign=True)
ml_pipe_ds = MLPipeline(
    target='no_fragmentation',
    estimator=estimator,
    features_to_drop=('init_volume_fraction', 'volume_fraction', 'sedimentation_Re',
       'sign_sedimentation_Re', 'sign_sedimentation_Stk', 'sedimentation_Stk',
       'particle_liquid_density_ratio', 'particle_droplet_diameter_ratio',
       'sign_particle_droplet_diameter_ratio', 'wettability',
       'relative_roughness', 'inclination', 'Re', 'We',),
    passthrough_features=('K'),
    model_postfix='less_147')

ml_pipe_ds.run(
    save_model_and_metrics=True)

Load dataset from: ..\data\df_dimless.xlsx
Keep "no_fragmentation" from {'no_fragmentation', 'splashing'}
Load split indexes from: ..\data\df_ml_split_no_fragmentation.xlsx
std_features

()

ColumnTransformer(transformers=[('minmax', MinMaxScaler(), ()),
                                ('std', StandardScaler(), ()),
                                ('passthrough', 'passthrough', ('K',))])

no summary in estimator class "DecisionStumpEstimator"

                                                               0
target                                          no_fragmentation
model                    DecisionStump_no_fragmentation_less_147
holdout_test_accuracy                                   0.586667
holdout_test_f1                                          0.56338
holdout_test_roc_auc                                    0.718182
cv_test_accuracy_median                                 0.641509
cv_test_f1_median                                       0.595745
cv_test_roc_auc_median                                   0.75641

Model saved in ..\results\models_modelling3\DecisionStump_no_fragmentation_less_147