Hyperparams selection

# Libraries

In [15]:
import openpyxl
import pandas as pd
from pathlib import Path
import numpy as np
import sys
from tqdm import tqdm
import optuna
import json

In [2]:
# train/test split
sys.path.insert(1, '../utils_functionality/split_utils/')
from split_tools import get_train_test

In [3]:
# hyperparams
sys.path.insert(1, '../utils_functionality/models/')
from modelling2_hyperparams import objective

In [4]:
RANDOM_STATE = 42

# Datatasets selection

In [5]:
path_data = Path('../data')
path_results = Path('../results/')
path_highlighted = path_results / 'metrics_modelling2_highlight.xlsx'
df_highlighted = pd.read_excel(path_highlighted)
wb = openpyxl.load_workbook(path_highlighted, data_only=True)
ws = wb.worksheets[0]

In [6]:
highlighted_rows = []
for row in range(1, ws.max_row):
    cell = ws.cell(column=1, row=row)
    bgColor = cell.fill.bgColor.index
    fgColor = cell.fill.fgColor.index
    if bgColor != '00000000':
        highlighted_rows.append(row)
highlighted_rows = np.array(highlighted_rows) - 2
df_filtered = df_highlighted.iloc[highlighted_rows]

Datasets for parameters selection.

In [7]:
df_filtered

,dataset,target,model,accuracy,f1,precision,recall,roc_auc
2,df_modelling_no_multicollinearity,splashing,catboostclassifier_splashing,0.866667,0.900000,0.865385,0.937500,0.839120
3,df_modelling_dimensionless,splashing,kneighborsclassifier_splashing_ordenc,0.866667,0.900000,0.865385,0.937500,0.839120
4,df_modelling_dimensionless,splashing,catboostclassifier_splashing,0.866667,0.900000,0.865385,0.937500,0.839120
5,df_modelling_dimensionless,net_impact,catboostclassifier_net_impact,0.946667,0.900000,0.900000,0.900000,0.931818
6,df_modelling_dimensionless,splashing,kneighborsclassifier_smote_splashing_ordenc,0.866667,0.897959,0.880000,0.916667,0.847222
7,df_modelling_dimensionless,splashing,kneighborsclassifier_splashing_onehot,0.853333,0.891089,0.849057,0.937500,0.820602
8,df_modelling_dimensionless,splashing,svc_smote_splashing_onehot,0.853333,0.888889,0.862745,0.916667,0.828704
11,df_modelling_no_multicollinearity,splashing,catboostclassifier_smote_splashing,0.853333,0.886598,0.877551,0.895833,0.836806
12,df_modelling_dimensionless,splashing,catboostclassifier_smote_splashing,0.853333,0.886598,0.877551,0.895833,0.836806
13,df_modelling_dimensionless,splashing,logisticregression_splashing_onehot,0.840000,0.880000,0.846154,0.916667,0.810185
15,df_modelling_no_multicollinearity,net_impact,kneighborsclassifier_net_impact_ordenc,0.933333,0.878049,0.857143,0.900000,0.922727
16,df_modelling_no_multicollinearity,net_impact,catboostclassifier_smote_net_impact,0.933333,0.878049,0.857143,0.900000,0.922727
17,df_modelling_no_multicollinearity,net_impact,catboostclassifier_net_impact,0.933333,0.878049,0.857143,0.900000,0.922727
18,df_modelling_dimensionless,net_impact,catboostclassifier_smote_net_impact,0.933333,0.878049,0.857143,0.900000,0.922727
20,df_modelling_dimensionless,splashing,svc_smote_splashing_ordenc,0.840000,0.877551,0.860000,0.895833,0.818287
37,df_modelling_no_multicollinearity,net_impact,kneighborsclassifier_net_impact_onehot,0.920000,0.857143,0.818182,0.900000,0.913636
61,df_modelling_no_multicollinearity,net_impact,svc_smote_net_impact_onehot,0.893333,0.826087,0.730769,0.950000,0.911364
64,df_modelling_no_multicollinearity,net_impact,logisticregression_net_impact_ordenc,0.893333,0.800000,0.800000,0.800000,0.863636
65,df_modelling_dimensionless,net_impact,logisticregression_net_impact_ordenc,0.893333,0.800000,0.800000,0.800000,0.863636
66,df_modelling_no_multicollinearity,net_impact,kneighborsclassifier_smote_net_impact_ordenc,0.880000,0.800000,0.720000,0.900000,0.886364
67,df_modelling_dimensionless,net_impact,svc_smote_net_impact_onehot,0.880000,0.800000,0.720000,0.900000,0.886364
68,df_modelling_dimensionless,net_impact,svc_smote_net_impact_ordenc,0.880000,0.800000,0.720000,0.900000,0.886364

In [8]:
sorted(df_filtered['model'].unique())

['catboostclassifier_net_impact',
 'catboostclassifier_smote_net_impact',
 'catboostclassifier_smote_splashing',
 'catboostclassifier_splashing',
 'kneighborsclassifier_net_impact_onehot',
 'kneighborsclassifier_net_impact_ordenc',
 'kneighborsclassifier_smote_net_impact_ordenc',
 'kneighborsclassifier_smote_splashing_ordenc',
 'kneighborsclassifier_splashing_onehot',
 'kneighborsclassifier_splashing_ordenc',
 'logisticregression_net_impact_ordenc',
 'logisticregression_splashing_onehot',
 'svc_smote_net_impact_onehot',
 'svc_smote_net_impact_ordenc',
 'svc_smote_splashing_onehot',
 'svc_smote_splashing_ordenc']

# Parameters selection

In [9]:
df_filtered.head(2)

,dataset,target,model,accuracy,f1,precision,recall,roc_auc
2,df_modelling_no_multicollinearity,splashing,catboostclassifier_splashing,0.866667,0.9,0.865385,0.9375,0.83912
3,df_modelling_dimensionless,splashing,kneighborsclassifier_splashing_ordenc,0.866667,0.9,0.865385,0.9375,0.83912

In [16]:
dict_results = {}
for i in (pbar:=tqdm(range(df_filtered.shape[0]))):
    dataset_filename = df_filtered.iloc[i]['dataset']
    if 'df_full' in dataset_filename: continue
    model_str = df_filtered.iloc[i]['model']
    pbar.set_description(f"Processing {model_str}")
    target = df_filtered.iloc[i]['target']
    train, test = get_train_test(
        dataset_filename=dataset_filename,
        target=target)
    study = optuna.create_study(direction="maximize")
    def obj(trial):
        return objective(
            trial, train, test, 
            target, model_str, dataset_filename=dataset_filename, 
            random_state=RANDOM_STATE, cat_features=['wettability'])
    study.optimize(obj, n_trials=3, timeout=10)
    dict_results[model_str] = {
            'dataset': dataset_filename,
            'model': model_str,
            'target': target,
            'f1': study.best_value,
            'best_params': study.best_params}
with open("../results/optuna_results.json", "w") as outfile: 
    json.dump(dict_results, outfile)

Processing catboostclassifier_splashing:   0%|          | 0/22 [00:00<?, ?it/s][I 2024-03-09 12:53:00,946] A new study created in memory with name: no-name-c96c0d69-ca37-4ede-8cc9-218ef2f23d6c
[I 2024-03-09 12:53:02,309] Trial 0 finished with value: 0.9 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.06750422065623855, 'depth': 6, 'boosting_type': 'Plain', 'bootstrap_type': 'Bernoulli', 'subsample': 0.7194560675200535}. Best is trial 0 with value: 0.9.
[I 2024-03-09 12:53:06,620] Trial 1 finished with value: 0.8598130841121496 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.08317451861599388, 'depth': 6, 'boosting_type': 'Ordered', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 3.3210956082289744}. Best is trial 0 with value: 0.9.
[I 2024-03-09 12:53:07,739] Trial 2 finished with value: 0.8392857142857143 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.029529478016267964, 'depth': 9, 'boosting_type': 'Plain', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.9.
Processing kneighborsclassifier_splashing_ordenc:   5%|▍         | 1/22 [00:06<02:23,  6.84s/it][I 2024-03-09 12:53:07,779] A new study created in memory with name: no-name-dffbeaf6-46f6-42fd-b78d-15e9f2bff455
[I 2024-03-09 12:53:07,793] Trial 0 finished with value: 0.875 and parameters: {'algorithm': 'brute', 'n_neighbors': 28, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.875.
[I 2024-03-09 12:53:07,803] Trial 1 finished with value: 0.8659793814432989 and parameters: {'algorithm': 'kd_tree', 'n_neighbors': 27, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.875.
[I 2024-03-09 12:53:07,813] Trial 2 finished with value: 0.86 and parameters: {'algorithm': 'auto', 'n_neighbors': 29, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 0 with value: 0.875.
Processing catboostclassifier_splashing:   5%|▍         | 1/22 [00:06<02:23,  6.84s/it]         [I 2024-03-09 12:53:07,864] A new study created in memory with name: no-name-50ca7f47-e768-4642-ab95-09daf23a1b61
[I 2024-03-09 12:53:08,829] Trial 0 finished with value: 0.854368932038835 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.030895471046189595, 'depth': 10, 'boosting_type': 'Plain', 'bootstrap_type': 'Bernoulli', 'subsample': 0.6777202218523335}. Best is trial 0 with value: 0.854368932038835.
[I 2024-03-09 12:53:11,818] Trial 1 finished with value: 0.8799999999999999 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.06058300201559248, 'depth': 7, 'boosting_type': 'Ordered', 'bootstrap_type': 'MVS'}. Best is trial 1 with value: 0.8799999999999999.
[I 2024-03-09 12:53:13,189] Trial 2 finished with value: 0.8627450980392156 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.06992701236399063, 'depth': 5, 'boosting_type': 'Plain', 'bootstrap_type': 'MVS'}. Best is trial 1 with value: 0.8799999999999999.
Processing catboostclassifier_net_impact:  14%|█▎        | 3/22 [00:12<01:12,  3.79s/it][I 2024-03-09 12:53:13,228] A new study created in memory with name: no-name-1e508d3b-8c1b-4f5e-9c5e-08b5c6c34f7e
[I 2024-03-09 12:53:14,295] Trial 0 finished with value: 0.0 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.032077269780363106, 'depth': 8, 'boosting_type': 'Plain', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 9.539628687038759}. Best is trial 0 with value: 0.0.
[I 2024-03-09 12:53:17,035] Trial 1 finished with value: 0.09523809523809523 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.032368644075584097, 'depth': 7, 'boosting_type': 'Ordered', 'bootstrap_type': 'MVS'}. Best is trial 1 with value: 0.09523809523809523.
[I 2024-03-09 12:53:19,178] Trial 2 finished with value: 0.8372093023255814 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.07565000748492076, 'depth': 11, 'boosting_type': 'Plain', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5762772257361392}. Best is trial 2 with value: 0.8372093023255814.
Processing kneighborsclassifier_smote_splashing_ordenc:  18%|█▊        | 4/22 [00:18<01:21,  4.55s/it][I 2024-03-09 12:53:19,265] A new study created in memory with name: no-name-d2d5be38-dba8-475f-ba7e-6b9de90d7847
[I 2024-03-09 12:53:19,280] Trial 0 finished with value: 0.8686868686868686 and parameters: {'algorithm': 'kd_tree', 'n_neighbors': 9, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 0 with value: 0.8686868686868686.
[I 2024-03-09 12:53:19,296] Trial 1 finished with value: 0.8686868686868686 and parameters: {'algorithm': 'auto', 'n_neighbors': 6, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 0 with value: 0.8686868686868686.
[I 2024-03-09 12:53:19,324] Trial 2 finished with value: 0.9052631578947369 and parameters: {'algorithm': 'brute', 'n_neighbors': 1, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 2 with value: 0.9052631578947369.
Processing kneighborsclassifier_splashing_onehot:  23%|██▎       | 5/22 [00:18<00:52,  3.09s/it]      [I 2024-03-09 12:53:19,405] A new study created in memory with name: no-name-c0c6b0bb-4421-481a-9acf-1f78fc32cdc9
[I 2024-03-09 12:53:19,420] Trial 0 finished with value: 0.875 and parameters: {'algorithm': 'ball_tree', 'n_neighbors': 20, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.875.
[I 2024-03-09 12:53:19,440] Trial 1 finished with value: 0.8349514563106797 and parameters: {'algorithm': 'auto', 'n_neighbors': 16, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 0 with value: 0.875.
[I 2024-03-09 12:53:19,461] Trial 2 finished with value: 0.8571428571428572 and parameters: {'algorithm': 'ball_tree', 'n_neighbors': 14, 'weights': 'uniform', 'metric': 'manhattan'}. Best is trial 0 with value: 0.875.
Processing svc_smote_splashing_onehot:  27%|██▋       | 6/22 [00:18<00:34,  2.15s/it]           [I 2024-03-09 12:53:19,549] A new study created in memory with name: no-name-c043bc8f-49c6-4f51-b68d-aebace0e572d
[I 2024-03-09 12:53:19,566] Trial 0 finished with value: 0.8571428571428572 and parameters: {'C': 0.04612844660037404, 'kernel': 'linear', 'gamma': 4540.337574740237, 'degree': 2, 'coef0': -0.0705573154642325}. Best is trial 0 with value: 0.8571428571428572.
[I 2024-03-09 12:53:19,602] Trial 1 finished with value: 0.8799999999999999 and parameters: {'C': 10542.628301270192, 'kernel': 'rbf', 'gamma': 3.247529110838254, 'degree': 3, 'coef0': 0.10922472049459109}. Best is trial 1 with value: 0.8799999999999999.
[I 2024-03-09 12:53:19,628] Trial 2 finished with value: 0.9072164948453607 and parameters: {'C': 2999.8867037781697, 'kernel': 'rbf', 'gamma': 0.03305466603435047, 'degree': 3, 'coef0': -0.6275990681237433}. Best is trial 2 with value: 0.9072164948453607.
Processing catboostclassifier_smote_splashing:  32%|███▏      | 7/22 [00:18<00:22,  1.52s/it][I 2024-03-09 12:53:19,734] A new study created in memory with name: no-name-7f02c5ae-6847-4de3-a6f1-e8dc1ec9635a
[I 2024-03-09 12:53:28,906] Trial 0 finished with value: 0.8958333333333334 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.08812483547775297, 'depth': 10, 'boosting_type': 'Ordered', 'bootstrap_type': 'Bernoulli', 'subsample': 0.5131561850511044}. Best is trial 0 with value: 0.8958333333333334.
[I 2024-03-09 12:53:34,671] Trial 1 finished with value: 0.875 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.027613650546005786, 'depth': 5, 'boosting_type': 'Ordered', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.8958333333333334.
Processing catboostclassifier_smote_splashing:  36%|███▋      | 8/22 [00:33<01:19,  5.71s/it][I 2024-03-09 12:53:34,765] A new study created in memory with name: no-name-a35bcc1e-9f83-4a8d-bf0b-0a5d6c071903
[I 2024-03-09 12:53:39,675] Trial 0 finished with value: 0.875 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.07222550629366895, 'depth': 8, 'boosting_type': 'Ordered', 'bootstrap_type': 'Bernoulli', 'subsample': 0.10309094235409212}. Best is trial 0 with value: 0.875.
[I 2024-03-09 12:53:40,637] Trial 1 finished with value: 0.8865979381443299 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.02296776093777556, 'depth': 6, 'boosting_type': 'Plain', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 5.251498525125037}. Best is trial 1 with value: 0.8865979381443299.
[I 2024-03-09 12:53:43,375] Trial 2 finished with value: 0.8571428571428572 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.031251197704323164, 'depth': 9, 'boosting_type': 'Ordered', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 6.915056323919595}. Best is trial 1 with value: 0.8865979381443299.
Processing logisticregression_splashing_onehot:  41%|████      | 9/22 [00:42<01:26,  6.63s/it][I 2024-03-09 12:53:43,421] A new study created in memory with name: no-name-48b51c2b-4d39-4c59-8b69-10fe9d07cf45
[I 2024-03-09 12:53:43,434] Trial 0 finished with value: 0.0 and parameters: {'penalty': 'l1', 'C': 0.007711306249865791, 'solver': 'saga', 'max_iter': 128, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.0.
[I 2024-03-09 12:53:43,434] Trial 1 finished with value: 0.8333333333333334 and parameters: {'penalty': 'l2', 'C': 0.6154100897406556, 'solver': 'saga', 'max_iter': 268, 'class_weight': 'balanced'}. Best is trial 1 with value: 0.8333333333333334.
[I 2024-03-09 12:53:43,449] Trial 2 finished with value: 0.7804878048780487 and parameters: {'penalty': 'l1', 'C': 0.013642535812427777, 'solver': 'saga', 'max_iter': 205, 'class_weight': None}. Best is trial 1 with value: 0.8333333333333334.
Processing kneighborsclassifier_net_impact_ordenc:  41%|████      | 9/22 [00:42<01:26,  6.63s/it][I 2024-03-09 12:53:43,497] A new study created in memory with name: no-name-887f7e0b-a34c-457e-b153-cefc319ec01f
[I 2024-03-09 12:53:43,500] Trial 0 finished with value: 0.8095238095238095 and parameters: {'algorithm': 'brute', 'n_neighbors': 7, 'weights': 'uniform', 'metric': 'euclidean'}. Best is trial 0 with value: 0.8095238095238095.
[I 2024-03-09 12:53:43,524] Trial 1 finished with value: 0.7567567567567567 and parameters: {'algorithm': 'brute', 'n_neighbors': 10, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 0.8095238095238095.
[I 2024-03-09 12:53:43,531] Trial 2 finished with value: 0.4285714285714285 and parameters: {'algorithm': 'kd_tree', 'n_neighbors': 25, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 0.8095238095238095.
Processing catboostclassifier_smote_net_impact:  50%|█████     | 11/22 [00:42<00:39,  3.57s/it]   [I 2024-03-09 12:53:43,575] A new study created in memory with name: no-name-f4596ed0-cb6a-404c-b0ba-058e99b964ef
[I 2024-03-09 12:53:44,944] Trial 0 finished with value: 0.7659574468085106 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.07901746565775108, 'depth': 1, 'boosting_type': 'Plain', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.7659574468085106.
[I 2024-03-09 12:53:48,056] Trial 1 finished with value: 0.7307692307692308 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.07674832867702552, 'depth': 3, 'boosting_type': 'Ordered', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 7.95003930696207}. Best is trial 0 with value: 0.7659574468085106.
[I 2024-03-09 12:53:49,083] Trial 2 finished with value: 0.7307692307692308 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.03408915718114328, 'depth': 2, 'boosting_type': 'Plain', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.7659574468085106.
Processing catboostclassifier_net_impact:  55%|█████▍    | 12/22 [00:48<00:40,  4.07s/it]      [I 2024-03-09 12:53:49,123] A new study created in memory with name: no-name-05b17e54-1e74-45e4-8274-253dd24707d7
[I 2024-03-09 12:53:50,305] Trial 0 finished with value: 0.8095238095238095 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.052513811147863756, 'depth': 11, 'boosting_type': 'Plain', 'bootstrap_type': 'Bernoulli', 'subsample': 0.7635806445706275}. Best is trial 0 with value: 0.8095238095238095.
[I 2024-03-09 12:53:53,033] Trial 1 finished with value: 0.6285714285714286 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.031879748158736655, 'depth': 1, 'boosting_type': 'Ordered', 'bootstrap_type': 'Bernoulli', 'subsample': 0.46617540248492095}. Best is trial 0 with value: 0.8095238095238095.
[I 2024-03-09 12:53:54,256] Trial 2 finished with value: 0.8095238095238095 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.04579185972461101, 'depth': 10, 'boosting_type': 'Plain', 'bootstrap_type': 'MVS'}. Best is trial 0 with value: 0.8095238095238095.
Processing catboostclassifier_smote_net_impact:  59%|█████▉    | 13/22 [00:53<00:39,  4.36s/it][I 2024-03-09 12:53:54,305] A new study created in memory with name: no-name-4351948a-aff9-4556-a034-2db7db8801d1
[I 2024-03-09 12:53:55,390] Trial 0 finished with value: 0.679245283018868 and parameters: {'objective': 'Logloss', 'colsample_bylevel': 0.015738633235380252, 'depth': 9, 'boosting_type': 'Plain', 'bootstrap_type': 'Bayesian', 'bagging_temperature': 5.351060405892691}. Best is trial 0 with value: 0.679245283018868.
[I 2024-03-09 12:53:56,319] Trial 1 finished with value: 0.7307692307692308 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.021152085230215684, 'depth': 5, 'boosting_type': 'Plain', 'bootstrap_type': 'Bernoulli', 'subsample': 0.8013657207396734}. Best is trial 1 with value: 0.7307692307692308.
[I 2024-03-09 12:53:59,340] Trial 2 finished with value: 0.8085106382978724 and parameters: {'objective': 'CrossEntropy', 'colsample_bylevel': 0.060417919214158726, 'depth': 10, 'boosting_type': 'Ordered', 'bootstrap_type': 'MVS'}. Best is trial 2 with value: 0.8085106382978724.
Processing svc_smote_splashing_ordenc:  64%|██████▎   | 14/22 [00:58<00:36,  4.56s/it]         [I 2024-03-09 12:53:59,383] A new study created in memory with name: no-name-5d3e6b33-2c9d-42dc-9d46-1f3dff292e30
[I 2024-03-09 12:53:59,391] Trial 0 finished with value: 0.7804878048780487 and parameters: {'C': 1.3699221662594927, 'kernel': 'poly', 'gamma': 0.0006686600224175363, 'degree': 5, 'coef0': 0.25247211166273065}. Best is trial 0 with value: 0.7804878048780487.
[I 2024-03-09 12:53:59,398] Trial 1 finished with value: 0.8571428571428572 and parameters: {'C': 0.014579290048159358, 'kernel': 'linear', 'gamma': 0.00010392903268085527, 'degree': 3, 'coef0': 0.27955710593800265}. Best is trial 1 with value: 0.8571428571428572.
[I 2024-03-09 12:53:59,403] Trial 2 finished with value: 0.7804878048780487 and parameters: {'C': 0.00011640923026473096, 'kernel': 'sigmoid', 'gamma': 0.0005840143593048819, 'degree': 3, 'coef0': 0.07513351333701679}. Best is trial 1 with value: 0.8571428571428572.
Processing kneighborsclassifier_net_impact_onehot:  64%|██████▎   | 14/22 [00:58<00:36,  4.56s/it][I 2024-03-09 12:53:59,452] A new study created in memory with name: no-name-eced173e-b177-40d5-a4ef-ba06fd2b0353
[I 2024-03-09 12:53:59,459] Trial 0 finished with value: 0.37037037037037035 and parameters: {'algorithm': 'auto', 'n_neighbors': 20, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 0.37037037037037035.
[I 2024-03-09 12:53:59,468] Trial 1 finished with value: 0.37037037037037035 and parameters: {'algorithm': 'auto', 'n_neighbors': 28, 'weights': 'uniform', 'metric': 'minkowski'}. Best is trial 0 with value: 0.37037037037037035.
[I 2024-03-09 12:53:59,479] Trial 2 finished with value: 0.8 and parameters: {'algorithm': 'brute', 'n_neighbors': 25, 'weights': 'distance', 'metric': 'euclidean'}. Best is trial 2 with value: 0.8.
Processing svc_smote_net_impact_onehot:  73%|███████▎  | 16/22 [00:58<00:15,  2.59s/it]           [I 2024-03-09 12:53:59,597] A new study created in memory with name: no-name-6dd6cad8-329f-4399-9e49-922c8515a6bb
[I 2024-03-09 12:53:59,604] Trial 0 finished with value: 0.4571428571428572 and parameters: {'C': 1.239742652408095, 'kernel': 'sigmoid', 'gamma': 922.2888171607832, 'degree': 2, 'coef0': 0.24548021204527748}. Best is trial 0 with value: 0.4571428571428572.
[I 2024-03-09 12:53:59,612] Trial 1 finished with value: 0.41025641025641024 and parameters: {'C': 6.040860108890178, 'kernel': 'sigmoid', 'gamma': 97.45426931016469, 'degree': 4, 'coef0': -0.5541199851908412}. Best is trial 0 with value: 0.4571428571428572.
[I 2024-03-09 12:53:59,635] Trial 2 finished with value: 0.7441860465116279 and parameters: {'C': 32.16138753863665, 'kernel': 'poly', 'gamma': 9.369606477396331, 'degree': 5, 'coef0': 0.4198235283443341}. Best is trial 2 with value: 0.7441860465116279.
Processing logisticregression_net_impact_ordenc:  77%|███████▋  | 17/22 [00:58<00:10,  2.01s/it][I 2024-03-09 12:53:59,683] A new study created in memory with name: no-name-1b66fccd-5384-451f-81ec-f7d605ca43e4
[I 2024-03-09 12:53:59,687] Trial 0 finished with value: 0.4210526315789474 and parameters: {'penalty': 'l1', 'C': 0.0034075869420696022, 'solver': 'saga', 'max_iter': 209, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.4210526315789474.
[I 2024-03-09 12:53:59,700] Trial 1 finished with value: 0.7222222222222223 and parameters: {'penalty': 'l1', 'C': 0.14084457329814754, 'solver': 'saga', 'max_iter': 204, 'class_weight': None}. Best is trial 1 with value: 0.7222222222222223.
[I 2024-03-09 12:53:59,704] Trial 2 finished with value: 0.0 and parameters: {'penalty': 'l1', 'C': 0.005190034604080465, 'solver': 'saga', 'max_iter': 178, 'class_weight': None}. Best is trial 1 with value: 0.7222222222222223.
Processing logisticregression_net_impact_ordenc:  77%|███████▋  | 17/22 [00:58<00:10,  2.01s/it][I 2024-03-09 12:53:59,746] A new study created in memory with name: no-name-c69228bc-be31-47ce-8b25-6f97fa8be10d
[I 2024-03-09 12:53:59,750] Trial 0 finished with value: 0.723404255319149 and parameters: {'penalty': 'l1', 'C': 0.10252059556645947, 'solver': 'saga', 'max_iter': 162, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.723404255319149.
[I 2024-03-09 12:53:59,760] Trial 1 finished with value: 0.0 and parameters: {'penalty': 'l1', 'C': 0.0021605455861958734, 'solver': 'liblinear', 'max_iter': 199, 'class_weight': None}. Best is trial 0 with value: 0.723404255319149.
[I 2024-03-09 12:53:59,766] Trial 2 finished with value: 0.7083333333333333 and parameters: {'penalty': 'l1', 'C': 1.019492288526727, 'solver': 'liblinear', 'max_iter': 188, 'class_weight': 'balanced'}. Best is trial 0 with value: 0.723404255319149.
Processing kneighborsclassifier_smote_net_impact_ordenc:  86%|████████▋ | 19/22 [00:58<00:03,  1.22s/it][I 2024-03-09 12:53:59,812] A new study created in memory with name: no-name-f1405323-7f80-4382-bdf4-6800d51a4b28
[I 2024-03-09 12:53:59,819] Trial 0 finished with value: 0.85 and parameters: {'algorithm': 'kd_tree', 'n_neighbors': 6, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.85.
[I 2024-03-09 12:53:59,833] Trial 1 finished with value: 0.85 and parameters: {'algorithm': 'brute', 'n_neighbors': 6, 'weights': 'distance', 'metric': 'manhattan'}. Best is trial 0 with value: 0.85.
[I 2024-03-09 12:53:59,849] Trial 2 finished with value: 0.8333333333333334 and parameters: {'algorithm': 'brute', 'n_neighbors': 17, 'weights': 'distance', 'metric': 'minkowski'}. Best is trial 0 with value: 0.85.
Processing svc_smote_net_impact_onehot:  86%|████████▋ | 19/22 [00:58<00:03,  1.22s/it]                 [I 2024-03-09 12:53:59,904] A new study created in memory with name: no-name-3239c4a2-fdda-420d-a404-a1a686c9cd2e
[I 2024-03-09 12:54:01,093] Trial 0 finished with value: 0.7692307692307692 and parameters: {'C': 0.08375336518815976, 'kernel': 'poly', 'gamma': 84.86683055654785, 'degree': 4, 'coef0': 0.6849049522363915}. Best is trial 0 with value: 0.7692307692307692.