This notebook is used to get the Experiment results for the dropclass-publication

# Prerequisites

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

## Main df

In [2]:
# Import data
df_main = pd.read_excel('../data/df_main.xlsx', index_col=0).reset_index(drop=True)
## Drop unused columns
# drop_columns = ['voltage', 'long_impulse_duration', 'long_impulse_dur_binary']
# df_main = df_main.drop(drop_columns, axis=1)
display(df_main.head())
df_main.info()

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,roughness,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
0,3,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
1,4,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
2,5,1,1,0,0,0,105.0,10,0.8,0,...,0.10,low,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
3,7,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small
4,8,0,1,0,0,0,105.0,10,0.8,0,...,0.04,low,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 28 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   test                             372 non-null    int64
 1   one_drop                         372 non-null    int64
 2   splashing                        372 non-null    int64
 3   breaking_up                      372 non-null    int64
 4   net_impact                       372 non-null    int64
 5   rebound                          372 non-null    int64
 6   voltage                          372 non-null    float64
 7   long_impulse_duration            372 non-null    int64
 8   height                           372 non-null    float64
 9   inclination                      372 non-null    int64
 10  droplet_diameter                 372 non-null    float64
 11  liquid_density                   372 non-null    int64
 12  surface_tension                  372 non-null    float64
 13  viscosity                        372 non-null    float64
 14  particle_mean_diameter           372 non-null    float64
 15  particle_liquid_density_ratio    372 non-null    float64
 16  volume_fraction                  372 non-null    float64
 17  wettability                      372 non-null    object
 18  roughness                        372 non-null    float64
 19  long_impulse_dur_binary          372 non-null    object
 20  roughness_binary                 372 non-null    int64
 21  volume_fraction_binary           372 non-null    int64
 22  velocity                         372 non-null    float64
 23  Re                               372 non-null    float64
 24  We                               372 non-null    float64
 25  We_Re                            372 non-null    float64
 26  particle_droplet_diameter_ratio  372 non-null    float64
 27  particle_diameter_cat            372 non-null    object
dtypes: float64(14), int64(11), object(3)
memory usage: 81.5+ KB

In [3]:
label_name = ['net_impact', 'splashing', 'breaking_up', 'rebound']

class_count_dict = {}

for label in label_name:
    class_count_dict[label] = df_main[df_main[label]==1].shape[0]

class_count_s = pd.Series(class_count_dict)
class_count_s

net_impact     121
splashing      174
breaking_up    101
rebound         99
dtype: int64

**Labels description:**
- **splashing**: when *'Number of detached small droplets during Spreading'=='many' (more than 5)*;
- **breaking_up**: combines clear "breaking_up" during receding *'Droplet Receding'==2*, as well as the Spreading detaching *0<'Number of detached small droplets during spreading'<=5*;
- **rebound**: combines all rebound types (partial and total, *'Rebound'>0*), as well as the central jet ejection *'Rim merging or Central jet ejecting'==2*
- **net_impact**: when there is 
    - **no Splashing** (no small droplets detached during spreading, *'Number of detached small droplets during Spreading'==0*), 
    - **no Breaking up** (*'Droplet Receding'<2* [equivalent is *'Number of detached small droplets during Receding or Rim merging' == 0*])
    - **no Rebound** (*'Rebound' == 0*)

**Total count of clear experiments is *372***

## Suspension Data Labeling Edited. For the classes reconfiguration

In [4]:
df_labels = pd.read_excel('../data/Suspension Data Labeling Edited.xlsx', index_col=0)
df_labels = df_labels.drop(index=0)
# Keep only used 372 tests (without draft substrated and liquids)
df_labels = df_labels[df_labels['Test #'].isin(df_main.test.values)]
df_labels = df_labels.drop('Comments', axis=1)
df_labels = df_labels.rename({'Test #': 'test'}, axis=1)
df_labels['test'] = df_labels['test'].astype(int)
df_labels = df_labels.reset_index(drop=True)
display(df_labels)
display(df_labels.info())
df_labels.columns

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
0,3,1,many,0,0,0,0,0,1
1,4,1,many,0,0,0,0,0,1
2,5,1,many,0,0,0,0,0,1
3,7,0,many,1,0,0,0,0,2
4,8,0,many,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...
367,391,0,0,1,2,0,2,0,0
368,392,1,3,1,1,0,0,0,1
369,393,1,2,1,1,0,0,0,3
370,394,1,0,1,1,1,0,0,2
371,395,1,0,1,2,0,2,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 9 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   test                                                              372 non-null    int64
 1   Total number of dropped drops                                     372 non-null    object
 2   Number of detached small droplets during Spreading                372 non-null    object
 3   Droplet Receding                                                  372 non-null    object
 4   Rim merging or Central jet ejecting                               372 non-null    object
 5   Number of detached small droplets during Receding or Rim merging  372 non-null    object
 6   Rebound                                                           372 non-null    object
 7   Number of detached droplets during Rebound                        372 non-null    object
 8   Final droplets count                                              372 non-null    object
dtypes: int64(1), object(8)
memory usage: 26.3+ KB

None

Index(['test', 'Total number of dropped drops',
       'Number of detached small droplets during Spreading',
       'Droplet Receding', 'Rim merging or Central jet ejecting',
       'Number of detached small droplets during Receding or Rim merging',
       'Rebound', 'Number of detached droplets during Rebound',
       'Final droplets count'],
      dtype='object')


| Parameter name | Description | Possible values |
| --- | --- | --- |
| Total number of dropped drops | The total number of drops that fell from above | 1, 2 |
| Number of detached small droplets during *spreading* | The number of small droplets that flew out of the lamella drops in the process of spreading | 0, 1, .., 5, many |
| Droplet Receding | Presence (1,2), absence — 0 of a visible drop shrinkage, and an increase in the drop height after reaching the maximum spot diameter. 1 — the usual reduction of the main drop, 2 — the destruction of the main drop in the process of reduction | 0, 1, 2 |
| Rim merging or Central jet ejecting | The presence (1,2), absence — 0 of an explicit rim merging at the end of the shrinkage of the drop (1) and/or the reverse vertical jet (2) (against gravity) | 0, 1, 2 |
| Number of detached small droplets during *Receding or Rim merging* | The number of small droplets separating from the rim of the main drop (rim) and remaining on the substrate during the shrinkage of the drop (receding). Drops do not separate — 0, several drops, many drops — many | 0, 1, .., 5, many |
| Rebound | Presence (1,2), absence — 0 of a drop rebound after the formation of a reverse vertical jet (central jet ejecting). Partial rebound — 1, total rebound - 2 | 0, 1, 2 |
| Number of detached droplets during *Rebound* | The number of droplets separating from the reverse vertical jet (central jet) | 0, 1, .., 5, many |
| Final droplets count | The total number of droplets on the substrate, clearly separated from each other | 1, .., 5, many |

# Classes Research

## Break up dividing. Create 'breaking_up_receding' and 'splashing_semi'

How many receding break up tests, when *'Number of detached small droplets during Receding or Rim merging' > 0*

In [5]:
index_receding_break_up = df_labels[df_labels['Number of detached small droplets during Receding or Rim merging'] != 0].index
receding_break_up_count = index_receding_break_up.shape[0]
print(f'Receding break_up tests count: {receding_break_up_count}')

Receding break_up tests count: 60

Let us check, that not_receding_break_up cases are happends only if number of detached small droplets during spreading == 'few'

In [6]:
# Not receding break up, when label is 'breaking_up', but no detached small droplets during Receding or Rim merging
index_not_receding_break_up = df_main[(~df_main.index.isin(index_receding_break_up))&(df_main['breaking_up']==1)].index
not_receding_break_up_count = index_not_receding_break_up.shape[0]
print(f'Not receding break_up tests count: {not_receding_break_up_count}')

Not receding break_up tests count: 41

In [7]:
print('Not receding break up labels')
not_receding_break_up_labels = df_labels.loc[index_not_receding_break_up]
display(not_receding_break_up_labels['Number of detached small droplets during Spreading'].value_counts())
display(not_receding_break_up_labels['Number of detached small droplets during Receding or Rim merging'].value_counts())
display(not_receding_break_up_labels)

Not receding break up labels

Number of detached small droplets during Spreading
2    15
1     9
3     8
4     5
5     4
Name: count, dtype: int64

Number of detached small droplets during Receding or Rim merging
0    41
Name: count, dtype: int64

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
17,26,1,2,0,0,0,0,0,1
18,27,0,5,0,0,0,0,0,1
38,51,0,2,0,0,0,0,0,1
46,59,1,1,1,1,0,0,0,1
47,60,1,1,1,0,0,0,0,1
58,74,1,1,0,0,0,0,0,1
60,78,1,2,1,0,0,0,0,2
63,81,0,5,0,0,0,0,0,2
78,100,1,3,1,1,0,0,0,1
86,109,1,1,1,1,0,0,0,1
87,110,1,2,1,1,0,0,0,3
89,112,1,2,1,1,0,0,0,3
95,118,1,3,0,0,0,0,0,1
96,119,0,3,0,0,0,0,0,1
102,125,1,2,0,0,0,0,0,1
122,145,0,1,1,1,0,0,0,2
123,146,1,3,0,0,0,0,0,5
127,150,1,3,1,1,0,0,0,1
142,165,1,4,1,1,0,0,0,1
146,169,1,4,1,2,0,1,0,2
149,172,1,2,1,1,0,0,0,1
179,202,1,1,1,1,0,0,0,1
184,207,1,4,1,0,0,0,0,1
193,216,1,4,1,1,0,0,0,4
196,219,0,4,1,0,0,0,0,4
197,220,1,5,0,0,0,0,0,1
243,266,1,3,1,1,0,0,0,3
251,274,1,1,1,2,0,1,0,1
257,281,0,2,1,2,0,0,0,1
263,287,0,2,1,1,0,0,0,3
274,298,1,1,1,2,0,1,1,1
283,307,1,2,1,1,0,0,0,2
296,320,0,2,1,1,0,0,0,2
299,323,0,5,1,1,0,0,0,4
301,325,0,2,1,1,0,0,0,3
319,343,1,1,1,1,0,0,0,1
323,347,1,3,1,1,0,0,0,3
331,355,1,2,1,1,0,0,0,1
365,389,1,2,1,1,0,0,0,3
368,392,1,3,1,1,0,0,0,1
369,393,1,2,1,1,0,0,0,3

Thus, only 'few small droplets during Spreading' cases are not in receding break_up

**Thus, let us create a receding break up** instead of *break up*

In [8]:
df_main['breaking_up_receding'] = 0
df_main.loc[index_receding_break_up, 'breaking_up_receding'] = 1
df_main['breaking_up_receding'].value_counts()

breaking_up_receding
0    312
1     60
Name: count, dtype: int64

Now, let us check classes of tests with a few count of 'Number of detached small droplets during Spreading'

In [9]:
index_spreading_few_detached = df_labels[df_labels['Number of detached small droplets during Spreading'].isin(list(range(1,6)))].index
# Show tests with few drops detached during Spreading
df_main.iloc[index_spreading_few_detached]

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,long_impulse_dur_binary,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat,breaking_up_receding
9,17,0,0,1,0,0,103.0,21,0.8,0,...,high,0,1,3.961141,11559.676628,650.561372,264.472523,0.045305,medium,1
10,18,0,0,1,0,0,103.0,18,0.8,0,...,high,0,1,3.961141,11559.676628,650.561372,264.472523,0.045305,medium,1
17,26,1,0,1,0,0,108.0,10,0.8,0,...,low,0,1,3.961141,11426.368989,643.059016,262.181762,0.045833,medium,0
18,27,0,0,1,0,0,108.0,10,0.8,0,...,low,0,1,3.961141,11883.423749,668.781377,270.008528,0.044071,medium,0
38,51,0,0,1,0,0,106.5,12,0.8,0,...,low,0,1,3.961141,677.852440,913.477171,154.217138,0.012388,small,0
42,55,0,0,1,0,1,111.0,12,0.8,0,...,low,0,1,3.961141,631.313317,850.760828,146.205928,0.013301,small,1
46,59,1,0,1,0,0,107.0,12,0.8,0,...,low,0,1,3.961141,693.028241,933.928153,156.799425,0.012117,small,0
47,60,1,0,1,0,0,107.0,12,0.8,0,...,low,0,1,3.961141,693.028241,933.928153,156.799425,0.012117,small,0
58,74,1,0,1,0,0,101.0,21,0.8,0,...,high,1,1,3.961141,560.088225,754.777555,133.651427,0.014993,small,0
60,78,1,0,1,0,0,108.0,15,0.8,0,...,high,0,1,3.961141,687.969640,927.111159,155.940249,0.040441,medium,0
63,81,0,0,1,0,0,108.0,15,0.8,0,...,high,1,1,3.961141,653.571158,880.755601,150.055157,0.042570,medium,0
78,100,1,0,1,0,0,101.0,15,0.8,0,...,high,0,0,3.961141,627.266437,845.307233,145.502450,0.013387,small,0
86,109,1,0,1,0,0,110.0,15,0.8,0,...,high,0,0,3.961141,683.922760,921.657564,155.251770,0.012278,small,0
87,110,1,0,1,0,0,110.0,15,0.8,0,...,high,0,0,3.961141,671.782119,905.296779,153.180188,0.012500,small,0
89,112,1,0,1,0,0,110.0,15,0.8,0,...,high,0,0,3.961141,620.184396,835.763442,144.268625,0.013540,small,0
95,118,1,0,1,0,0,114.0,10,0.8,0,...,low,0,0,3.961141,12949.884855,728.800219,287.985568,0.040441,medium,0
96,119,0,0,1,0,0,114.0,10,0.8,0,...,low,0,0,3.961141,12607.093785,709.508448,282.249078,0.041541,medium,0
102,125,1,0,1,0,0,112.0,10,0.8,0,...,low,0,0,3.961141,13064.148545,735.230809,289.889260,0.040087,medium,0
122,145,0,0,1,0,0,106.0,18,0.8,0,...,high,0,0,3.961141,611.078916,823.492853,142.677090,0.091060,large,0
123,146,1,0,1,0,0,109.0,15,0.8,0,...,high,0,0,3.961141,685.946200,924.384361,155.596136,0.081121,large,0
127,150,1,0,1,0,0,109.0,15,0.8,0,...,high,0,0,3.961141,683.922760,921.657564,155.251770,0.081361,large,0
142,165,1,0,1,0,0,110.0,15,0.8,0,...,high,0,0,3.961141,669.758679,902.569981,152.834018,0.041541,medium,0
146,169,1,0,1,0,1,110.0,15,0.8,0,...,high,0,0,3.961141,685.946200,924.384361,155.596136,0.040560,medium,0
149,172,1,0,1,0,0,110.0,15,0.8,0,...,high,0,0,3.961141,667.735239,899.843184,152.487586,0.041667,medium,0
179,202,1,0,1,0,0,100.0,15,0.8,0,...,high,0,1,3.961141,554.422593,747.142522,132.636165,0.015146,small,0
184,207,1,0,1,0,0,100.0,15,0.8,0,...,high,0,1,3.961141,665.711799,897.116386,152.140892,0.012614,small,0
193,216,1,0,1,0,0,108.0,15,0.8,0,...,high,0,1,3.961141,665.711799,897.116386,152.140892,0.083587,large,0
196,219,0,0,1,0,0,105.0,15,0.8,0,...,high,0,1,3.961141,643.453958,867.121613,148.309638,0.086478,large,0
197,220,1,0,1,0,0,105.0,15,0.8,0,...,high,0,1,3.961141,643.453958,867.121613,148.309638,0.086478,large,0
243,266,1,0,1,0,0,101.0,15,0.8,20,...,high,0,1,3.961141,598.938275,807.132068,140.545783,0.014020,small,0
251,274,1,0,1,0,1,101.0,15,0.8,20,...,high,0,1,3.961141,669.758679,902.569981,152.834018,0.012538,small,0
257,281,0,0,1,0,1,101.0,15,0.8,20,...,high,0,1,3.961141,661.440092,891.359813,151.408115,0.012695,small,0
263,287,0,0,1,0,0,106.0,15,0.8,20,...,high,0,1,3.961141,694.545821,935.973251,157.056872,0.080117,large,0
274,298,1,0,1,0,1,101.0,12,0.8,45,...,low,0,1,3.961141,600.961715,809.858865,140.901745,0.013973,small,0
283,307,1,0,1,0,0,105.0,12,0.8,45,...,low,0,1,3.961141,669.758679,902.569981,152.834018,0.012538,small,0
296,320,0,0,1,0,0,110.0,12,0.2,45,...,low,0,1,1.980571,365.230941,246.093477,68.579125,0.076177,large,0
298,322,0,0,1,0,0,109.0,12,0.2,45,...,low,0,1,1.980571,365.230941,246.093477,68.579125,0.076177,large,1
299,323,0,0,1,0,0,109.0,12,0.2,45,...,low,0,1,1.980571,357.137181,240.639882,67.436119,0.077904,large,0
301,325,0,0,1,0,0,108.0,12,0.2,45,...,low,0,1,1.980571,268.105816,180.650336,54.387105,0.103774,large,0
319,343,1,0,1,0,0,108.0,12,1.8,0,...,low,0,1,5.941712,937.864495,1895.805980,240.952795,0.088997,large,0
323,347,1,0,1,0,0,109.0,12,1.8,0,...,low,0,1,5.941712,959.110616,1938.753041,245.035168,0.087025,large,0
331,355,1,0,1,0,0,102.0,12,1.8,0,...,low,0,1,5.941712,837.704209,1693.341264,221.383332,0.015036,small,0
365,389,1,0,1,0,0,106.0,12,0.2,20,...,low,0,1,1.980571,333.867620,224.960796,64.113132,0.083333,large,0
368,392,1,0,1,0,0,109.0,12,0.2,20,...,low,0,1,1.980571,333.867620,224.960796,64.113132,0.083333,large,0
369,393,1,0,1,0,0,107.0,12,0.2,20,...,low,0,1,1.980571,330.832459,222.915698,63.675499,0.084098,large,0

Let us introduce 'semi-splashing' as class for the few detached droplets

In [10]:
df_main['splashing_semi'] = 0
df_main.loc[index_spreading_few_detached, 'splashing_semi'] = 1
df_main['splashing_semi'].value_counts()

splashing_semi
0    327
1     45
Name: count, dtype: int64

## Rebound dividing. Create 'rebound_total', 'rebound_true', 'jet_ejection'

In [11]:
df_main['rebound'].value_counts()

rebound
0    273
1     99
Name: count, dtype: int64

In [12]:
index_rebound_total = df_labels[df_labels['Rebound'] == 2].index
print(f'Real total rebound cases count: {index_rebound_total.shape[0]}')
display(df_labels.loc[index_rebound_total])

Real total rebound cases count: 38

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
69,90,0,many,2,2,many,2,0,many
71,92,0,many,2,2,many,2,0,many
75,96,1,many,2,2,many,2,0,many
99,122,1,many,2,2,many,2,0,many
100,123,0,many,2,2,many,2,0,many
101,124,1,many,2,2,many,2,0,many
110,133,1,many,1,2,many,2,0,many
174,197,1,many,2,2,many,2,0,many
176,199,0,many,2,2,many,2,0,many
177,200,0,many,2,2,many,2,0,many
201,224,0,many,1,2,many,2,3,many
204,227,0,many,1,2,many,2,2,many
206,229,0,many,1,2,many,2,0,many
207,230,0,many,1,2,many,2,0,many
232,255,1,many,1,2,many,2,0,many
245,268,0,many,2,2,many,2,0,many
247,270,1,many,2,2,many,2,0,many
248,271,1,many,2,2,many,2,0,many
265,289,1,many,2,2,many,2,0,0
268,292,1,many,2,2,many,2,0,0
272,296,1,many,2,2,many,2,0,1
278,302,1,many,2,2,many,2,2,1
284,308,1,0,1,2,0,2,2,0
297,321,1,0,1,2,0,2,0,0
305,329,1,0,1,2,0,2,0,0
306,330,0,0,1,2,0,2,2,0
310,334,1,0,1,2,0,2,3,0
316,340,1,0,1,2,0,2,1,0
339,363,1,many,2,2,many,2,0,many
345,369,0,many,2,2,many,2,0,many
349,373,0,0,1,2,0,2,1,1
350,374,1,0,1,2,0,2,1,1
352,376,1,0,1,2,0,2,1,1
357,381,1,0,1,2,0,2,0,1
361,385,1,0,1,2,0,2,1,1
366,390,0,0,1,2,0,2,0,0
367,391,0,0,1,2,0,2,0,0
371,395,1,0,1,2,0,2,0,0

According to videos of tests, when Rebound==2, but Number of detached droplets during Rebound == 0 - there is no mistake, so let us include 'rebound_total' for the analysis

In [13]:
df_main['rebound_total'] = 0
df_main.loc[index_rebound_total, 'rebound_total'] = 1
df_main['rebound_total'].value_counts()

rebound_total
0    334
1     38
Name: count, dtype: int64

Let us consider partial rebound cases

In [14]:
index_rebound_partial = df_labels[(df_labels['Rebound'] == 1)&(df_labels['Number of detached droplets during Rebound']>0)].index
print(f'Number of partial rebound cases {index_rebound_partial.shape[0]}')
df_labels.loc[index_rebound_partial]

Number of partial rebound cases 6

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
14,23,0,many,2,2,many,1,1,many
33,45,1,many,1,2,many,1,1,many
274,298,1,1,1,2,0,1,1,1
282,306,1,0,1,2,0,1,1,1
291,315,1,many,1,2,0,1,3,1
294,318,0,many,1,2,0,1,2,1

Only 6 cases has real partial rebound, let us combine total and partial rebound -> 'rebound_true'

In [15]:
index_rebound_true = list(set(index_rebound_total).union(set(index_rebound_partial)))

df_main['rebound_true'] = 0
df_main.loc[index_rebound_true, 'rebound_true'] = 1
df_main['rebound_true'].value_counts()

rebound_true
0    328
1     44
Name: count, dtype: int64

Now, let us check not true rebound

In [16]:
index_not_rebound = df_main[(df_main['rebound_true']==0)&(df_main['rebound']==1)].index
print(f'Number of not rebound cases: {index_not_rebound.shape[0]}')
display(df_main.loc[index_not_rebound])
display(df_labels.loc[index_not_rebound])
display(df_labels.loc[index_not_rebound]['Rim merging or Central jet ejecting'].value_counts())

Number of not rebound cases: 55

,test,one_drop,splashing,breaking_up,net_impact,rebound,voltage,long_impulse_duration,height,inclination,...,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat,breaking_up_receding,splashing_semi,rebound_total,rebound_true
12,20,0,1,1,0,1,103.0,15,0.8,0,...,3.961141,11864.379801,667.709612,269.683934,0.044141,medium,1,0,0,0
13,22,0,1,1,0,1,110.5,12,0.8,0,...,3.961141,12340.478509,694.503738,277.760377,0.042438,medium,1,0,0,0
23,34,1,1,1,0,1,105.0,12,0.8,0,...,3.961141,6615.685566,753.458811,247.556009,0.012848,small,1,0,0,0
24,35,0,1,1,0,1,105.0,12,0.8,0,...,3.961141,6390.383581,727.799223,241.205677,0.013301,small,1,0,0,0
32,44,1,1,0,0,1,120.0,12,0.8,0,...,3.961141,2172.648606,858.125870,199.996719,0.012519,small,0,0,0,0
42,55,0,0,1,0,1,111.0,12,0.8,0,...,3.961141,631.313317,850.760828,146.205928,0.013301,small,1,1,0,0
43,56,0,0,1,0,1,106.0,12,0.8,0,...,3.961141,677.852440,913.477171,154.217138,0.012388,small,1,0,0,0
53,69,1,0,0,0,1,108.0,15,0.8,0,...,3.961141,682.304008,919.476126,154.976093,0.012307,small,0,0,0,0
54,70,1,0,1,0,1,103.5,21,0.8,0,...,3.961141,682.304008,919.476126,154.976093,0.012307,small,1,0,0,0
62,80,1,1,1,0,1,108.0,15,0.8,0,...,3.961141,661.664919,891.662791,151.446712,0.042049,medium,1,0,0,0
65,83,1,1,0,0,1,106.0,15,0.8,0,...,3.961141,651.547718,878.028803,149.706597,0.042702,medium,0,0,0,0
77,99,0,1,1,0,1,103.5,15,0.8,0,...,3.961141,645.477398,869.848411,148.659288,0.013009,small,1,0,0,0
79,101,0,1,1,0,1,101.0,15,0.8,0,...,3.961141,618.498196,833.491110,143.974340,0.013577,small,1,0,0,0
80,102,0,1,1,0,1,100.0,15,0.8,0,...,3.961141,592.867955,798.951675,139.476085,0.014164,small,1,0,0,0
82,104,0,1,0,0,1,103.5,15,0.8,0,...,3.961141,685.946200,924.384361,155.596136,0.012242,small,0,0,0,0
84,106,1,1,0,0,1,103.5,15,0.8,0,...,3.961141,641.430518,864.394816,147.959713,0.013091,small,0,0,0,0
88,111,1,1,0,0,1,110.0,15,0.8,0,...,3.961141,620.184396,835.763442,144.268625,0.013540,small,0,0,0,0
108,131,1,1,1,0,1,106.0,12,0.8,0,...,3.961141,6185.563594,704.472325,235.383918,0.013742,small,1,0,0,0
116,139,1,1,0,0,1,108.0,12,0.8,0,...,3.961141,2051.399740,810.236493,191.566019,0.013259,small,0,0,0,0
119,142,1,1,1,0,1,108.0,12,0.8,0,...,3.961141,2249.658021,888.542096,205.290159,0.012090,small,1,0,0,0
126,149,1,1,1,0,1,109.0,15,0.8,0,...,3.961141,659.641479,888.935993,151.099224,0.084356,large,1,0,0,0
128,151,1,1,0,0,1,109.0,15,0.8,0,...,3.961141,672.456600,906.205711,153.295520,0.082748,large,0,0,0,0
135,158,0,1,0,0,1,104.0,15,0.8,0,...,3.961141,672.716015,906.555300,153.339871,0.012483,small,0,0,0,0
136,159,0,1,1,0,1,104.0,15,0.8,0,...,3.961141,629.289877,848.034031,145.854330,0.013344,small,1,0,0,0
137,160,0,1,0,0,1,103.0,15,0.8,0,...,3.961141,584.099714,787.135552,137.926118,0.014376,small,0,0,0,0
140,163,0,1,0,0,1,101.0,15,0.8,0,...,3.961141,670.770399,903.933380,153.007135,0.012519,small,0,0,0,0
141,164,1,1,1,0,1,101.0,15,0.8,0,...,3.961141,677.852440,913.477171,154.217138,0.012388,small,1,0,0,0
146,169,1,0,1,0,1,110.0,15,0.8,0,...,3.961141,685.946200,924.384361,155.596136,0.040560,medium,0,1,0,0
147,170,1,1,0,0,1,110.0,15,0.8,0,...,3.961141,589.832795,794.861479,138.940211,0.047170,medium,0,0,0,0
154,177,1,1,0,0,1,106.0,15,0.8,0,...,3.961141,584.099714,787.135552,137.926118,0.014376,small,0,0,0,0
155,178,0,1,0,0,1,106.0,15,0.8,0,...,3.961141,692.016521,932.564754,156.627716,0.012135,small,0,0,0,0
156,179,1,1,0,0,1,104.0,15,0.8,0,...,3.961141,635.360197,856.214423,146.908279,0.013217,small,0,0,0,0
158,181,0,1,0,0,1,104.0,15,0.8,0,...,3.961141,661.664919,891.662791,151.446712,0.012691,small,0,0,0,0
172,195,0,1,1,0,1,110.0,12,0.8,0,...,3.961141,12530.917992,705.221388,280.969035,0.012614,small,1,0,0,0
187,210,0,1,0,0,1,105.0,15,0.8,0,...,3.961141,633.336757,853.487626,146.557243,0.013259,small,0,0,0,0
191,214,1,1,1,0,1,105.0,15,0.8,0,...,3.961141,663.688359,894.389588,151.793934,0.012652,small,1,0,0,0
194,217,1,1,0,0,1,106.0,15,0.8,0,...,3.961141,663.688359,894.389588,151.793934,0.083841,large,0,0,0,0
209,232,0,0,0,0,1,103.0,12,0.2,0,...,1.980571,294.410537,198.374520,58.341996,0.014261,small,0,0,0,0
212,235,1,0,0,0,1,102.0,12,0.2,0,...,1.980571,293.398817,197.692821,58.191565,0.014310,small,0,0,0,0
215,238,1,0,0,0,1,102.0,15,0.2,0,...,1.980571,292.387097,197.011121,58.041005,0.014360,small,0,0,0,0
219,242,0,0,0,0,1,102.0,15,0.2,0,...,1.980571,294.073297,198.147287,58.291867,0.014278,small,0,0,0,0
222,245,1,0,0,0,1,100.0,15,0.2,0,...,1.980571,268.105816,180.650336,54.387105,0.015660,small,0,0,0,0
224,247,0,0,0,0,1,107.0,15,0.2,0,...,1.980571,344.996540,232.459489,65.709373,0.080645,large,0,0,0,0
228,251,1,0,0,0,1,107.0,15,0.2,0,...,1.980571,274.513376,184.967765,55.359085,0.101351,large,0,0,0,0
239,262,0,1,1,0,1,103.0,15,0.8,20,...,3.961141,592.867955,798.951675,139.476085,0.014164,small,1,0,0,0
240,263,1,1,1,0,1,101.0,15,0.8,20,...,3.961141,598.938275,807.132068,140.545783,0.014020,small,1,0,0,0
251,274,1,0,1,0,1,101.0,15,0.8,20,...,3.961141,669.758679,902.569981,152.834018,0.012538,small,0,1,0,0
257,281,0,0,1,0,1,101.0,15,0.8,20,...,3.961141,661.440092,891.359813,151.408115,0.012695,small,0,1,0,0
259,283,1,1,0,0,1,106.5,15,0.8,20,...,3.961141,698.086841,940.745146,157.657036,0.079710,large,0,0,0,0
262,286,1,1,0,0,1,106.0,15,0.8,20,...,3.961141,626.254717,843.943834,145.326403,0.088853,large,0,0,0,0
320,344,1,1,0,0,1,108.0,12,1.8,0,...,5.941712,940.899655,1901.941274,241.537395,0.088710,large,0,0,0,0
324,348,1,1,0,0,1,109.0,12,1.8,0,...,5.941712,1007.673179,2036.917752,254.282616,0.082831,large,0,0,0,0
326,350,1,1,0,0,1,107.0,12,1.8,0,...,5.941712,934.829335,1889.670685,240.367721,0.013474,small,0,0,0,0
330,354,1,1,0,0,1,107.0,12,1.8,0,...,5.941712,959.110616,1938.753041,245.035168,0.013133,small,0,0,0,0
340,364,1,1,1,0,1,112.0,12,1.8,0,...,5.941712,15996.916585,1350.423934,413.279757,0.014821,small,1,0,0,0

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
12,20,0,many,2,2,many,1,0,many
13,22,0,many,2,2,many,1,0,many
23,34,1,many,2,2,many,1,0,many
24,35,0,many,2,2,many,1,0,many
32,44,1,many,1,2,0,1,0,many
42,55,0,1,1,2,3,1,0,3
43,56,0,0,1,2,2,1,0,2
53,69,1,0,1,2,0,1,0,1
54,70,1,0,1,2,1,1,0,1
62,80,1,many,1,2,many,1,0,many
65,83,1,many,1,2,0,0,0,4
77,99,0,many,1,2,many,1,0,many
79,101,0,many,1,2,many,1,0,many
80,102,0,many,1,2,3,1,0,many
82,104,0,many,1,2,0,1,0,5
84,106,1,many,1,2,0,1,0,many
88,111,1,many,1,2,0,1,0,many
108,131,1,many,1,2,many,1,0,many
116,139,1,many,1,2,0,1,0,many
119,142,1,many,1,2,many,1,0,many
126,149,1,many,1,2,many,1,0,many
128,151,1,many,1,2,0,1,0,many
135,158,0,many,1,2,0,1,0,many
136,159,0,many,1,2,many,1,0,3
137,160,0,many,1,2,0,1,0,many
140,163,0,many,1,2,0,1,0,many
141,164,1,many,1,2,many,1,0,many
146,169,1,4,1,2,0,1,0,2
147,170,1,many,1,2,0,1,0,many
154,177,1,many,1,2,0,1,0,3
155,178,0,many,1,2,0,1,0,3
156,179,1,many,1,2,0,1,0,6
158,181,0,many,1,2,0,1,0,5
172,195,0,many,1,2,many,1,0,many
187,210,0,many,1,2,0,1,0,many
191,214,1,many,1,2,many,1,0,many
194,217,1,many,1,2,0,0,0,many
209,232,0,0,1,2,0,1,0,1
212,235,1,0,1,2,0,1,0,1
215,238,1,0,1,2,0,1,0,1
219,242,0,0,1,2,0,1,0,1
222,245,1,0,1,2,0,1,0,1
224,247,0,0,1,2,0,1,0,1
228,251,1,0,1,2,0,1,0,1
239,262,0,many,1,2,many,1,0,many
240,263,1,many,1,2,many,1,0,many
251,274,1,1,1,2,0,1,0,1
257,281,0,2,1,2,0,0,0,1
259,283,1,many,1,2,0,1,0,1
262,286,1,many,1,2,0,1,0,3
320,344,1,many,1,2,0,1,0,many
324,348,1,many,1,2,0,1,0,many
326,350,1,many,1,2,0,0,0,many
330,354,1,many,1,2,0,1,0,many
340,364,1,many,1,2,1,1,0,many

Rim merging or Central jet ejecting
2    55
Name: count, dtype: int64

We see, that all not rebound cases has the jet ejection

Now, let us create label - jet_ejection

In [17]:
df_main['jet_ejection'] = 0
df_main.loc[index_not_rebound, 'jet_ejection'] = 1
df_main['jet_ejection'].value_counts()

jet_ejection
0    317
1     55
Name: count, dtype: int64

## Splashing

This class is the same, since it has simple condition: 'Number of detached droplets during spreading' > 5. Total count = 174

In [18]:
index_splashing = df_main[df_main['splashing'] == 1].index

df_labels.loc[index_splashing, 'Number of detached small droplets during Spreading'].value_counts()

Number of detached small droplets during Spreading
many    173
7         1
Name: count, dtype: int64

## Net impact

Let us check, that net impact occurs only when other new labels are 0

In [19]:
df_main[(df_main['splashing'] == 0) & (df_main['splashing_semi'] == 0) & (df_main['rebound_true'] == 0) & (df_main['breaking_up_receding'] == 0) & (df_main['jet_ejection'] == 0)]['net_impact'].value_counts()

net_impact
1    121
Name: count, dtype: int64

The number is the same as in the original classification

## Save result

Now we have edited main dataset with new labels and old classes. Let us save it

In [20]:
# df_main.to_excel('../data/df_main_edited.xlsx', index=False)

# Experiments Research

In [ ]:
## Drop unused columns
drop_columns = ['voltage', 'long_impulse_duration', 'long_impulse_dur_binary']
df_main = df_main.drop(drop_columns, axis=1)