This notebook is used to get the Experiment results for the dropclass-publication

# Prerequisites

In [1]:
# Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('darkgrid')

## Main df

In [2]:
# Import data
df = pd.read_excel('../data/df_main.xlsx', index_col=0).reset_index(drop=True)
# Drop unused columns
drop_columns = ['voltage', 'long_impulse_duration', 'long_impulse_dur_binary']
df = df.drop(drop_columns, axis=1)
display(df.head())
df.info()

,test,one_drop,splashing,breaking_up,net_impact,rebound,height,inclination,droplet_diameter,liquid_density,...,wettability,roughness,roughness_binary,volume_fraction_binary,velocity,Re,We,We_Re,particle_droplet_diameter_ratio,particle_diameter_cat
0,3,1,1,0,0,0,0.8,0,0.00312,820,...,lyophilic,0.10,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
1,4,1,1,0,0,0,0.8,0,0.00312,820,...,lyophilic,0.10,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
2,5,1,1,0,0,0,0.8,0,0.00312,820,...,lyophilic,0.10,0,1,3.961141,1492.516020,1492.302356,240.108847,0.013301,small
3,7,0,1,0,0,0,0.8,0,0.00300,820,...,neutral,0.04,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small
4,8,0,1,0,0,0,0.8,0,0.00300,820,...,neutral,0.04,0,1,3.961141,1435.111557,1434.906112,233.148786,0.013833,small

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 25 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   test                             372 non-null    int64
 1   one_drop                         372 non-null    int64
 2   splashing                        372 non-null    int64
 3   breaking_up                      372 non-null    int64
 4   net_impact                       372 non-null    int64
 5   rebound                          372 non-null    int64
 6   height                           372 non-null    float64
 7   inclination                      372 non-null    int64
 8   droplet_diameter                 372 non-null    float64
 9   liquid_density                   372 non-null    int64
 10  surface_tension                  372 non-null    float64
 11  viscosity                        372 non-null    float64
 12  particle_mean_diameter           372 non-null    float64
 13  particle_liquid_density_ratio    372 non-null    float64
 14  volume_fraction                  372 non-null    float64
 15  wettability                      372 non-null    object
 16  roughness                        372 non-null    float64
 17  roughness_binary                 372 non-null    int64
 18  volume_fraction_binary           372 non-null    int64
 19  velocity                         372 non-null    float64
 20  Re                               372 non-null    float64
 21  We                               372 non-null    float64
 22  We_Re                            372 non-null    float64
 23  particle_droplet_diameter_ratio  372 non-null    float64
 24  particle_diameter_cat            372 non-null    object
dtypes: float64(13), int64(10), object(2)
memory usage: 72.8+ KB

In [3]:
label_name = ['net_impact', 'splashing', 'breaking_up', 'rebound']

class_count_dict = {}

for label in label_name:
    class_count_dict[label] = df[df[label]==1].shape[0]

class_count_s = pd.Series(class_count_dict)
class_count_s

net_impact     121
splashing      174
breaking_up    101
rebound         99
dtype: int64

**Labels description:**
- **splashing**: when *'Number of detached small droplets during Spreading'=='many' (more than 5)*;
- **breaking_up**: combines clear "breaking_up" during receding *'Droplet Receding'==2*, as well as the Spreading detaching *0<'Number of detached small droplets during spreading'<=5*;
- **rebound**: combines all rebound types (partial and total, *'Rebound'>0*), as well as the central jet ejection *'Rim merging or Central jet ejecting'==2*
- **net_impact**: when there is 
    - **no Splashing** (no small droplets detached during spreading, *'Number of detached small droplets during Spreading'==0*), 
    - **no Breaking up** (*'Droplet Receding'<2* [equivalent is *'Number of detached small droplets during Receding or Rim merging' == 0*])
    - **no Rebound** (*'Rebound' == 0*)

**Total count of clear experiments is *372***

## Suspension Data Labeling Edited. Only for additional, support researches

In [4]:
df_labels = pd.read_excel('../data/Suspension Data Labeling Edited.xlsx', index_col=0)
df_labels = df_labels.drop(index=0)
# Keep only used 372 tests (without draft substrated and liquids)
df_labels = df_labels[df_labels['Test #'].isin(df.test.values)]
df_labels = df_labels.drop('Comments', axis=1)
df_labels = df_labels.rename({'Test #': 'test'}, axis=1)
df_labels['test'] = df_labels['test'].astype(int)
df_labels = df_labels.reset_index(drop=True)
display(df_labels)
display(df_labels.info())
df_labels.columns

,test,Total number of dropped drops,Number of detached small droplets during Spreading,Droplet Receding,Rim merging or Central jet ejecting,Number of detached small droplets during Receding or Rim merging,Rebound,Number of detached droplets during Rebound,Final droplets count
0,3,1,many,0,0,0,0,0,1
1,4,1,many,0,0,0,0,0,1
2,5,1,many,0,0,0,0,0,1
3,7,0,many,1,0,0,0,0,2
4,8,0,many,0,0,0,0,0,2
...,...,...,...,...,...,...,...,...,...
367,391,0,0,1,2,0,2,0,0
368,392,1,3,1,1,0,0,0,1
369,393,1,2,1,1,0,0,0,3
370,394,1,0,1,1,1,0,0,2
371,395,1,0,1,2,0,2,0,0

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 372 entries, 0 to 371
Data columns (total 9 columns):
 #   Column                                                            Non-Null Count  Dtype
---  ------                                                            --------------  -----
 0   test                                                              372 non-null    int64
 1   Total number of dropped drops                                     372 non-null    object
 2   Number of detached small droplets during Spreading                372 non-null    object
 3   Droplet Receding                                                  372 non-null    object
 4   Rim merging or Central jet ejecting                               372 non-null    object
 5   Number of detached small droplets during Receding or Rim merging  372 non-null    object
 6   Rebound                                                           372 non-null    object
 7   Number of detached droplets during Rebound                        372 non-null    object
 8   Final droplets count                                              372 non-null    object
dtypes: int64(1), object(8)
memory usage: 26.3+ KB

None

Index(['test', 'Total number of dropped drops',
       'Number of detached small droplets during Spreading',
       'Droplet Receding', 'Rim merging or Central jet ejecting',
       'Number of detached small droplets during Receding or Rim merging',
       'Rebound', 'Number of detached droplets during Rebound',
       'Final droplets count'],
      dtype='object')


| Parameter name | Description | Possible values |
| --- | --- | --- |
| Total number of dropped drops | The total number of drops that fell from above | 1, 2 |
| Number of detached small droplets during *spreading* | The number of small droplets that flew out of the lamella drops in the process of spreading | 0, 1, .., 5, many |
| Droplet Receding | Presence (1,2), absence — 0 of a visible drop shrinkage, and an increase in the drop height after reaching the maximum spot diameter. 1 — the usual reduction of the main drop, 2 — the destruction of the main drop in the process of reduction | 0, 1, 2 |
| Rim merging or Central jet ejecting | The presence (1,2), absence — 0 of an explicit rim merging at the end of the shrinkage of the drop (1) and/or the reverse vertical jet (2) (against gravity) | 0, 1, 2 |
| Number of detached small droplets during *Receding or Rim merging* | The number of small droplets separating from the rim of the main drop (rim) and remaining on the substrate during the shrinkage of the drop (receding). Drops do not separate — 0, several drops, many drops — many | 0, 1, .., 5, many |
| Rebound | Presence (1,2), absence — 0 of a drop rebound after the formation of a reverse vertical jet (central jet ejecting). Partial rebound — 1, total rebound - 2 | 0, 1, 2 |
| Number of detached droplets during *Rebound* | The number of droplets separating from the reverse vertical jet (central jet) | 0, 1, .., 5, many |
| Final droplets count | The total number of droplets on the substrate, clearly separated from each other | 1, .., 5, many |

# Research

## Break up dividing. Create 'real_break_up'

**USE** only real_break_up_labels['test'].values for getting a real break_up

How many real break up tests, when *'Number of detached small droplets during Receding or Rim merging' > 0*

In [5]:
real_break_up_labels = df_labels[df_labels['Number of detached small droplets during Receding or Rim merging'] != 0]
real_break_up_count = real_break_up_labels.shape[0]
print(f'Real break_up tests count: {real_break_up_count}')

Real break_up tests count: 60

Let us check, that not_real_break_up cases are happends only if number of detached small droplets during spreading == 'few'

In [6]:
# Not real break up, when label is 'breaking_up', but no detached small droplets during Receding or Rim merging
not_real_break_up = df[(df['breaking_up']==1)&(~df['test'].isin(real_break_up_labels['test'].values))]
not_real_break_up_count = not_real_break_up.shape[0]
print(f'Not real break_up tests count: {not_real_break_up_count}')

Not real break_up tests count: 41

In [11]:
print('Not real break up labels')
not_real_break_up_labels = df_labels[df_labels['test'].isin(not_real_break_up['test'].values)]
display(not_real_break_up_labels['Number of detached small droplets during Spreading'].value_counts())

Not real break up labels

Number of detached small droplets during Spreading
2    15
1     9
3     8
4     5
5     4
Name: count, dtype: int64

Thus, only few small droplets during Spreading cases are in not real break_up

**Thus, let us create a real break up** instead of *break up*

In [8]:
df['real_breaking_up'] = 0
df.loc[real_break_up_labels.index, 'real_breaking_up'] = 1
df['real_breaking_up'].value_counts()

real_breaking_up
0    312
1     60
Name: count, dtype: int64

## Rebound dividing