Metrics comparison with baseline

In [1]:
%load_ext autoreload
%autoreload 2

# Libraries

In [2]:
import os
import sys
from pathlib import Path
sys.path.append(
    str(Path('..', 'utils_functionality', 'split_utils'))
)
sys.path.append(
    str(Path('..', 'utils_functionality', 'models'))
)

import seaborn as sns
import joblib
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
from IPython.display import clear_output

# Data load

In [31]:
df_metrics = pd.read_excel('../results/metrics_modelling4.xlsx')
df_stump = pd.read_excel('../results/metrics_modelling3.xlsx').iloc[-2:]
df_metrics = pd.concat((df_metrics, df_stump)).reset_index(drop=True)

# Update data

In [32]:
df_metrics = df_metrics.loc[
    df_metrics['model'].apply(lambda x:
                              x in [
        'DecisionStump_splashing_greater_or_equal_kl',
        'Logit_splashing_default',
        'CatBoostClassifier_splashing_smote_opt-model'
        ])][[
            'model', 'holdout_test_accuracy',
                      'holdout_test_f1_macro', 'holdout_test_roc_auc'
        ]].sort_values(by=['holdout_test_f1_macro']).reset_index(drop=True)
df_metrics

,model,holdout_test_accuracy,holdout_test_f1_macro,holdout_test_roc_auc
0,DecisionStump_splashing_greater_or_equal_kl,0.773333,0.765150,0.782407
1,Logit_splashing_default,0.800000,0.777184,0.874228
2,CatBoostClassifier_splashing_smote_opt-model,0.893333,0.880000,0.962191

In [34]:
first_model = df_metrics.iloc[0]

for metric in ['holdout_test_accuracy', 'holdout_test_f1_macro',
       'holdout_test_roc_auc']:
    df_metrics[f'{metric}_pct_change'] = ((df_metrics[metric] - first_model[metric]) / first_model[metric]) * 100
    df_metrics.loc[0, f'{metric}_pct_change'] = 0
df_metrics

,model,holdout_test_accuracy,holdout_test_f1_macro,holdout_test_roc_auc,holdout_test_accuracy_pct_change,holdout_test_f1_macro_pct_change,holdout_test_roc_auc_pct_change
0,DecisionStump_splashing_greater_or_equal_kl,0.773333,0.765150,0.782407,0.000000,0.000000,0.000000
1,Logit_splashing_default,0.800000,0.777184,0.874228,3.448276,1.572695,11.735700
2,CatBoostClassifier_splashing_smote_opt-model,0.893333,0.880000,0.962191,15.517241,15.010111,22.978304